/*
Notehub API

Testing WebhookAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package notehub

import (
	"context"
	"testing"

	openapiclient "github.com/blues/notehub-go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_notehub_WebhookAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test WebhookAPIService CreateWebhook", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var projectOrProductUID string
		var webhookUID string

		httpRes, err := apiClient.WebhookAPI.CreateWebhook(context.Background(), projectOrProductUID, webhookUID).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WebhookAPIService DeleteWebhook", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var projectOrProductUID string
		var webhookUID string

		httpRes, err := apiClient.WebhookAPI.DeleteWebhook(context.Background(), projectOrProductUID, webhookUID).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WebhookAPIService GetWebhook", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var projectOrProductUID string
		var webhookUID string

		resp, httpRes, err := apiClient.WebhookAPI.GetWebhook(context.Background(), projectOrProductUID, webhookUID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WebhookAPIService GetWebhooks", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var projectOrProductUID string

		resp, httpRes, err := apiClient.WebhookAPI.GetWebhooks(context.Background(), projectOrProductUID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WebhookAPIService UpdateWebhook", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var projectOrProductUID string
		var webhookUID string

		httpRes, err := apiClient.WebhookAPI.UpdateWebhook(context.Background(), projectOrProductUID, webhookUID).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
