/*
Notehub API

Testing ExternalDevicesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package notehub

import (
	"context"
	"testing"

	openapiclient "github.com/blues/notehub-go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_notehub_ExternalDevicesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ExternalDevicesAPIService CreateEventExtDevice", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var productUID string
		var deviceUID string

		httpRes, err := apiClient.ExternalDevicesAPI.CreateEventExtDevice(context.Background(), productUID, deviceUID).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ExternalDevicesAPIService ExtDeviceSessionClose", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var productUID string
		var deviceUID string

		httpRes, err := apiClient.ExternalDevicesAPI.ExtDeviceSessionClose(context.Background(), productUID, deviceUID).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ExternalDevicesAPIService ExtDeviceSessionOpen", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var productUID string
		var deviceUID string

		httpRes, err := apiClient.ExternalDevicesAPI.ExtDeviceSessionOpen(context.Background(), productUID, deviceUID).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
