/*
Notehub API

Testing EventAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package notehub

import (
	"context"
	"testing"

	openapiclient "github.com/blues/notehub-go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_notehub_EventAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test EventAPIService GetEvents", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var projectOrProductUID string

		resp, httpRes, err := apiClient.EventAPI.GetEvents(context.Background(), projectOrProductUID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EventAPIService GetEventsByCursor", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var projectOrProductUID string

		resp, httpRes, err := apiClient.EventAPI.GetEventsByCursor(context.Background(), projectOrProductUID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EventAPIService GetFleetEvents", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var projectOrProductUID string
		var fleetUID string

		resp, httpRes, err := apiClient.EventAPI.GetFleetEvents(context.Background(), projectOrProductUID, fleetUID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EventAPIService GetFleetEventsByCursor", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var projectOrProductUID string
		var fleetUID string

		resp, httpRes, err := apiClient.EventAPI.GetFleetEventsByCursor(context.Background(), projectOrProductUID, fleetUID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EventAPIService GetRouteLogsByEvent", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var projectOrProductUID string
		var eventUID string

		resp, httpRes, err := apiClient.EventAPI.GetRouteLogsByEvent(context.Background(), projectOrProductUID, eventUID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
