/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the Project type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Project{}

// Project struct for Project
type Project struct {
	AdministrativeContact NullableContact `json:"administrative_contact,omitempty"`
	Created               time.Time       `json:"created"`
	Label                 string          `json:"label"`
	Role                  NullableRole    `json:"role,omitempty"`
	TechnicalContact      NullableContact `json:"technical_contact,omitempty"`
	Uid                   string          `json:"uid"`
}

type _Project Project

// NewProject instantiates a new Project object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProject(created time.Time, label string, uid string) *Project {
	this := Project{}
	this.Created = created
	this.Label = label
	this.Uid = uid
	return &this
}

// NewProjectWithDefaults instantiates a new Project object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectWithDefaults() *Project {
	this := Project{}
	return &this
}

// GetAdministrativeContact returns the AdministrativeContact field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Project) GetAdministrativeContact() Contact {
	if o == nil || IsNil(o.AdministrativeContact.Get()) {
		var ret Contact
		return ret
	}
	return *o.AdministrativeContact.Get()
}

// GetAdministrativeContactOk returns a tuple with the AdministrativeContact field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Project) GetAdministrativeContactOk() (*Contact, bool) {
	if o == nil {
		return nil, false
	}
	return o.AdministrativeContact.Get(), o.AdministrativeContact.IsSet()
}

// HasAdministrativeContact returns a boolean if a field has been set.
func (o *Project) HasAdministrativeContact() bool {
	if o != nil && o.AdministrativeContact.IsSet() {
		return true
	}

	return false
}

// SetAdministrativeContact gets a reference to the given NullableContact and assigns it to the AdministrativeContact field.
func (o *Project) SetAdministrativeContact(v Contact) {
	o.AdministrativeContact.Set(&v)
}

// SetAdministrativeContactNil sets the value for AdministrativeContact to be an explicit nil
func (o *Project) SetAdministrativeContactNil() {
	o.AdministrativeContact.Set(nil)
}

// UnsetAdministrativeContact ensures that no value is present for AdministrativeContact, not even an explicit nil
func (o *Project) UnsetAdministrativeContact() {
	o.AdministrativeContact.Unset()
}

// GetCreated returns the Created field value
func (o *Project) GetCreated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *Project) GetCreatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *Project) SetCreated(v time.Time) {
	o.Created = v
}

// GetLabel returns the Label field value
func (o *Project) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *Project) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *Project) SetLabel(v string) {
	o.Label = v
}

// GetRole returns the Role field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Project) GetRole() Role {
	if o == nil || IsNil(o.Role.Get()) {
		var ret Role
		return ret
	}
	return *o.Role.Get()
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Project) GetRoleOk() (*Role, bool) {
	if o == nil {
		return nil, false
	}
	return o.Role.Get(), o.Role.IsSet()
}

// HasRole returns a boolean if a field has been set.
func (o *Project) HasRole() bool {
	if o != nil && o.Role.IsSet() {
		return true
	}

	return false
}

// SetRole gets a reference to the given NullableRole and assigns it to the Role field.
func (o *Project) SetRole(v Role) {
	o.Role.Set(&v)
}

// SetRoleNil sets the value for Role to be an explicit nil
func (o *Project) SetRoleNil() {
	o.Role.Set(nil)
}

// UnsetRole ensures that no value is present for Role, not even an explicit nil
func (o *Project) UnsetRole() {
	o.Role.Unset()
}

// GetTechnicalContact returns the TechnicalContact field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Project) GetTechnicalContact() Contact {
	if o == nil || IsNil(o.TechnicalContact.Get()) {
		var ret Contact
		return ret
	}
	return *o.TechnicalContact.Get()
}

// GetTechnicalContactOk returns a tuple with the TechnicalContact field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Project) GetTechnicalContactOk() (*Contact, bool) {
	if o == nil {
		return nil, false
	}
	return o.TechnicalContact.Get(), o.TechnicalContact.IsSet()
}

// HasTechnicalContact returns a boolean if a field has been set.
func (o *Project) HasTechnicalContact() bool {
	if o != nil && o.TechnicalContact.IsSet() {
		return true
	}

	return false
}

// SetTechnicalContact gets a reference to the given NullableContact and assigns it to the TechnicalContact field.
func (o *Project) SetTechnicalContact(v Contact) {
	o.TechnicalContact.Set(&v)
}

// SetTechnicalContactNil sets the value for TechnicalContact to be an explicit nil
func (o *Project) SetTechnicalContactNil() {
	o.TechnicalContact.Set(nil)
}

// UnsetTechnicalContact ensures that no value is present for TechnicalContact, not even an explicit nil
func (o *Project) UnsetTechnicalContact() {
	o.TechnicalContact.Unset()
}

// GetUid returns the Uid field value
func (o *Project) GetUid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uid
}

// GetUidOk returns a tuple with the Uid field value
// and a boolean to check if the value has been set.
func (o *Project) GetUidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uid, true
}

// SetUid sets field value
func (o *Project) SetUid(v string) {
	o.Uid = v
}

func (o Project) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Project) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.AdministrativeContact.IsSet() {
		toSerialize["administrative_contact"] = o.AdministrativeContact.Get()
	}
	toSerialize["created"] = o.Created
	toSerialize["label"] = o.Label
	if o.Role.IsSet() {
		toSerialize["role"] = o.Role.Get()
	}
	if o.TechnicalContact.IsSet() {
		toSerialize["technical_contact"] = o.TechnicalContact.Get()
	}
	toSerialize["uid"] = o.Uid
	return toSerialize, nil
}

func (o *Project) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"created",
		"label",
		"uid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProject := _Project{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProject)

	if err != nil {
		return err
	}

	*o = Project(varProject)

	return err
}

type NullableProject struct {
	value *Project
	isSet bool
}

func (v NullableProject) Get() *Project {
	return v.value
}

func (v *NullableProject) Set(val *Project) {
	v.value = val
	v.isSet = true
}

func (v NullableProject) IsSet() bool {
	return v.isSet
}

func (v *NullableProject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProject(val *Project) *NullableProject {
	return &NullableProject{value: val, isSet: true}
}

func (v NullableProject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
