/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetDeviceFleets200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetDeviceFleets200Response{}

// GetDeviceFleets200Response struct for GetDeviceFleets200Response
type GetDeviceFleets200Response struct {
	Fleets []Fleet `json:"fleets"`
}

type _GetDeviceFleets200Response GetDeviceFleets200Response

// NewGetDeviceFleets200Response instantiates a new GetDeviceFleets200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetDeviceFleets200Response(fleets []Fleet) *GetDeviceFleets200Response {
	this := GetDeviceFleets200Response{}
	this.Fleets = fleets
	return &this
}

// NewGetDeviceFleets200ResponseWithDefaults instantiates a new GetDeviceFleets200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetDeviceFleets200ResponseWithDefaults() *GetDeviceFleets200Response {
	this := GetDeviceFleets200Response{}
	return &this
}

// GetFleets returns the Fleets field value
func (o *GetDeviceFleets200Response) GetFleets() []Fleet {
	if o == nil {
		var ret []Fleet
		return ret
	}

	return o.Fleets
}

// GetFleetsOk returns a tuple with the Fleets field value
// and a boolean to check if the value has been set.
func (o *GetDeviceFleets200Response) GetFleetsOk() ([]Fleet, bool) {
	if o == nil {
		return nil, false
	}
	return o.Fleets, true
}

// SetFleets sets field value
func (o *GetDeviceFleets200Response) SetFleets(v []Fleet) {
	o.Fleets = v
}

func (o GetDeviceFleets200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetDeviceFleets200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["fleets"] = o.Fleets
	return toSerialize, nil
}

func (o *GetDeviceFleets200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fleets",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetDeviceFleets200Response := _GetDeviceFleets200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetDeviceFleets200Response)

	if err != nil {
		return err
	}

	*o = GetDeviceFleets200Response(varGetDeviceFleets200Response)

	return err
}

type NullableGetDeviceFleets200Response struct {
	value *GetDeviceFleets200Response
	isSet bool
}

func (v NullableGetDeviceFleets200Response) Get() *GetDeviceFleets200Response {
	return v.value
}

func (v *NullableGetDeviceFleets200Response) Set(val *GetDeviceFleets200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDeviceFleets200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDeviceFleets200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDeviceFleets200Response(val *GetDeviceFleets200Response) *NullableGetDeviceFleets200Response {
	return &NullableGetDeviceFleets200Response{value: val, isSet: true}
}

func (v NullableGetDeviceFleets200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetDeviceFleets200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
