/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DataUsage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DataUsage{}

// DataUsage struct for DataUsage
type DataUsage struct {
	// Kilobytes remaining in the plan
	KbRemaining float64 `json:"kb_remaining"`
	// Total Kilobytes included in the plan
	KbTotal float64 `json:"kb_total"`
	// Kilobytes used to date
	KbUsed float64 `json:"kb_used"`
}

type _DataUsage DataUsage

// NewDataUsage instantiates a new DataUsage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataUsage(kbRemaining float64, kbTotal float64, kbUsed float64) *DataUsage {
	this := DataUsage{}
	this.KbRemaining = kbRemaining
	this.KbTotal = kbTotal
	this.KbUsed = kbUsed
	return &this
}

// NewDataUsageWithDefaults instantiates a new DataUsage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataUsageWithDefaults() *DataUsage {
	this := DataUsage{}
	return &this
}

// GetKbRemaining returns the KbRemaining field value
func (o *DataUsage) GetKbRemaining() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.KbRemaining
}

// GetKbRemainingOk returns a tuple with the KbRemaining field value
// and a boolean to check if the value has been set.
func (o *DataUsage) GetKbRemainingOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KbRemaining, true
}

// SetKbRemaining sets field value
func (o *DataUsage) SetKbRemaining(v float64) {
	o.KbRemaining = v
}

// GetKbTotal returns the KbTotal field value
func (o *DataUsage) GetKbTotal() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.KbTotal
}

// GetKbTotalOk returns a tuple with the KbTotal field value
// and a boolean to check if the value has been set.
func (o *DataUsage) GetKbTotalOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KbTotal, true
}

// SetKbTotal sets field value
func (o *DataUsage) SetKbTotal(v float64) {
	o.KbTotal = v
}

// GetKbUsed returns the KbUsed field value
func (o *DataUsage) GetKbUsed() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.KbUsed
}

// GetKbUsedOk returns a tuple with the KbUsed field value
// and a boolean to check if the value has been set.
func (o *DataUsage) GetKbUsedOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KbUsed, true
}

// SetKbUsed sets field value
func (o *DataUsage) SetKbUsed(v float64) {
	o.KbUsed = v
}

func (o DataUsage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DataUsage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["kb_remaining"] = o.KbRemaining
	toSerialize["kb_total"] = o.KbTotal
	toSerialize["kb_used"] = o.KbUsed
	return toSerialize, nil
}

func (o *DataUsage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"kb_remaining",
		"kb_total",
		"kb_used",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDataUsage := _DataUsage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDataUsage)

	if err != nil {
		return err
	}

	*o = DataUsage(varDataUsage)

	return err
}

type NullableDataUsage struct {
	value *DataUsage
	isSet bool
}

func (v NullableDataUsage) Get() *DataUsage {
	return v.value
}

func (v *NullableDataUsage) Set(val *DataUsage) {
	v.value = val
	v.isSet = true
}

func (v NullableDataUsage) IsSet() bool {
	return v.isSet
}

func (v *NullableDataUsage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataUsage(val *DataUsage) *NullableDataUsage {
	return &NullableDataUsage{value: val, isSet: true}
}

func (v NullableDataUsage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataUsage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
