/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetEvents200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetEvents200Response{}

// GetEvents200Response struct for GetEvents200Response
type GetEvents200Response struct {
	Events []Event `json:"events"`
	// True if there are more events
	HasMore bool `json:"has_more"`
	// The UID of the last event returned
	Through *string `json:"through,omitempty"`
}

type _GetEvents200Response GetEvents200Response

// NewGetEvents200Response instantiates a new GetEvents200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEvents200Response(events []Event, hasMore bool) *GetEvents200Response {
	this := GetEvents200Response{}
	this.Events = events
	this.HasMore = hasMore
	return &this
}

// NewGetEvents200ResponseWithDefaults instantiates a new GetEvents200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEvents200ResponseWithDefaults() *GetEvents200Response {
	this := GetEvents200Response{}
	return &this
}

// GetEvents returns the Events field value
func (o *GetEvents200Response) GetEvents() []Event {
	if o == nil {
		var ret []Event
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *GetEvents200Response) GetEventsOk() ([]Event, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *GetEvents200Response) SetEvents(v []Event) {
	o.Events = v
}

// GetHasMore returns the HasMore field value
func (o *GetEvents200Response) GetHasMore() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value
// and a boolean to check if the value has been set.
func (o *GetEvents200Response) GetHasMoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasMore, true
}

// SetHasMore sets field value
func (o *GetEvents200Response) SetHasMore(v bool) {
	o.HasMore = v
}

// GetThrough returns the Through field value if set, zero value otherwise.
func (o *GetEvents200Response) GetThrough() string {
	if o == nil || IsNil(o.Through) {
		var ret string
		return ret
	}
	return *o.Through
}

// GetThroughOk returns a tuple with the Through field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEvents200Response) GetThroughOk() (*string, bool) {
	if o == nil || IsNil(o.Through) {
		return nil, false
	}
	return o.Through, true
}

// HasThrough returns a boolean if a field has been set.
func (o *GetEvents200Response) HasThrough() bool {
	if o != nil && !IsNil(o.Through) {
		return true
	}

	return false
}

// SetThrough gets a reference to the given string and assigns it to the Through field.
func (o *GetEvents200Response) SetThrough(v string) {
	o.Through = &v
}

func (o GetEvents200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetEvents200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["events"] = o.Events
	toSerialize["has_more"] = o.HasMore
	if !IsNil(o.Through) {
		toSerialize["through"] = o.Through
	}
	return toSerialize, nil
}

func (o *GetEvents200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"events",
		"has_more",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetEvents200Response := _GetEvents200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetEvents200Response)

	if err != nil {
		return err
	}

	*o = GetEvents200Response(varGetEvents200Response)

	return err
}

type NullableGetEvents200Response struct {
	value *GetEvents200Response
	isSet bool
}

func (v NullableGetEvents200Response) Get() *GetEvents200Response {
	return v.value
}

func (v *NullableGetEvents200Response) Set(val *GetEvents200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEvents200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEvents200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEvents200Response(val *GetEvents200Response) *NullableGetEvents200Response {
	return &NullableGetEvents200Response{value: val, isSet: true}
}

func (v NullableGetEvents200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEvents200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
