/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetEventsByCursor200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetEventsByCursor200Response{}

// GetEventsByCursor200Response struct for GetEventsByCursor200Response
type GetEventsByCursor200Response struct {
	Events []Event `json:"events"`
	// True if there are more events
	HasMore bool `json:"has_more"`
	// The cursor value of the next result, which is intended to be used as the \"cursor\" parameter value of the next call to this method. An empty string is returned if there are no more results after this results set.
	NextCursor string `json:"next_cursor"`
}

type _GetEventsByCursor200Response GetEventsByCursor200Response

// NewGetEventsByCursor200Response instantiates a new GetEventsByCursor200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEventsByCursor200Response(events []Event, hasMore bool, nextCursor string) *GetEventsByCursor200Response {
	this := GetEventsByCursor200Response{}
	this.Events = events
	this.HasMore = hasMore
	this.NextCursor = nextCursor
	return &this
}

// NewGetEventsByCursor200ResponseWithDefaults instantiates a new GetEventsByCursor200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEventsByCursor200ResponseWithDefaults() *GetEventsByCursor200Response {
	this := GetEventsByCursor200Response{}
	return &this
}

// GetEvents returns the Events field value
func (o *GetEventsByCursor200Response) GetEvents() []Event {
	if o == nil {
		var ret []Event
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *GetEventsByCursor200Response) GetEventsOk() ([]Event, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *GetEventsByCursor200Response) SetEvents(v []Event) {
	o.Events = v
}

// GetHasMore returns the HasMore field value
func (o *GetEventsByCursor200Response) GetHasMore() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value
// and a boolean to check if the value has been set.
func (o *GetEventsByCursor200Response) GetHasMoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasMore, true
}

// SetHasMore sets field value
func (o *GetEventsByCursor200Response) SetHasMore(v bool) {
	o.HasMore = v
}

// GetNextCursor returns the NextCursor field value
func (o *GetEventsByCursor200Response) GetNextCursor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NextCursor
}

// GetNextCursorOk returns a tuple with the NextCursor field value
// and a boolean to check if the value has been set.
func (o *GetEventsByCursor200Response) GetNextCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NextCursor, true
}

// SetNextCursor sets field value
func (o *GetEventsByCursor200Response) SetNextCursor(v string) {
	o.NextCursor = v
}

func (o GetEventsByCursor200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetEventsByCursor200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["events"] = o.Events
	toSerialize["has_more"] = o.HasMore
	toSerialize["next_cursor"] = o.NextCursor
	return toSerialize, nil
}

func (o *GetEventsByCursor200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"events",
		"has_more",
		"next_cursor",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetEventsByCursor200Response := _GetEventsByCursor200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetEventsByCursor200Response)

	if err != nil {
		return err
	}

	*o = GetEventsByCursor200Response(varGetEventsByCursor200Response)

	return err
}

type NullableGetEventsByCursor200Response struct {
	value *GetEventsByCursor200Response
	isSet bool
}

func (v NullableGetEventsByCursor200Response) Get() *GetEventsByCursor200Response {
	return v.value
}

func (v *NullableGetEventsByCursor200Response) Set(val *GetEventsByCursor200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEventsByCursor200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEventsByCursor200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEventsByCursor200Response(val *GetEventsByCursor200Response) *NullableGetEventsByCursor200Response {
	return &NullableGetEventsByCursor200Response{value: val, isSet: true}
}

func (v NullableGetEventsByCursor200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEventsByCursor200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
