/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"encoding/json"
)

// checks if the CreatedRepository type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatedRepository{}

// CreatedRepository struct for CreatedRepository
type CreatedRepository struct {
	FleetUids []string `json:"fleet_uids,omitempty"`
	// repository name
	Name *string `json:"name,omitempty"`
	// read-only password for the database, also used as X-Repository-Token header for subsequent API calls.  This value is only served once when the repository is created
	Password    *string  `json:"password,omitempty"`
	ProjectUids []string `json:"project_uids,omitempty"`
	// The unique identifier for the data repository
	Uid *string `json:"uid,omitempty"`
	// read-only user for database
	User                 *string `json:"user,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreatedRepository CreatedRepository

// NewCreatedRepository instantiates a new CreatedRepository object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatedRepository() *CreatedRepository {
	this := CreatedRepository{}
	return &this
}

// NewCreatedRepositoryWithDefaults instantiates a new CreatedRepository object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatedRepositoryWithDefaults() *CreatedRepository {
	this := CreatedRepository{}
	return &this
}

// GetFleetUids returns the FleetUids field value if set, zero value otherwise.
func (o *CreatedRepository) GetFleetUids() []string {
	if o == nil || IsNil(o.FleetUids) {
		var ret []string
		return ret
	}
	return o.FleetUids
}

// GetFleetUidsOk returns a tuple with the FleetUids field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatedRepository) GetFleetUidsOk() ([]string, bool) {
	if o == nil || IsNil(o.FleetUids) {
		return nil, false
	}
	return o.FleetUids, true
}

// HasFleetUids returns a boolean if a field has been set.
func (o *CreatedRepository) HasFleetUids() bool {
	if o != nil && !IsNil(o.FleetUids) {
		return true
	}

	return false
}

// SetFleetUids gets a reference to the given []string and assigns it to the FleetUids field.
func (o *CreatedRepository) SetFleetUids(v []string) {
	o.FleetUids = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreatedRepository) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatedRepository) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreatedRepository) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreatedRepository) SetName(v string) {
	o.Name = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *CreatedRepository) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatedRepository) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *CreatedRepository) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *CreatedRepository) SetPassword(v string) {
	o.Password = &v
}

// GetProjectUids returns the ProjectUids field value if set, zero value otherwise.
func (o *CreatedRepository) GetProjectUids() []string {
	if o == nil || IsNil(o.ProjectUids) {
		var ret []string
		return ret
	}
	return o.ProjectUids
}

// GetProjectUidsOk returns a tuple with the ProjectUids field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatedRepository) GetProjectUidsOk() ([]string, bool) {
	if o == nil || IsNil(o.ProjectUids) {
		return nil, false
	}
	return o.ProjectUids, true
}

// HasProjectUids returns a boolean if a field has been set.
func (o *CreatedRepository) HasProjectUids() bool {
	if o != nil && !IsNil(o.ProjectUids) {
		return true
	}

	return false
}

// SetProjectUids gets a reference to the given []string and assigns it to the ProjectUids field.
func (o *CreatedRepository) SetProjectUids(v []string) {
	o.ProjectUids = v
}

// GetUid returns the Uid field value if set, zero value otherwise.
func (o *CreatedRepository) GetUid() string {
	if o == nil || IsNil(o.Uid) {
		var ret string
		return ret
	}
	return *o.Uid
}

// GetUidOk returns a tuple with the Uid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatedRepository) GetUidOk() (*string, bool) {
	if o == nil || IsNil(o.Uid) {
		return nil, false
	}
	return o.Uid, true
}

// HasUid returns a boolean if a field has been set.
func (o *CreatedRepository) HasUid() bool {
	if o != nil && !IsNil(o.Uid) {
		return true
	}

	return false
}

// SetUid gets a reference to the given string and assigns it to the Uid field.
func (o *CreatedRepository) SetUid(v string) {
	o.Uid = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *CreatedRepository) GetUser() string {
	if o == nil || IsNil(o.User) {
		var ret string
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatedRepository) GetUserOk() (*string, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *CreatedRepository) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given string and assigns it to the User field.
func (o *CreatedRepository) SetUser(v string) {
	o.User = &v
}

func (o CreatedRepository) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatedRepository) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FleetUids) {
		toSerialize["fleet_uids"] = o.FleetUids
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	if !IsNil(o.ProjectUids) {
		toSerialize["project_uids"] = o.ProjectUids
	}
	if !IsNil(o.Uid) {
		toSerialize["uid"] = o.Uid
	}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreatedRepository) UnmarshalJSON(data []byte) (err error) {
	varCreatedRepository := _CreatedRepository{}

	err = json.Unmarshal(data, &varCreatedRepository)

	if err != nil {
		return err
	}

	*o = CreatedRepository(varCreatedRepository)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "fleet_uids")
		delete(additionalProperties, "name")
		delete(additionalProperties, "password")
		delete(additionalProperties, "project_uids")
		delete(additionalProperties, "uid")
		delete(additionalProperties, "user")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreatedRepository struct {
	value *CreatedRepository
	isSet bool
}

func (v NullableCreatedRepository) Get() *CreatedRepository {
	return v.value
}

func (v *NullableCreatedRepository) Set(val *CreatedRepository) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatedRepository) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatedRepository) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatedRepository(val *CreatedRepository) *NullableCreatedRepository {
	return &NullableCreatedRepository{value: val, isSet: true}
}

func (v NullableCreatedRepository) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatedRepository) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
