/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"encoding/json"
)

// checks if the Firmware type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Firmware{}

// Firmware struct for Firmware
type Firmware struct {
	Builder  *string `json:"builder,omitempty"`
	Built    *string `json:"built,omitempty"`
	Firmware *string `json:"firmware,omitempty"`
	Org      *string `json:"org,omitempty"`
	Product  *string `json:"product,omitempty"`
	Target   *string `json:"target,omitempty"`
	VerBuild *int32  `json:"ver_build,omitempty"`
	VerMajor *int32  `json:"ver_major,omitempty"`
	VerMinor *int32  `json:"ver_minor,omitempty"`
	VerPatch *int32  `json:"ver_patch,omitempty"`
	Version  *string `json:"version,omitempty"`
}

// NewFirmware instantiates a new Firmware object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFirmware() *Firmware {
	this := Firmware{}
	return &this
}

// NewFirmwareWithDefaults instantiates a new Firmware object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFirmwareWithDefaults() *Firmware {
	this := Firmware{}
	return &this
}

// GetBuilder returns the Builder field value if set, zero value otherwise.
func (o *Firmware) GetBuilder() string {
	if o == nil || IsNil(o.Builder) {
		var ret string
		return ret
	}
	return *o.Builder
}

// GetBuilderOk returns a tuple with the Builder field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Firmware) GetBuilderOk() (*string, bool) {
	if o == nil || IsNil(o.Builder) {
		return nil, false
	}
	return o.Builder, true
}

// HasBuilder returns a boolean if a field has been set.
func (o *Firmware) HasBuilder() bool {
	if o != nil && !IsNil(o.Builder) {
		return true
	}

	return false
}

// SetBuilder gets a reference to the given string and assigns it to the Builder field.
func (o *Firmware) SetBuilder(v string) {
	o.Builder = &v
}

// GetBuilt returns the Built field value if set, zero value otherwise.
func (o *Firmware) GetBuilt() string {
	if o == nil || IsNil(o.Built) {
		var ret string
		return ret
	}
	return *o.Built
}

// GetBuiltOk returns a tuple with the Built field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Firmware) GetBuiltOk() (*string, bool) {
	if o == nil || IsNil(o.Built) {
		return nil, false
	}
	return o.Built, true
}

// HasBuilt returns a boolean if a field has been set.
func (o *Firmware) HasBuilt() bool {
	if o != nil && !IsNil(o.Built) {
		return true
	}

	return false
}

// SetBuilt gets a reference to the given string and assigns it to the Built field.
func (o *Firmware) SetBuilt(v string) {
	o.Built = &v
}

// GetFirmware returns the Firmware field value if set, zero value otherwise.
func (o *Firmware) GetFirmware() string {
	if o == nil || IsNil(o.Firmware) {
		var ret string
		return ret
	}
	return *o.Firmware
}

// GetFirmwareOk returns a tuple with the Firmware field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Firmware) GetFirmwareOk() (*string, bool) {
	if o == nil || IsNil(o.Firmware) {
		return nil, false
	}
	return o.Firmware, true
}

// HasFirmware returns a boolean if a field has been set.
func (o *Firmware) HasFirmware() bool {
	if o != nil && !IsNil(o.Firmware) {
		return true
	}

	return false
}

// SetFirmware gets a reference to the given string and assigns it to the Firmware field.
func (o *Firmware) SetFirmware(v string) {
	o.Firmware = &v
}

// GetOrg returns the Org field value if set, zero value otherwise.
func (o *Firmware) GetOrg() string {
	if o == nil || IsNil(o.Org) {
		var ret string
		return ret
	}
	return *o.Org
}

// GetOrgOk returns a tuple with the Org field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Firmware) GetOrgOk() (*string, bool) {
	if o == nil || IsNil(o.Org) {
		return nil, false
	}
	return o.Org, true
}

// HasOrg returns a boolean if a field has been set.
func (o *Firmware) HasOrg() bool {
	if o != nil && !IsNil(o.Org) {
		return true
	}

	return false
}

// SetOrg gets a reference to the given string and assigns it to the Org field.
func (o *Firmware) SetOrg(v string) {
	o.Org = &v
}

// GetProduct returns the Product field value if set, zero value otherwise.
func (o *Firmware) GetProduct() string {
	if o == nil || IsNil(o.Product) {
		var ret string
		return ret
	}
	return *o.Product
}

// GetProductOk returns a tuple with the Product field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Firmware) GetProductOk() (*string, bool) {
	if o == nil || IsNil(o.Product) {
		return nil, false
	}
	return o.Product, true
}

// HasProduct returns a boolean if a field has been set.
func (o *Firmware) HasProduct() bool {
	if o != nil && !IsNil(o.Product) {
		return true
	}

	return false
}

// SetProduct gets a reference to the given string and assigns it to the Product field.
func (o *Firmware) SetProduct(v string) {
	o.Product = &v
}

// GetTarget returns the Target field value if set, zero value otherwise.
func (o *Firmware) GetTarget() string {
	if o == nil || IsNil(o.Target) {
		var ret string
		return ret
	}
	return *o.Target
}

// GetTargetOk returns a tuple with the Target field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Firmware) GetTargetOk() (*string, bool) {
	if o == nil || IsNil(o.Target) {
		return nil, false
	}
	return o.Target, true
}

// HasTarget returns a boolean if a field has been set.
func (o *Firmware) HasTarget() bool {
	if o != nil && !IsNil(o.Target) {
		return true
	}

	return false
}

// SetTarget gets a reference to the given string and assigns it to the Target field.
func (o *Firmware) SetTarget(v string) {
	o.Target = &v
}

// GetVerBuild returns the VerBuild field value if set, zero value otherwise.
func (o *Firmware) GetVerBuild() int32 {
	if o == nil || IsNil(o.VerBuild) {
		var ret int32
		return ret
	}
	return *o.VerBuild
}

// GetVerBuildOk returns a tuple with the VerBuild field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Firmware) GetVerBuildOk() (*int32, bool) {
	if o == nil || IsNil(o.VerBuild) {
		return nil, false
	}
	return o.VerBuild, true
}

// HasVerBuild returns a boolean if a field has been set.
func (o *Firmware) HasVerBuild() bool {
	if o != nil && !IsNil(o.VerBuild) {
		return true
	}

	return false
}

// SetVerBuild gets a reference to the given int32 and assigns it to the VerBuild field.
func (o *Firmware) SetVerBuild(v int32) {
	o.VerBuild = &v
}

// GetVerMajor returns the VerMajor field value if set, zero value otherwise.
func (o *Firmware) GetVerMajor() int32 {
	if o == nil || IsNil(o.VerMajor) {
		var ret int32
		return ret
	}
	return *o.VerMajor
}

// GetVerMajorOk returns a tuple with the VerMajor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Firmware) GetVerMajorOk() (*int32, bool) {
	if o == nil || IsNil(o.VerMajor) {
		return nil, false
	}
	return o.VerMajor, true
}

// HasVerMajor returns a boolean if a field has been set.
func (o *Firmware) HasVerMajor() bool {
	if o != nil && !IsNil(o.VerMajor) {
		return true
	}

	return false
}

// SetVerMajor gets a reference to the given int32 and assigns it to the VerMajor field.
func (o *Firmware) SetVerMajor(v int32) {
	o.VerMajor = &v
}

// GetVerMinor returns the VerMinor field value if set, zero value otherwise.
func (o *Firmware) GetVerMinor() int32 {
	if o == nil || IsNil(o.VerMinor) {
		var ret int32
		return ret
	}
	return *o.VerMinor
}

// GetVerMinorOk returns a tuple with the VerMinor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Firmware) GetVerMinorOk() (*int32, bool) {
	if o == nil || IsNil(o.VerMinor) {
		return nil, false
	}
	return o.VerMinor, true
}

// HasVerMinor returns a boolean if a field has been set.
func (o *Firmware) HasVerMinor() bool {
	if o != nil && !IsNil(o.VerMinor) {
		return true
	}

	return false
}

// SetVerMinor gets a reference to the given int32 and assigns it to the VerMinor field.
func (o *Firmware) SetVerMinor(v int32) {
	o.VerMinor = &v
}

// GetVerPatch returns the VerPatch field value if set, zero value otherwise.
func (o *Firmware) GetVerPatch() int32 {
	if o == nil || IsNil(o.VerPatch) {
		var ret int32
		return ret
	}
	return *o.VerPatch
}

// GetVerPatchOk returns a tuple with the VerPatch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Firmware) GetVerPatchOk() (*int32, bool) {
	if o == nil || IsNil(o.VerPatch) {
		return nil, false
	}
	return o.VerPatch, true
}

// HasVerPatch returns a boolean if a field has been set.
func (o *Firmware) HasVerPatch() bool {
	if o != nil && !IsNil(o.VerPatch) {
		return true
	}

	return false
}

// SetVerPatch gets a reference to the given int32 and assigns it to the VerPatch field.
func (o *Firmware) SetVerPatch(v int32) {
	o.VerPatch = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *Firmware) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Firmware) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *Firmware) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *Firmware) SetVersion(v string) {
	o.Version = &v
}

func (o Firmware) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Firmware) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Builder) {
		toSerialize["builder"] = o.Builder
	}
	if !IsNil(o.Built) {
		toSerialize["built"] = o.Built
	}
	if !IsNil(o.Firmware) {
		toSerialize["firmware"] = o.Firmware
	}
	if !IsNil(o.Org) {
		toSerialize["org"] = o.Org
	}
	if !IsNil(o.Product) {
		toSerialize["product"] = o.Product
	}
	if !IsNil(o.Target) {
		toSerialize["target"] = o.Target
	}
	if !IsNil(o.VerBuild) {
		toSerialize["ver_build"] = o.VerBuild
	}
	if !IsNil(o.VerMajor) {
		toSerialize["ver_major"] = o.VerMajor
	}
	if !IsNil(o.VerMinor) {
		toSerialize["ver_minor"] = o.VerMinor
	}
	if !IsNil(o.VerPatch) {
		toSerialize["ver_patch"] = o.VerPatch
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableFirmware struct {
	value *Firmware
	isSet bool
}

func (v NullableFirmware) Get() *Firmware {
	return v.value
}

func (v *NullableFirmware) Set(val *Firmware) {
	v.value = val
	v.isSet = true
}

func (v NullableFirmware) IsSet() bool {
	return v.isSet
}

func (v *NullableFirmware) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFirmware(val *Firmware) *NullableFirmware {
	return &NullableFirmware{value: val, isSet: true}
}

func (v NullableFirmware) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFirmware) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
