/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"encoding/json"
)

// checks if the S3ArchiveRoute type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &S3ArchiveRoute{}

// S3ArchiveRoute struct for S3ArchiveRoute
type S3ArchiveRoute struct {
	ArchiveCountExceeds *int32                  `json:"archive_count_exceeds,omitempty"`
	ArchiveEveryMins    *int32                  `json:"archive_every_mins,omitempty"`
	ArchiveId           *string                 `json:"archive_id,omitempty"`
	BucketEndpoint      *string                 `json:"bucket_endpoint,omitempty"`
	BucketName          *string                 `json:"bucket_name,omitempty"`
	BucketRegion        *string                 `json:"bucket_region,omitempty"`
	FileAccess          *string                 `json:"file_access,omitempty"`
	FileFolder          *string                 `json:"file_folder,omitempty"`
	FileFormat          *string                 `json:"file_format,omitempty"`
	Filter              *Filter                 `json:"filter,omitempty"`
	Fleets              []string                `json:"fleets,omitempty"`
	KeyId               *string                 `json:"key_id,omitempty"`
	KeySecret           *string                 `json:"key_secret,omitempty"`
	ThrottleMs          *int32                  `json:"throttle_ms,omitempty"`
	Timeout             *int32                  `json:"timeout,omitempty"`
	Transform           *RouteTransformSettings `json:"transform,omitempty"`
	Url                 *string                 `json:"url,omitempty"`
}

// NewS3ArchiveRoute instantiates a new S3ArchiveRoute object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewS3ArchiveRoute() *S3ArchiveRoute {
	this := S3ArchiveRoute{}
	return &this
}

// NewS3ArchiveRouteWithDefaults instantiates a new S3ArchiveRoute object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewS3ArchiveRouteWithDefaults() *S3ArchiveRoute {
	this := S3ArchiveRoute{}
	return &this
}

// GetArchiveCountExceeds returns the ArchiveCountExceeds field value if set, zero value otherwise.
func (o *S3ArchiveRoute) GetArchiveCountExceeds() int32 {
	if o == nil || IsNil(o.ArchiveCountExceeds) {
		var ret int32
		return ret
	}
	return *o.ArchiveCountExceeds
}

// GetArchiveCountExceedsOk returns a tuple with the ArchiveCountExceeds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3ArchiveRoute) GetArchiveCountExceedsOk() (*int32, bool) {
	if o == nil || IsNil(o.ArchiveCountExceeds) {
		return nil, false
	}
	return o.ArchiveCountExceeds, true
}

// HasArchiveCountExceeds returns a boolean if a field has been set.
func (o *S3ArchiveRoute) HasArchiveCountExceeds() bool {
	if o != nil && !IsNil(o.ArchiveCountExceeds) {
		return true
	}

	return false
}

// SetArchiveCountExceeds gets a reference to the given int32 and assigns it to the ArchiveCountExceeds field.
func (o *S3ArchiveRoute) SetArchiveCountExceeds(v int32) {
	o.ArchiveCountExceeds = &v
}

// GetArchiveEveryMins returns the ArchiveEveryMins field value if set, zero value otherwise.
func (o *S3ArchiveRoute) GetArchiveEveryMins() int32 {
	if o == nil || IsNil(o.ArchiveEveryMins) {
		var ret int32
		return ret
	}
	return *o.ArchiveEveryMins
}

// GetArchiveEveryMinsOk returns a tuple with the ArchiveEveryMins field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3ArchiveRoute) GetArchiveEveryMinsOk() (*int32, bool) {
	if o == nil || IsNil(o.ArchiveEveryMins) {
		return nil, false
	}
	return o.ArchiveEveryMins, true
}

// HasArchiveEveryMins returns a boolean if a field has been set.
func (o *S3ArchiveRoute) HasArchiveEveryMins() bool {
	if o != nil && !IsNil(o.ArchiveEveryMins) {
		return true
	}

	return false
}

// SetArchiveEveryMins gets a reference to the given int32 and assigns it to the ArchiveEveryMins field.
func (o *S3ArchiveRoute) SetArchiveEveryMins(v int32) {
	o.ArchiveEveryMins = &v
}

// GetArchiveId returns the ArchiveId field value if set, zero value otherwise.
func (o *S3ArchiveRoute) GetArchiveId() string {
	if o == nil || IsNil(o.ArchiveId) {
		var ret string
		return ret
	}
	return *o.ArchiveId
}

// GetArchiveIdOk returns a tuple with the ArchiveId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3ArchiveRoute) GetArchiveIdOk() (*string, bool) {
	if o == nil || IsNil(o.ArchiveId) {
		return nil, false
	}
	return o.ArchiveId, true
}

// HasArchiveId returns a boolean if a field has been set.
func (o *S3ArchiveRoute) HasArchiveId() bool {
	if o != nil && !IsNil(o.ArchiveId) {
		return true
	}

	return false
}

// SetArchiveId gets a reference to the given string and assigns it to the ArchiveId field.
func (o *S3ArchiveRoute) SetArchiveId(v string) {
	o.ArchiveId = &v
}

// GetBucketEndpoint returns the BucketEndpoint field value if set, zero value otherwise.
func (o *S3ArchiveRoute) GetBucketEndpoint() string {
	if o == nil || IsNil(o.BucketEndpoint) {
		var ret string
		return ret
	}
	return *o.BucketEndpoint
}

// GetBucketEndpointOk returns a tuple with the BucketEndpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3ArchiveRoute) GetBucketEndpointOk() (*string, bool) {
	if o == nil || IsNil(o.BucketEndpoint) {
		return nil, false
	}
	return o.BucketEndpoint, true
}

// HasBucketEndpoint returns a boolean if a field has been set.
func (o *S3ArchiveRoute) HasBucketEndpoint() bool {
	if o != nil && !IsNil(o.BucketEndpoint) {
		return true
	}

	return false
}

// SetBucketEndpoint gets a reference to the given string and assigns it to the BucketEndpoint field.
func (o *S3ArchiveRoute) SetBucketEndpoint(v string) {
	o.BucketEndpoint = &v
}

// GetBucketName returns the BucketName field value if set, zero value otherwise.
func (o *S3ArchiveRoute) GetBucketName() string {
	if o == nil || IsNil(o.BucketName) {
		var ret string
		return ret
	}
	return *o.BucketName
}

// GetBucketNameOk returns a tuple with the BucketName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3ArchiveRoute) GetBucketNameOk() (*string, bool) {
	if o == nil || IsNil(o.BucketName) {
		return nil, false
	}
	return o.BucketName, true
}

// HasBucketName returns a boolean if a field has been set.
func (o *S3ArchiveRoute) HasBucketName() bool {
	if o != nil && !IsNil(o.BucketName) {
		return true
	}

	return false
}

// SetBucketName gets a reference to the given string and assigns it to the BucketName field.
func (o *S3ArchiveRoute) SetBucketName(v string) {
	o.BucketName = &v
}

// GetBucketRegion returns the BucketRegion field value if set, zero value otherwise.
func (o *S3ArchiveRoute) GetBucketRegion() string {
	if o == nil || IsNil(o.BucketRegion) {
		var ret string
		return ret
	}
	return *o.BucketRegion
}

// GetBucketRegionOk returns a tuple with the BucketRegion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3ArchiveRoute) GetBucketRegionOk() (*string, bool) {
	if o == nil || IsNil(o.BucketRegion) {
		return nil, false
	}
	return o.BucketRegion, true
}

// HasBucketRegion returns a boolean if a field has been set.
func (o *S3ArchiveRoute) HasBucketRegion() bool {
	if o != nil && !IsNil(o.BucketRegion) {
		return true
	}

	return false
}

// SetBucketRegion gets a reference to the given string and assigns it to the BucketRegion field.
func (o *S3ArchiveRoute) SetBucketRegion(v string) {
	o.BucketRegion = &v
}

// GetFileAccess returns the FileAccess field value if set, zero value otherwise.
func (o *S3ArchiveRoute) GetFileAccess() string {
	if o == nil || IsNil(o.FileAccess) {
		var ret string
		return ret
	}
	return *o.FileAccess
}

// GetFileAccessOk returns a tuple with the FileAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3ArchiveRoute) GetFileAccessOk() (*string, bool) {
	if o == nil || IsNil(o.FileAccess) {
		return nil, false
	}
	return o.FileAccess, true
}

// HasFileAccess returns a boolean if a field has been set.
func (o *S3ArchiveRoute) HasFileAccess() bool {
	if o != nil && !IsNil(o.FileAccess) {
		return true
	}

	return false
}

// SetFileAccess gets a reference to the given string and assigns it to the FileAccess field.
func (o *S3ArchiveRoute) SetFileAccess(v string) {
	o.FileAccess = &v
}

// GetFileFolder returns the FileFolder field value if set, zero value otherwise.
func (o *S3ArchiveRoute) GetFileFolder() string {
	if o == nil || IsNil(o.FileFolder) {
		var ret string
		return ret
	}
	return *o.FileFolder
}

// GetFileFolderOk returns a tuple with the FileFolder field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3ArchiveRoute) GetFileFolderOk() (*string, bool) {
	if o == nil || IsNil(o.FileFolder) {
		return nil, false
	}
	return o.FileFolder, true
}

// HasFileFolder returns a boolean if a field has been set.
func (o *S3ArchiveRoute) HasFileFolder() bool {
	if o != nil && !IsNil(o.FileFolder) {
		return true
	}

	return false
}

// SetFileFolder gets a reference to the given string and assigns it to the FileFolder field.
func (o *S3ArchiveRoute) SetFileFolder(v string) {
	o.FileFolder = &v
}

// GetFileFormat returns the FileFormat field value if set, zero value otherwise.
func (o *S3ArchiveRoute) GetFileFormat() string {
	if o == nil || IsNil(o.FileFormat) {
		var ret string
		return ret
	}
	return *o.FileFormat
}

// GetFileFormatOk returns a tuple with the FileFormat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3ArchiveRoute) GetFileFormatOk() (*string, bool) {
	if o == nil || IsNil(o.FileFormat) {
		return nil, false
	}
	return o.FileFormat, true
}

// HasFileFormat returns a boolean if a field has been set.
func (o *S3ArchiveRoute) HasFileFormat() bool {
	if o != nil && !IsNil(o.FileFormat) {
		return true
	}

	return false
}

// SetFileFormat gets a reference to the given string and assigns it to the FileFormat field.
func (o *S3ArchiveRoute) SetFileFormat(v string) {
	o.FileFormat = &v
}

// GetFilter returns the Filter field value if set, zero value otherwise.
func (o *S3ArchiveRoute) GetFilter() Filter {
	if o == nil || IsNil(o.Filter) {
		var ret Filter
		return ret
	}
	return *o.Filter
}

// GetFilterOk returns a tuple with the Filter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3ArchiveRoute) GetFilterOk() (*Filter, bool) {
	if o == nil || IsNil(o.Filter) {
		return nil, false
	}
	return o.Filter, true
}

// HasFilter returns a boolean if a field has been set.
func (o *S3ArchiveRoute) HasFilter() bool {
	if o != nil && !IsNil(o.Filter) {
		return true
	}

	return false
}

// SetFilter gets a reference to the given Filter and assigns it to the Filter field.
func (o *S3ArchiveRoute) SetFilter(v Filter) {
	o.Filter = &v
}

// GetFleets returns the Fleets field value if set, zero value otherwise.
func (o *S3ArchiveRoute) GetFleets() []string {
	if o == nil || IsNil(o.Fleets) {
		var ret []string
		return ret
	}
	return o.Fleets
}

// GetFleetsOk returns a tuple with the Fleets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3ArchiveRoute) GetFleetsOk() ([]string, bool) {
	if o == nil || IsNil(o.Fleets) {
		return nil, false
	}
	return o.Fleets, true
}

// HasFleets returns a boolean if a field has been set.
func (o *S3ArchiveRoute) HasFleets() bool {
	if o != nil && !IsNil(o.Fleets) {
		return true
	}

	return false
}

// SetFleets gets a reference to the given []string and assigns it to the Fleets field.
func (o *S3ArchiveRoute) SetFleets(v []string) {
	o.Fleets = v
}

// GetKeyId returns the KeyId field value if set, zero value otherwise.
func (o *S3ArchiveRoute) GetKeyId() string {
	if o == nil || IsNil(o.KeyId) {
		var ret string
		return ret
	}
	return *o.KeyId
}

// GetKeyIdOk returns a tuple with the KeyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3ArchiveRoute) GetKeyIdOk() (*string, bool) {
	if o == nil || IsNil(o.KeyId) {
		return nil, false
	}
	return o.KeyId, true
}

// HasKeyId returns a boolean if a field has been set.
func (o *S3ArchiveRoute) HasKeyId() bool {
	if o != nil && !IsNil(o.KeyId) {
		return true
	}

	return false
}

// SetKeyId gets a reference to the given string and assigns it to the KeyId field.
func (o *S3ArchiveRoute) SetKeyId(v string) {
	o.KeyId = &v
}

// GetKeySecret returns the KeySecret field value if set, zero value otherwise.
func (o *S3ArchiveRoute) GetKeySecret() string {
	if o == nil || IsNil(o.KeySecret) {
		var ret string
		return ret
	}
	return *o.KeySecret
}

// GetKeySecretOk returns a tuple with the KeySecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3ArchiveRoute) GetKeySecretOk() (*string, bool) {
	if o == nil || IsNil(o.KeySecret) {
		return nil, false
	}
	return o.KeySecret, true
}

// HasKeySecret returns a boolean if a field has been set.
func (o *S3ArchiveRoute) HasKeySecret() bool {
	if o != nil && !IsNil(o.KeySecret) {
		return true
	}

	return false
}

// SetKeySecret gets a reference to the given string and assigns it to the KeySecret field.
func (o *S3ArchiveRoute) SetKeySecret(v string) {
	o.KeySecret = &v
}

// GetThrottleMs returns the ThrottleMs field value if set, zero value otherwise.
func (o *S3ArchiveRoute) GetThrottleMs() int32 {
	if o == nil || IsNil(o.ThrottleMs) {
		var ret int32
		return ret
	}
	return *o.ThrottleMs
}

// GetThrottleMsOk returns a tuple with the ThrottleMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3ArchiveRoute) GetThrottleMsOk() (*int32, bool) {
	if o == nil || IsNil(o.ThrottleMs) {
		return nil, false
	}
	return o.ThrottleMs, true
}

// HasThrottleMs returns a boolean if a field has been set.
func (o *S3ArchiveRoute) HasThrottleMs() bool {
	if o != nil && !IsNil(o.ThrottleMs) {
		return true
	}

	return false
}

// SetThrottleMs gets a reference to the given int32 and assigns it to the ThrottleMs field.
func (o *S3ArchiveRoute) SetThrottleMs(v int32) {
	o.ThrottleMs = &v
}

// GetTimeout returns the Timeout field value if set, zero value otherwise.
func (o *S3ArchiveRoute) GetTimeout() int32 {
	if o == nil || IsNil(o.Timeout) {
		var ret int32
		return ret
	}
	return *o.Timeout
}

// GetTimeoutOk returns a tuple with the Timeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3ArchiveRoute) GetTimeoutOk() (*int32, bool) {
	if o == nil || IsNil(o.Timeout) {
		return nil, false
	}
	return o.Timeout, true
}

// HasTimeout returns a boolean if a field has been set.
func (o *S3ArchiveRoute) HasTimeout() bool {
	if o != nil && !IsNil(o.Timeout) {
		return true
	}

	return false
}

// SetTimeout gets a reference to the given int32 and assigns it to the Timeout field.
func (o *S3ArchiveRoute) SetTimeout(v int32) {
	o.Timeout = &v
}

// GetTransform returns the Transform field value if set, zero value otherwise.
func (o *S3ArchiveRoute) GetTransform() RouteTransformSettings {
	if o == nil || IsNil(o.Transform) {
		var ret RouteTransformSettings
		return ret
	}
	return *o.Transform
}

// GetTransformOk returns a tuple with the Transform field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3ArchiveRoute) GetTransformOk() (*RouteTransformSettings, bool) {
	if o == nil || IsNil(o.Transform) {
		return nil, false
	}
	return o.Transform, true
}

// HasTransform returns a boolean if a field has been set.
func (o *S3ArchiveRoute) HasTransform() bool {
	if o != nil && !IsNil(o.Transform) {
		return true
	}

	return false
}

// SetTransform gets a reference to the given RouteTransformSettings and assigns it to the Transform field.
func (o *S3ArchiveRoute) SetTransform(v RouteTransformSettings) {
	o.Transform = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *S3ArchiveRoute) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3ArchiveRoute) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *S3ArchiveRoute) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *S3ArchiveRoute) SetUrl(v string) {
	o.Url = &v
}

func (o S3ArchiveRoute) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o S3ArchiveRoute) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ArchiveCountExceeds) {
		toSerialize["archive_count_exceeds"] = o.ArchiveCountExceeds
	}
	if !IsNil(o.ArchiveEveryMins) {
		toSerialize["archive_every_mins"] = o.ArchiveEveryMins
	}
	if !IsNil(o.ArchiveId) {
		toSerialize["archive_id"] = o.ArchiveId
	}
	if !IsNil(o.BucketEndpoint) {
		toSerialize["bucket_endpoint"] = o.BucketEndpoint
	}
	if !IsNil(o.BucketName) {
		toSerialize["bucket_name"] = o.BucketName
	}
	if !IsNil(o.BucketRegion) {
		toSerialize["bucket_region"] = o.BucketRegion
	}
	if !IsNil(o.FileAccess) {
		toSerialize["file_access"] = o.FileAccess
	}
	if !IsNil(o.FileFolder) {
		toSerialize["file_folder"] = o.FileFolder
	}
	if !IsNil(o.FileFormat) {
		toSerialize["file_format"] = o.FileFormat
	}
	if !IsNil(o.Filter) {
		toSerialize["filter"] = o.Filter
	}
	if !IsNil(o.Fleets) {
		toSerialize["fleets"] = o.Fleets
	}
	if !IsNil(o.KeyId) {
		toSerialize["key_id"] = o.KeyId
	}
	if !IsNil(o.KeySecret) {
		toSerialize["key_secret"] = o.KeySecret
	}
	if !IsNil(o.ThrottleMs) {
		toSerialize["throttle_ms"] = o.ThrottleMs
	}
	if !IsNil(o.Timeout) {
		toSerialize["timeout"] = o.Timeout
	}
	if !IsNil(o.Transform) {
		toSerialize["transform"] = o.Transform
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableS3ArchiveRoute struct {
	value *S3ArchiveRoute
	isSet bool
}

func (v NullableS3ArchiveRoute) Get() *S3ArchiveRoute {
	return v.value
}

func (v *NullableS3ArchiveRoute) Set(val *S3ArchiveRoute) {
	v.value = val
	v.isSet = true
}

func (v NullableS3ArchiveRoute) IsSet() bool {
	return v.isSet
}

func (v *NullableS3ArchiveRoute) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableS3ArchiveRoute(val *S3ArchiveRoute) *NullableS3ArchiveRoute {
	return &NullableS3ArchiveRoute{value: val, isSet: true}
}

func (v NullableS3ArchiveRoute) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableS3ArchiveRoute) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
