/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"encoding/json"
	"time"
)

// checks if the NotehubRouteSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NotehubRouteSummary{}

// NotehubRouteSummary struct for NotehubRouteSummary
type NotehubRouteSummary struct {
	Disabled *bool      `json:"disabled,omitempty"`
	Label    *string    `json:"label,omitempty"`
	Modified *time.Time `json:"modified,omitempty"`
	Type     *string    `json:"type,omitempty"`
	Uid      *string    `json:"uid,omitempty"`
}

// NewNotehubRouteSummary instantiates a new NotehubRouteSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotehubRouteSummary() *NotehubRouteSummary {
	this := NotehubRouteSummary{}
	var disabled bool = false
	this.Disabled = &disabled
	var label string = "success route"
	this.Label = &label
	var type_ string = "http"
	this.Type = &type_
	var uid string = "route:8d65a087d5d290ce5bdf03aeff2becc0"
	this.Uid = &uid
	return &this
}

// NewNotehubRouteSummaryWithDefaults instantiates a new NotehubRouteSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotehubRouteSummaryWithDefaults() *NotehubRouteSummary {
	this := NotehubRouteSummary{}
	var disabled bool = false
	this.Disabled = &disabled
	var label string = "success route"
	this.Label = &label
	var type_ string = "http"
	this.Type = &type_
	var uid string = "route:8d65a087d5d290ce5bdf03aeff2becc0"
	this.Uid = &uid
	return &this
}

// GetDisabled returns the Disabled field value if set, zero value otherwise.
func (o *NotehubRouteSummary) GetDisabled() bool {
	if o == nil || IsNil(o.Disabled) {
		var ret bool
		return ret
	}
	return *o.Disabled
}

// GetDisabledOk returns a tuple with the Disabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotehubRouteSummary) GetDisabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Disabled) {
		return nil, false
	}
	return o.Disabled, true
}

// HasDisabled returns a boolean if a field has been set.
func (o *NotehubRouteSummary) HasDisabled() bool {
	if o != nil && !IsNil(o.Disabled) {
		return true
	}

	return false
}

// SetDisabled gets a reference to the given bool and assigns it to the Disabled field.
func (o *NotehubRouteSummary) SetDisabled(v bool) {
	o.Disabled = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *NotehubRouteSummary) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotehubRouteSummary) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *NotehubRouteSummary) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *NotehubRouteSummary) SetLabel(v string) {
	o.Label = &v
}

// GetModified returns the Modified field value if set, zero value otherwise.
func (o *NotehubRouteSummary) GetModified() time.Time {
	if o == nil || IsNil(o.Modified) {
		var ret time.Time
		return ret
	}
	return *o.Modified
}

// GetModifiedOk returns a tuple with the Modified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotehubRouteSummary) GetModifiedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Modified) {
		return nil, false
	}
	return o.Modified, true
}

// HasModified returns a boolean if a field has been set.
func (o *NotehubRouteSummary) HasModified() bool {
	if o != nil && !IsNil(o.Modified) {
		return true
	}

	return false
}

// SetModified gets a reference to the given time.Time and assigns it to the Modified field.
func (o *NotehubRouteSummary) SetModified(v time.Time) {
	o.Modified = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *NotehubRouteSummary) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotehubRouteSummary) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *NotehubRouteSummary) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *NotehubRouteSummary) SetType(v string) {
	o.Type = &v
}

// GetUid returns the Uid field value if set, zero value otherwise.
func (o *NotehubRouteSummary) GetUid() string {
	if o == nil || IsNil(o.Uid) {
		var ret string
		return ret
	}
	return *o.Uid
}

// GetUidOk returns a tuple with the Uid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotehubRouteSummary) GetUidOk() (*string, bool) {
	if o == nil || IsNil(o.Uid) {
		return nil, false
	}
	return o.Uid, true
}

// HasUid returns a boolean if a field has been set.
func (o *NotehubRouteSummary) HasUid() bool {
	if o != nil && !IsNil(o.Uid) {
		return true
	}

	return false
}

// SetUid gets a reference to the given string and assigns it to the Uid field.
func (o *NotehubRouteSummary) SetUid(v string) {
	o.Uid = &v
}

func (o NotehubRouteSummary) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NotehubRouteSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Disabled) {
		toSerialize["disabled"] = o.Disabled
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.Modified) {
		toSerialize["modified"] = o.Modified
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Uid) {
		toSerialize["uid"] = o.Uid
	}
	return toSerialize, nil
}

type NullableNotehubRouteSummary struct {
	value *NotehubRouteSummary
	isSet bool
}

func (v NullableNotehubRouteSummary) Get() *NotehubRouteSummary {
	return v.value
}

func (v *NullableNotehubRouteSummary) Set(val *NotehubRouteSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableNotehubRouteSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableNotehubRouteSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotehubRouteSummary(val *NotehubRouteSummary) *NullableNotehubRouteSummary {
	return &NullableNotehubRouteSummary{value: val, isSet: true}
}

func (v NullableNotehubRouteSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotehubRouteSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
