/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the RepositoryTokenResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RepositoryTokenResponse{}

// RepositoryTokenResponse struct for RepositoryTokenResponse
type RepositoryTokenResponse struct {
	// Storage service database name scoped to this repository
	Database string `json:"database"`
	// Absolute expiration time of the ephemeral user. The storage service will reject connections and queries after this instant.
	ExpiresAt time.Time `json:"expires_at"`
	// Storage service hostname the caller should connect to
	Host string `json:"host"`
	// Ephemeral password. Returned once; not stored by Notehub. Hold this in memory only and discard after `expires_at`.
	Password string `json:"password"`
	// Storage service port
	Port int32 `json:"port"`
	// Ephemeral storage service username (prefixed with `u_`)
	Username             string `json:"username"`
	AdditionalProperties map[string]interface{}
}

type _RepositoryTokenResponse RepositoryTokenResponse

// NewRepositoryTokenResponse instantiates a new RepositoryTokenResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRepositoryTokenResponse(database string, expiresAt time.Time, host string, password string, port int32, username string) *RepositoryTokenResponse {
	this := RepositoryTokenResponse{}
	this.Database = database
	this.ExpiresAt = expiresAt
	this.Host = host
	this.Password = password
	this.Port = port
	this.Username = username
	return &this
}

// NewRepositoryTokenResponseWithDefaults instantiates a new RepositoryTokenResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRepositoryTokenResponseWithDefaults() *RepositoryTokenResponse {
	this := RepositoryTokenResponse{}
	return &this
}

// GetDatabase returns the Database field value
func (o *RepositoryTokenResponse) GetDatabase() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Database
}

// GetDatabaseOk returns a tuple with the Database field value
// and a boolean to check if the value has been set.
func (o *RepositoryTokenResponse) GetDatabaseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Database, true
}

// SetDatabase sets field value
func (o *RepositoryTokenResponse) SetDatabase(v string) {
	o.Database = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *RepositoryTokenResponse) GetExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *RepositoryTokenResponse) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *RepositoryTokenResponse) SetExpiresAt(v time.Time) {
	o.ExpiresAt = v
}

// GetHost returns the Host field value
func (o *RepositoryTokenResponse) GetHost() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Host
}

// GetHostOk returns a tuple with the Host field value
// and a boolean to check if the value has been set.
func (o *RepositoryTokenResponse) GetHostOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Host, true
}

// SetHost sets field value
func (o *RepositoryTokenResponse) SetHost(v string) {
	o.Host = v
}

// GetPassword returns the Password field value
func (o *RepositoryTokenResponse) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *RepositoryTokenResponse) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *RepositoryTokenResponse) SetPassword(v string) {
	o.Password = v
}

// GetPort returns the Port field value
func (o *RepositoryTokenResponse) GetPort() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Port
}

// GetPortOk returns a tuple with the Port field value
// and a boolean to check if the value has been set.
func (o *RepositoryTokenResponse) GetPortOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Port, true
}

// SetPort sets field value
func (o *RepositoryTokenResponse) SetPort(v int32) {
	o.Port = v
}

// GetUsername returns the Username field value
func (o *RepositoryTokenResponse) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *RepositoryTokenResponse) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *RepositoryTokenResponse) SetUsername(v string) {
	o.Username = v
}

func (o RepositoryTokenResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RepositoryTokenResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["database"] = o.Database
	toSerialize["expires_at"] = o.ExpiresAt
	toSerialize["host"] = o.Host
	toSerialize["password"] = o.Password
	toSerialize["port"] = o.Port
	toSerialize["username"] = o.Username

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RepositoryTokenResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"database",
		"expires_at",
		"host",
		"password",
		"port",
		"username",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRepositoryTokenResponse := _RepositoryTokenResponse{}

	err = json.Unmarshal(data, &varRepositoryTokenResponse)

	if err != nil {
		return err
	}

	*o = RepositoryTokenResponse(varRepositoryTokenResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "database")
		delete(additionalProperties, "expires_at")
		delete(additionalProperties, "host")
		delete(additionalProperties, "password")
		delete(additionalProperties, "port")
		delete(additionalProperties, "username")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRepositoryTokenResponse struct {
	value *RepositoryTokenResponse
	isSet bool
}

func (v NullableRepositoryTokenResponse) Get() *RepositoryTokenResponse {
	return v.value
}

func (v *NullableRepositoryTokenResponse) Set(val *RepositoryTokenResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRepositoryTokenResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRepositoryTokenResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRepositoryTokenResponse(val *RepositoryTokenResponse) *NullableRepositoryTokenResponse {
	return &NullableRepositoryTokenResponse{value: val, isSet: true}
}

func (v NullableRepositoryTokenResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRepositoryTokenResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
