/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"encoding/json"
)

// checks if the Monitor type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Monitor{}

// Monitor struct for Monitor
type Monitor struct {
	// Aggregate function to apply to the selected values before applying the condition. [none, sum, average, max, min]
	AggregateFunction *string `json:"aggregate_function,omitempty"`
	// The time window to aggregate the selected values. It follows the format of a number followed by a time unit
	AggregateWindow *string `json:"aggregate_window,omitempty" validate:"regexp=^[0-9]+[smh]$"`
	// If true, the monitor is in alert state.
	Alert       *bool                     `json:"alert,omitempty"`
	AlertRoutes []MonitorAlertRoutesInner `json:"alert_routes,omitempty"`
	// A comparison operation to apply to the value selected by the source_selector [greater_than, greater_than_or_equal_to, less_than, less_than_or_equal_to, equal_to, not_equal_to]
	ConditionType *string `json:"condition_type,omitempty"`
	Description   *string `json:"description,omitempty"`
	// If true, the monitor will not be evaluated.
	Disabled    *bool    `json:"disabled,omitempty"`
	FleetFilter []string `json:"fleet_filter,omitempty"`
	// The last time the monitor was evaluated and routed.
	LastRoutedAt   *string  `json:"last_routed_at,omitempty"`
	Name           *string  `json:"name,omitempty"`
	NotefileFilter []string `json:"notefile_filter,omitempty"`
	// Only relevant when using an aggregate_function. If true, the monitor will be evaluated per device, | rather than across the set of selected devices. If true then if a single device matches the specified criteria, | and alert will be created, otherwise the aggregate function will be applied across all devices.
	PerDevice *bool `json:"per_device,omitempty"`
	// The time period to wait before routing another event after the monitor | has been triggered. It follows the format of a number followed by a time unit.
	RoutingCooldownPeriod *string `json:"routing_cooldown_period,omitempty" validate:"regexp=^[0-9]+[smh]$"`
	// If true, alerts will be created, but no notifications will be sent.
	Silenced *bool `json:"silenced,omitempty"`
	// A valid JSONata expression that selects the value to monitor from the source. | It should return a single, numeric value.
	SourceSelector *string `json:"source_selector,omitempty"`
	// The type of source to monitor. Supported values are \"event\" and \"heartbeat\".
	SourceType *string `json:"source_type,omitempty"`
	// The type of condition to apply to the value selected by the source_selector
	Threshold *int32  `json:"threshold,omitempty"`
	Uid       *string `json:"uid,omitempty"`
}

// NewMonitor instantiates a new Monitor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMonitor() *Monitor {
	this := Monitor{}
	return &this
}

// NewMonitorWithDefaults instantiates a new Monitor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMonitorWithDefaults() *Monitor {
	this := Monitor{}
	return &this
}

// GetAggregateFunction returns the AggregateFunction field value if set, zero value otherwise.
func (o *Monitor) GetAggregateFunction() string {
	if o == nil || IsNil(o.AggregateFunction) {
		var ret string
		return ret
	}
	return *o.AggregateFunction
}

// GetAggregateFunctionOk returns a tuple with the AggregateFunction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Monitor) GetAggregateFunctionOk() (*string, bool) {
	if o == nil || IsNil(o.AggregateFunction) {
		return nil, false
	}
	return o.AggregateFunction, true
}

// HasAggregateFunction returns a boolean if a field has been set.
func (o *Monitor) HasAggregateFunction() bool {
	if o != nil && !IsNil(o.AggregateFunction) {
		return true
	}

	return false
}

// SetAggregateFunction gets a reference to the given string and assigns it to the AggregateFunction field.
func (o *Monitor) SetAggregateFunction(v string) {
	o.AggregateFunction = &v
}

// GetAggregateWindow returns the AggregateWindow field value if set, zero value otherwise.
func (o *Monitor) GetAggregateWindow() string {
	if o == nil || IsNil(o.AggregateWindow) {
		var ret string
		return ret
	}
	return *o.AggregateWindow
}

// GetAggregateWindowOk returns a tuple with the AggregateWindow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Monitor) GetAggregateWindowOk() (*string, bool) {
	if o == nil || IsNil(o.AggregateWindow) {
		return nil, false
	}
	return o.AggregateWindow, true
}

// HasAggregateWindow returns a boolean if a field has been set.
func (o *Monitor) HasAggregateWindow() bool {
	if o != nil && !IsNil(o.AggregateWindow) {
		return true
	}

	return false
}

// SetAggregateWindow gets a reference to the given string and assigns it to the AggregateWindow field.
func (o *Monitor) SetAggregateWindow(v string) {
	o.AggregateWindow = &v
}

// GetAlert returns the Alert field value if set, zero value otherwise.
func (o *Monitor) GetAlert() bool {
	if o == nil || IsNil(o.Alert) {
		var ret bool
		return ret
	}
	return *o.Alert
}

// GetAlertOk returns a tuple with the Alert field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Monitor) GetAlertOk() (*bool, bool) {
	if o == nil || IsNil(o.Alert) {
		return nil, false
	}
	return o.Alert, true
}

// HasAlert returns a boolean if a field has been set.
func (o *Monitor) HasAlert() bool {
	if o != nil && !IsNil(o.Alert) {
		return true
	}

	return false
}

// SetAlert gets a reference to the given bool and assigns it to the Alert field.
func (o *Monitor) SetAlert(v bool) {
	o.Alert = &v
}

// GetAlertRoutes returns the AlertRoutes field value if set, zero value otherwise.
func (o *Monitor) GetAlertRoutes() []MonitorAlertRoutesInner {
	if o == nil || IsNil(o.AlertRoutes) {
		var ret []MonitorAlertRoutesInner
		return ret
	}
	return o.AlertRoutes
}

// GetAlertRoutesOk returns a tuple with the AlertRoutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Monitor) GetAlertRoutesOk() ([]MonitorAlertRoutesInner, bool) {
	if o == nil || IsNil(o.AlertRoutes) {
		return nil, false
	}
	return o.AlertRoutes, true
}

// HasAlertRoutes returns a boolean if a field has been set.
func (o *Monitor) HasAlertRoutes() bool {
	if o != nil && !IsNil(o.AlertRoutes) {
		return true
	}

	return false
}

// SetAlertRoutes gets a reference to the given []MonitorAlertRoutesInner and assigns it to the AlertRoutes field.
func (o *Monitor) SetAlertRoutes(v []MonitorAlertRoutesInner) {
	o.AlertRoutes = v
}

// GetConditionType returns the ConditionType field value if set, zero value otherwise.
func (o *Monitor) GetConditionType() string {
	if o == nil || IsNil(o.ConditionType) {
		var ret string
		return ret
	}
	return *o.ConditionType
}

// GetConditionTypeOk returns a tuple with the ConditionType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Monitor) GetConditionTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ConditionType) {
		return nil, false
	}
	return o.ConditionType, true
}

// HasConditionType returns a boolean if a field has been set.
func (o *Monitor) HasConditionType() bool {
	if o != nil && !IsNil(o.ConditionType) {
		return true
	}

	return false
}

// SetConditionType gets a reference to the given string and assigns it to the ConditionType field.
func (o *Monitor) SetConditionType(v string) {
	o.ConditionType = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Monitor) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Monitor) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Monitor) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Monitor) SetDescription(v string) {
	o.Description = &v
}

// GetDisabled returns the Disabled field value if set, zero value otherwise.
func (o *Monitor) GetDisabled() bool {
	if o == nil || IsNil(o.Disabled) {
		var ret bool
		return ret
	}
	return *o.Disabled
}

// GetDisabledOk returns a tuple with the Disabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Monitor) GetDisabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Disabled) {
		return nil, false
	}
	return o.Disabled, true
}

// HasDisabled returns a boolean if a field has been set.
func (o *Monitor) HasDisabled() bool {
	if o != nil && !IsNil(o.Disabled) {
		return true
	}

	return false
}

// SetDisabled gets a reference to the given bool and assigns it to the Disabled field.
func (o *Monitor) SetDisabled(v bool) {
	o.Disabled = &v
}

// GetFleetFilter returns the FleetFilter field value if set, zero value otherwise.
func (o *Monitor) GetFleetFilter() []string {
	if o == nil || IsNil(o.FleetFilter) {
		var ret []string
		return ret
	}
	return o.FleetFilter
}

// GetFleetFilterOk returns a tuple with the FleetFilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Monitor) GetFleetFilterOk() ([]string, bool) {
	if o == nil || IsNil(o.FleetFilter) {
		return nil, false
	}
	return o.FleetFilter, true
}

// HasFleetFilter returns a boolean if a field has been set.
func (o *Monitor) HasFleetFilter() bool {
	if o != nil && !IsNil(o.FleetFilter) {
		return true
	}

	return false
}

// SetFleetFilter gets a reference to the given []string and assigns it to the FleetFilter field.
func (o *Monitor) SetFleetFilter(v []string) {
	o.FleetFilter = v
}

// GetLastRoutedAt returns the LastRoutedAt field value if set, zero value otherwise.
func (o *Monitor) GetLastRoutedAt() string {
	if o == nil || IsNil(o.LastRoutedAt) {
		var ret string
		return ret
	}
	return *o.LastRoutedAt
}

// GetLastRoutedAtOk returns a tuple with the LastRoutedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Monitor) GetLastRoutedAtOk() (*string, bool) {
	if o == nil || IsNil(o.LastRoutedAt) {
		return nil, false
	}
	return o.LastRoutedAt, true
}

// HasLastRoutedAt returns a boolean if a field has been set.
func (o *Monitor) HasLastRoutedAt() bool {
	if o != nil && !IsNil(o.LastRoutedAt) {
		return true
	}

	return false
}

// SetLastRoutedAt gets a reference to the given string and assigns it to the LastRoutedAt field.
func (o *Monitor) SetLastRoutedAt(v string) {
	o.LastRoutedAt = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Monitor) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Monitor) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Monitor) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Monitor) SetName(v string) {
	o.Name = &v
}

// GetNotefileFilter returns the NotefileFilter field value if set, zero value otherwise.
func (o *Monitor) GetNotefileFilter() []string {
	if o == nil || IsNil(o.NotefileFilter) {
		var ret []string
		return ret
	}
	return o.NotefileFilter
}

// GetNotefileFilterOk returns a tuple with the NotefileFilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Monitor) GetNotefileFilterOk() ([]string, bool) {
	if o == nil || IsNil(o.NotefileFilter) {
		return nil, false
	}
	return o.NotefileFilter, true
}

// HasNotefileFilter returns a boolean if a field has been set.
func (o *Monitor) HasNotefileFilter() bool {
	if o != nil && !IsNil(o.NotefileFilter) {
		return true
	}

	return false
}

// SetNotefileFilter gets a reference to the given []string and assigns it to the NotefileFilter field.
func (o *Monitor) SetNotefileFilter(v []string) {
	o.NotefileFilter = v
}

// GetPerDevice returns the PerDevice field value if set, zero value otherwise.
func (o *Monitor) GetPerDevice() bool {
	if o == nil || IsNil(o.PerDevice) {
		var ret bool
		return ret
	}
	return *o.PerDevice
}

// GetPerDeviceOk returns a tuple with the PerDevice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Monitor) GetPerDeviceOk() (*bool, bool) {
	if o == nil || IsNil(o.PerDevice) {
		return nil, false
	}
	return o.PerDevice, true
}

// HasPerDevice returns a boolean if a field has been set.
func (o *Monitor) HasPerDevice() bool {
	if o != nil && !IsNil(o.PerDevice) {
		return true
	}

	return false
}

// SetPerDevice gets a reference to the given bool and assigns it to the PerDevice field.
func (o *Monitor) SetPerDevice(v bool) {
	o.PerDevice = &v
}

// GetRoutingCooldownPeriod returns the RoutingCooldownPeriod field value if set, zero value otherwise.
func (o *Monitor) GetRoutingCooldownPeriod() string {
	if o == nil || IsNil(o.RoutingCooldownPeriod) {
		var ret string
		return ret
	}
	return *o.RoutingCooldownPeriod
}

// GetRoutingCooldownPeriodOk returns a tuple with the RoutingCooldownPeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Monitor) GetRoutingCooldownPeriodOk() (*string, bool) {
	if o == nil || IsNil(o.RoutingCooldownPeriod) {
		return nil, false
	}
	return o.RoutingCooldownPeriod, true
}

// HasRoutingCooldownPeriod returns a boolean if a field has been set.
func (o *Monitor) HasRoutingCooldownPeriod() bool {
	if o != nil && !IsNil(o.RoutingCooldownPeriod) {
		return true
	}

	return false
}

// SetRoutingCooldownPeriod gets a reference to the given string and assigns it to the RoutingCooldownPeriod field.
func (o *Monitor) SetRoutingCooldownPeriod(v string) {
	o.RoutingCooldownPeriod = &v
}

// GetSilenced returns the Silenced field value if set, zero value otherwise.
func (o *Monitor) GetSilenced() bool {
	if o == nil || IsNil(o.Silenced) {
		var ret bool
		return ret
	}
	return *o.Silenced
}

// GetSilencedOk returns a tuple with the Silenced field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Monitor) GetSilencedOk() (*bool, bool) {
	if o == nil || IsNil(o.Silenced) {
		return nil, false
	}
	return o.Silenced, true
}

// HasSilenced returns a boolean if a field has been set.
func (o *Monitor) HasSilenced() bool {
	if o != nil && !IsNil(o.Silenced) {
		return true
	}

	return false
}

// SetSilenced gets a reference to the given bool and assigns it to the Silenced field.
func (o *Monitor) SetSilenced(v bool) {
	o.Silenced = &v
}

// GetSourceSelector returns the SourceSelector field value if set, zero value otherwise.
func (o *Monitor) GetSourceSelector() string {
	if o == nil || IsNil(o.SourceSelector) {
		var ret string
		return ret
	}
	return *o.SourceSelector
}

// GetSourceSelectorOk returns a tuple with the SourceSelector field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Monitor) GetSourceSelectorOk() (*string, bool) {
	if o == nil || IsNil(o.SourceSelector) {
		return nil, false
	}
	return o.SourceSelector, true
}

// HasSourceSelector returns a boolean if a field has been set.
func (o *Monitor) HasSourceSelector() bool {
	if o != nil && !IsNil(o.SourceSelector) {
		return true
	}

	return false
}

// SetSourceSelector gets a reference to the given string and assigns it to the SourceSelector field.
func (o *Monitor) SetSourceSelector(v string) {
	o.SourceSelector = &v
}

// GetSourceType returns the SourceType field value if set, zero value otherwise.
func (o *Monitor) GetSourceType() string {
	if o == nil || IsNil(o.SourceType) {
		var ret string
		return ret
	}
	return *o.SourceType
}

// GetSourceTypeOk returns a tuple with the SourceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Monitor) GetSourceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.SourceType) {
		return nil, false
	}
	return o.SourceType, true
}

// HasSourceType returns a boolean if a field has been set.
func (o *Monitor) HasSourceType() bool {
	if o != nil && !IsNil(o.SourceType) {
		return true
	}

	return false
}

// SetSourceType gets a reference to the given string and assigns it to the SourceType field.
func (o *Monitor) SetSourceType(v string) {
	o.SourceType = &v
}

// GetThreshold returns the Threshold field value if set, zero value otherwise.
func (o *Monitor) GetThreshold() int32 {
	if o == nil || IsNil(o.Threshold) {
		var ret int32
		return ret
	}
	return *o.Threshold
}

// GetThresholdOk returns a tuple with the Threshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Monitor) GetThresholdOk() (*int32, bool) {
	if o == nil || IsNil(o.Threshold) {
		return nil, false
	}
	return o.Threshold, true
}

// HasThreshold returns a boolean if a field has been set.
func (o *Monitor) HasThreshold() bool {
	if o != nil && !IsNil(o.Threshold) {
		return true
	}

	return false
}

// SetThreshold gets a reference to the given int32 and assigns it to the Threshold field.
func (o *Monitor) SetThreshold(v int32) {
	o.Threshold = &v
}

// GetUid returns the Uid field value if set, zero value otherwise.
func (o *Monitor) GetUid() string {
	if o == nil || IsNil(o.Uid) {
		var ret string
		return ret
	}
	return *o.Uid
}

// GetUidOk returns a tuple with the Uid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Monitor) GetUidOk() (*string, bool) {
	if o == nil || IsNil(o.Uid) {
		return nil, false
	}
	return o.Uid, true
}

// HasUid returns a boolean if a field has been set.
func (o *Monitor) HasUid() bool {
	if o != nil && !IsNil(o.Uid) {
		return true
	}

	return false
}

// SetUid gets a reference to the given string and assigns it to the Uid field.
func (o *Monitor) SetUid(v string) {
	o.Uid = &v
}

func (o Monitor) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Monitor) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AggregateFunction) {
		toSerialize["aggregate_function"] = o.AggregateFunction
	}
	if !IsNil(o.AggregateWindow) {
		toSerialize["aggregate_window"] = o.AggregateWindow
	}
	if !IsNil(o.Alert) {
		toSerialize["alert"] = o.Alert
	}
	if !IsNil(o.AlertRoutes) {
		toSerialize["alert_routes"] = o.AlertRoutes
	}
	if !IsNil(o.ConditionType) {
		toSerialize["condition_type"] = o.ConditionType
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Disabled) {
		toSerialize["disabled"] = o.Disabled
	}
	if !IsNil(o.FleetFilter) {
		toSerialize["fleet_filter"] = o.FleetFilter
	}
	if !IsNil(o.LastRoutedAt) {
		toSerialize["last_routed_at"] = o.LastRoutedAt
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.NotefileFilter) {
		toSerialize["notefile_filter"] = o.NotefileFilter
	}
	if !IsNil(o.PerDevice) {
		toSerialize["per_device"] = o.PerDevice
	}
	if !IsNil(o.RoutingCooldownPeriod) {
		toSerialize["routing_cooldown_period"] = o.RoutingCooldownPeriod
	}
	if !IsNil(o.Silenced) {
		toSerialize["silenced"] = o.Silenced
	}
	if !IsNil(o.SourceSelector) {
		toSerialize["source_selector"] = o.SourceSelector
	}
	if !IsNil(o.SourceType) {
		toSerialize["source_type"] = o.SourceType
	}
	if !IsNil(o.Threshold) {
		toSerialize["threshold"] = o.Threshold
	}
	if !IsNil(o.Uid) {
		toSerialize["uid"] = o.Uid
	}
	return toSerialize, nil
}

type NullableMonitor struct {
	value *Monitor
	isSet bool
}

func (v NullableMonitor) Get() *Monitor {
	return v.value
}

func (v *NullableMonitor) Set(val *Monitor) {
	v.value = val
	v.isSet = true
}

func (v NullableMonitor) IsSet() bool {
	return v.isSet
}

func (v *NullableMonitor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMonitor(val *Monitor) *NullableMonitor {
	return &NullableMonitor{value: val, isSet: true}
}

func (v NullableMonitor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMonitor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
