/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetDataUsage200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetDataUsage200ResponseDataInner{}

// GetDataUsage200ResponseDataInner struct for GetDataUsage200ResponseDataInner
type GetDataUsage200ResponseDataInner struct {
	Data []UsageData `json:"data"`
	// The device UID this usage data belongs to (only present when aggregate is 'device')
	Device *string `json:"device,omitempty"`
	// the number of devices represented by this data point
	DeviceCount *int32 `json:"device_count,omitempty"`
	// The fleet UID this usage data belongs to (only present when aggregate is 'fleet')
	Fleet *string `json:"fleet,omitempty"`
	// The ICCID of the cellular SIM card (only present when type is 'cellular')
	Iccid *string `json:"iccid,omitempty"`
	// The IMSI of the satellite device (only present when type is 'satellite')
	Imsi *string `json:"imsi,omitempty"`
	// The type of connectivity
	Type string `json:"type"`
}

type _GetDataUsage200ResponseDataInner GetDataUsage200ResponseDataInner

// NewGetDataUsage200ResponseDataInner instantiates a new GetDataUsage200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetDataUsage200ResponseDataInner(data []UsageData, type_ string) *GetDataUsage200ResponseDataInner {
	this := GetDataUsage200ResponseDataInner{}
	this.Data = data
	this.Type = type_
	return &this
}

// NewGetDataUsage200ResponseDataInnerWithDefaults instantiates a new GetDataUsage200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetDataUsage200ResponseDataInnerWithDefaults() *GetDataUsage200ResponseDataInner {
	this := GetDataUsage200ResponseDataInner{}
	return &this
}

// GetData returns the Data field value
func (o *GetDataUsage200ResponseDataInner) GetData() []UsageData {
	if o == nil {
		var ret []UsageData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetDataUsage200ResponseDataInner) GetDataOk() ([]UsageData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GetDataUsage200ResponseDataInner) SetData(v []UsageData) {
	o.Data = v
}

// GetDevice returns the Device field value if set, zero value otherwise.
func (o *GetDataUsage200ResponseDataInner) GetDevice() string {
	if o == nil || IsNil(o.Device) {
		var ret string
		return ret
	}
	return *o.Device
}

// GetDeviceOk returns a tuple with the Device field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDataUsage200ResponseDataInner) GetDeviceOk() (*string, bool) {
	if o == nil || IsNil(o.Device) {
		return nil, false
	}
	return o.Device, true
}

// HasDevice returns a boolean if a field has been set.
func (o *GetDataUsage200ResponseDataInner) HasDevice() bool {
	if o != nil && !IsNil(o.Device) {
		return true
	}

	return false
}

// SetDevice gets a reference to the given string and assigns it to the Device field.
func (o *GetDataUsage200ResponseDataInner) SetDevice(v string) {
	o.Device = &v
}

// GetDeviceCount returns the DeviceCount field value if set, zero value otherwise.
func (o *GetDataUsage200ResponseDataInner) GetDeviceCount() int32 {
	if o == nil || IsNil(o.DeviceCount) {
		var ret int32
		return ret
	}
	return *o.DeviceCount
}

// GetDeviceCountOk returns a tuple with the DeviceCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDataUsage200ResponseDataInner) GetDeviceCountOk() (*int32, bool) {
	if o == nil || IsNil(o.DeviceCount) {
		return nil, false
	}
	return o.DeviceCount, true
}

// HasDeviceCount returns a boolean if a field has been set.
func (o *GetDataUsage200ResponseDataInner) HasDeviceCount() bool {
	if o != nil && !IsNil(o.DeviceCount) {
		return true
	}

	return false
}

// SetDeviceCount gets a reference to the given int32 and assigns it to the DeviceCount field.
func (o *GetDataUsage200ResponseDataInner) SetDeviceCount(v int32) {
	o.DeviceCount = &v
}

// GetFleet returns the Fleet field value if set, zero value otherwise.
func (o *GetDataUsage200ResponseDataInner) GetFleet() string {
	if o == nil || IsNil(o.Fleet) {
		var ret string
		return ret
	}
	return *o.Fleet
}

// GetFleetOk returns a tuple with the Fleet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDataUsage200ResponseDataInner) GetFleetOk() (*string, bool) {
	if o == nil || IsNil(o.Fleet) {
		return nil, false
	}
	return o.Fleet, true
}

// HasFleet returns a boolean if a field has been set.
func (o *GetDataUsage200ResponseDataInner) HasFleet() bool {
	if o != nil && !IsNil(o.Fleet) {
		return true
	}

	return false
}

// SetFleet gets a reference to the given string and assigns it to the Fleet field.
func (o *GetDataUsage200ResponseDataInner) SetFleet(v string) {
	o.Fleet = &v
}

// GetIccid returns the Iccid field value if set, zero value otherwise.
func (o *GetDataUsage200ResponseDataInner) GetIccid() string {
	if o == nil || IsNil(o.Iccid) {
		var ret string
		return ret
	}
	return *o.Iccid
}

// GetIccidOk returns a tuple with the Iccid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDataUsage200ResponseDataInner) GetIccidOk() (*string, bool) {
	if o == nil || IsNil(o.Iccid) {
		return nil, false
	}
	return o.Iccid, true
}

// HasIccid returns a boolean if a field has been set.
func (o *GetDataUsage200ResponseDataInner) HasIccid() bool {
	if o != nil && !IsNil(o.Iccid) {
		return true
	}

	return false
}

// SetIccid gets a reference to the given string and assigns it to the Iccid field.
func (o *GetDataUsage200ResponseDataInner) SetIccid(v string) {
	o.Iccid = &v
}

// GetImsi returns the Imsi field value if set, zero value otherwise.
func (o *GetDataUsage200ResponseDataInner) GetImsi() string {
	if o == nil || IsNil(o.Imsi) {
		var ret string
		return ret
	}
	return *o.Imsi
}

// GetImsiOk returns a tuple with the Imsi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDataUsage200ResponseDataInner) GetImsiOk() (*string, bool) {
	if o == nil || IsNil(o.Imsi) {
		return nil, false
	}
	return o.Imsi, true
}

// HasImsi returns a boolean if a field has been set.
func (o *GetDataUsage200ResponseDataInner) HasImsi() bool {
	if o != nil && !IsNil(o.Imsi) {
		return true
	}

	return false
}

// SetImsi gets a reference to the given string and assigns it to the Imsi field.
func (o *GetDataUsage200ResponseDataInner) SetImsi(v string) {
	o.Imsi = &v
}

// GetType returns the Type field value
func (o *GetDataUsage200ResponseDataInner) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GetDataUsage200ResponseDataInner) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GetDataUsage200ResponseDataInner) SetType(v string) {
	o.Type = v
}

func (o GetDataUsage200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetDataUsage200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	if !IsNil(o.Device) {
		toSerialize["device"] = o.Device
	}
	if !IsNil(o.DeviceCount) {
		toSerialize["device_count"] = o.DeviceCount
	}
	if !IsNil(o.Fleet) {
		toSerialize["fleet"] = o.Fleet
	}
	if !IsNil(o.Iccid) {
		toSerialize["iccid"] = o.Iccid
	}
	if !IsNil(o.Imsi) {
		toSerialize["imsi"] = o.Imsi
	}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *GetDataUsage200ResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetDataUsage200ResponseDataInner := _GetDataUsage200ResponseDataInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetDataUsage200ResponseDataInner)

	if err != nil {
		return err
	}

	*o = GetDataUsage200ResponseDataInner(varGetDataUsage200ResponseDataInner)

	return err
}

type NullableGetDataUsage200ResponseDataInner struct {
	value *GetDataUsage200ResponseDataInner
	isSet bool
}

func (v NullableGetDataUsage200ResponseDataInner) Get() *GetDataUsage200ResponseDataInner {
	return v.value
}

func (v *NullableGetDataUsage200ResponseDataInner) Set(val *GetDataUsage200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDataUsage200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDataUsage200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDataUsage200ResponseDataInner(val *GetDataUsage200ResponseDataInner) *NullableGetDataUsage200ResponseDataInner {
	return &NullableGetDataUsage200ResponseDataInner{value: val, isSet: true}
}

func (v NullableGetDataUsage200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetDataUsage200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
