/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"encoding/json"
)

// checks if the DeviceUsage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceUsage{}

// DeviceUsage struct for DeviceUsage
type DeviceUsage struct {
	BytesRcvd          *int64 `json:"bytes_rcvd,omitempty"`
	BytesRcvdSecondary *int64 `json:"bytes_rcvd_secondary,omitempty"`
	BytesSent          *int64 `json:"bytes_sent,omitempty"`
	BytesSentSecondary *int64 `json:"bytes_sent_secondary,omitempty"`
	// Duration in seconds
	Duration    *int64 `json:"duration,omitempty"`
	NotesRcvd   *int64 `json:"notes_rcvd,omitempty"`
	NotesSent   *int64 `json:"notes_sent,omitempty"`
	SessionsTcp *int64 `json:"sessions_tcp,omitempty"`
	SessionsTls *int64 `json:"sessions_tls,omitempty"`
	// Unix timestamp
	Since *int64 `json:"since,omitempty"`
}

// NewDeviceUsage instantiates a new DeviceUsage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceUsage() *DeviceUsage {
	this := DeviceUsage{}
	return &this
}

// NewDeviceUsageWithDefaults instantiates a new DeviceUsage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceUsageWithDefaults() *DeviceUsage {
	this := DeviceUsage{}
	return &this
}

// GetBytesRcvd returns the BytesRcvd field value if set, zero value otherwise.
func (o *DeviceUsage) GetBytesRcvd() int64 {
	if o == nil || IsNil(o.BytesRcvd) {
		var ret int64
		return ret
	}
	return *o.BytesRcvd
}

// GetBytesRcvdOk returns a tuple with the BytesRcvd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceUsage) GetBytesRcvdOk() (*int64, bool) {
	if o == nil || IsNil(o.BytesRcvd) {
		return nil, false
	}
	return o.BytesRcvd, true
}

// HasBytesRcvd returns a boolean if a field has been set.
func (o *DeviceUsage) HasBytesRcvd() bool {
	if o != nil && !IsNil(o.BytesRcvd) {
		return true
	}

	return false
}

// SetBytesRcvd gets a reference to the given int64 and assigns it to the BytesRcvd field.
func (o *DeviceUsage) SetBytesRcvd(v int64) {
	o.BytesRcvd = &v
}

// GetBytesRcvdSecondary returns the BytesRcvdSecondary field value if set, zero value otherwise.
func (o *DeviceUsage) GetBytesRcvdSecondary() int64 {
	if o == nil || IsNil(o.BytesRcvdSecondary) {
		var ret int64
		return ret
	}
	return *o.BytesRcvdSecondary
}

// GetBytesRcvdSecondaryOk returns a tuple with the BytesRcvdSecondary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceUsage) GetBytesRcvdSecondaryOk() (*int64, bool) {
	if o == nil || IsNil(o.BytesRcvdSecondary) {
		return nil, false
	}
	return o.BytesRcvdSecondary, true
}

// HasBytesRcvdSecondary returns a boolean if a field has been set.
func (o *DeviceUsage) HasBytesRcvdSecondary() bool {
	if o != nil && !IsNil(o.BytesRcvdSecondary) {
		return true
	}

	return false
}

// SetBytesRcvdSecondary gets a reference to the given int64 and assigns it to the BytesRcvdSecondary field.
func (o *DeviceUsage) SetBytesRcvdSecondary(v int64) {
	o.BytesRcvdSecondary = &v
}

// GetBytesSent returns the BytesSent field value if set, zero value otherwise.
func (o *DeviceUsage) GetBytesSent() int64 {
	if o == nil || IsNil(o.BytesSent) {
		var ret int64
		return ret
	}
	return *o.BytesSent
}

// GetBytesSentOk returns a tuple with the BytesSent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceUsage) GetBytesSentOk() (*int64, bool) {
	if o == nil || IsNil(o.BytesSent) {
		return nil, false
	}
	return o.BytesSent, true
}

// HasBytesSent returns a boolean if a field has been set.
func (o *DeviceUsage) HasBytesSent() bool {
	if o != nil && !IsNil(o.BytesSent) {
		return true
	}

	return false
}

// SetBytesSent gets a reference to the given int64 and assigns it to the BytesSent field.
func (o *DeviceUsage) SetBytesSent(v int64) {
	o.BytesSent = &v
}

// GetBytesSentSecondary returns the BytesSentSecondary field value if set, zero value otherwise.
func (o *DeviceUsage) GetBytesSentSecondary() int64 {
	if o == nil || IsNil(o.BytesSentSecondary) {
		var ret int64
		return ret
	}
	return *o.BytesSentSecondary
}

// GetBytesSentSecondaryOk returns a tuple with the BytesSentSecondary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceUsage) GetBytesSentSecondaryOk() (*int64, bool) {
	if o == nil || IsNil(o.BytesSentSecondary) {
		return nil, false
	}
	return o.BytesSentSecondary, true
}

// HasBytesSentSecondary returns a boolean if a field has been set.
func (o *DeviceUsage) HasBytesSentSecondary() bool {
	if o != nil && !IsNil(o.BytesSentSecondary) {
		return true
	}

	return false
}

// SetBytesSentSecondary gets a reference to the given int64 and assigns it to the BytesSentSecondary field.
func (o *DeviceUsage) SetBytesSentSecondary(v int64) {
	o.BytesSentSecondary = &v
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *DeviceUsage) GetDuration() int64 {
	if o == nil || IsNil(o.Duration) {
		var ret int64
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceUsage) GetDurationOk() (*int64, bool) {
	if o == nil || IsNil(o.Duration) {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *DeviceUsage) HasDuration() bool {
	if o != nil && !IsNil(o.Duration) {
		return true
	}

	return false
}

// SetDuration gets a reference to the given int64 and assigns it to the Duration field.
func (o *DeviceUsage) SetDuration(v int64) {
	o.Duration = &v
}

// GetNotesRcvd returns the NotesRcvd field value if set, zero value otherwise.
func (o *DeviceUsage) GetNotesRcvd() int64 {
	if o == nil || IsNil(o.NotesRcvd) {
		var ret int64
		return ret
	}
	return *o.NotesRcvd
}

// GetNotesRcvdOk returns a tuple with the NotesRcvd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceUsage) GetNotesRcvdOk() (*int64, bool) {
	if o == nil || IsNil(o.NotesRcvd) {
		return nil, false
	}
	return o.NotesRcvd, true
}

// HasNotesRcvd returns a boolean if a field has been set.
func (o *DeviceUsage) HasNotesRcvd() bool {
	if o != nil && !IsNil(o.NotesRcvd) {
		return true
	}

	return false
}

// SetNotesRcvd gets a reference to the given int64 and assigns it to the NotesRcvd field.
func (o *DeviceUsage) SetNotesRcvd(v int64) {
	o.NotesRcvd = &v
}

// GetNotesSent returns the NotesSent field value if set, zero value otherwise.
func (o *DeviceUsage) GetNotesSent() int64 {
	if o == nil || IsNil(o.NotesSent) {
		var ret int64
		return ret
	}
	return *o.NotesSent
}

// GetNotesSentOk returns a tuple with the NotesSent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceUsage) GetNotesSentOk() (*int64, bool) {
	if o == nil || IsNil(o.NotesSent) {
		return nil, false
	}
	return o.NotesSent, true
}

// HasNotesSent returns a boolean if a field has been set.
func (o *DeviceUsage) HasNotesSent() bool {
	if o != nil && !IsNil(o.NotesSent) {
		return true
	}

	return false
}

// SetNotesSent gets a reference to the given int64 and assigns it to the NotesSent field.
func (o *DeviceUsage) SetNotesSent(v int64) {
	o.NotesSent = &v
}

// GetSessionsTcp returns the SessionsTcp field value if set, zero value otherwise.
func (o *DeviceUsage) GetSessionsTcp() int64 {
	if o == nil || IsNil(o.SessionsTcp) {
		var ret int64
		return ret
	}
	return *o.SessionsTcp
}

// GetSessionsTcpOk returns a tuple with the SessionsTcp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceUsage) GetSessionsTcpOk() (*int64, bool) {
	if o == nil || IsNil(o.SessionsTcp) {
		return nil, false
	}
	return o.SessionsTcp, true
}

// HasSessionsTcp returns a boolean if a field has been set.
func (o *DeviceUsage) HasSessionsTcp() bool {
	if o != nil && !IsNil(o.SessionsTcp) {
		return true
	}

	return false
}

// SetSessionsTcp gets a reference to the given int64 and assigns it to the SessionsTcp field.
func (o *DeviceUsage) SetSessionsTcp(v int64) {
	o.SessionsTcp = &v
}

// GetSessionsTls returns the SessionsTls field value if set, zero value otherwise.
func (o *DeviceUsage) GetSessionsTls() int64 {
	if o == nil || IsNil(o.SessionsTls) {
		var ret int64
		return ret
	}
	return *o.SessionsTls
}

// GetSessionsTlsOk returns a tuple with the SessionsTls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceUsage) GetSessionsTlsOk() (*int64, bool) {
	if o == nil || IsNil(o.SessionsTls) {
		return nil, false
	}
	return o.SessionsTls, true
}

// HasSessionsTls returns a boolean if a field has been set.
func (o *DeviceUsage) HasSessionsTls() bool {
	if o != nil && !IsNil(o.SessionsTls) {
		return true
	}

	return false
}

// SetSessionsTls gets a reference to the given int64 and assigns it to the SessionsTls field.
func (o *DeviceUsage) SetSessionsTls(v int64) {
	o.SessionsTls = &v
}

// GetSince returns the Since field value if set, zero value otherwise.
func (o *DeviceUsage) GetSince() int64 {
	if o == nil || IsNil(o.Since) {
		var ret int64
		return ret
	}
	return *o.Since
}

// GetSinceOk returns a tuple with the Since field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceUsage) GetSinceOk() (*int64, bool) {
	if o == nil || IsNil(o.Since) {
		return nil, false
	}
	return o.Since, true
}

// HasSince returns a boolean if a field has been set.
func (o *DeviceUsage) HasSince() bool {
	if o != nil && !IsNil(o.Since) {
		return true
	}

	return false
}

// SetSince gets a reference to the given int64 and assigns it to the Since field.
func (o *DeviceUsage) SetSince(v int64) {
	o.Since = &v
}

func (o DeviceUsage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceUsage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BytesRcvd) {
		toSerialize["bytes_rcvd"] = o.BytesRcvd
	}
	if !IsNil(o.BytesRcvdSecondary) {
		toSerialize["bytes_rcvd_secondary"] = o.BytesRcvdSecondary
	}
	if !IsNil(o.BytesSent) {
		toSerialize["bytes_sent"] = o.BytesSent
	}
	if !IsNil(o.BytesSentSecondary) {
		toSerialize["bytes_sent_secondary"] = o.BytesSentSecondary
	}
	if !IsNil(o.Duration) {
		toSerialize["duration"] = o.Duration
	}
	if !IsNil(o.NotesRcvd) {
		toSerialize["notes_rcvd"] = o.NotesRcvd
	}
	if !IsNil(o.NotesSent) {
		toSerialize["notes_sent"] = o.NotesSent
	}
	if !IsNil(o.SessionsTcp) {
		toSerialize["sessions_tcp"] = o.SessionsTcp
	}
	if !IsNil(o.SessionsTls) {
		toSerialize["sessions_tls"] = o.SessionsTls
	}
	if !IsNil(o.Since) {
		toSerialize["since"] = o.Since
	}
	return toSerialize, nil
}

type NullableDeviceUsage struct {
	value *DeviceUsage
	isSet bool
}

func (v NullableDeviceUsage) Get() *DeviceUsage {
	return v.value
}

func (v *NullableDeviceUsage) Set(val *DeviceUsage) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceUsage) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceUsage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceUsage(val *DeviceUsage) *NullableDeviceUsage {
	return &NullableDeviceUsage{value: val, isSet: true}
}

func (v NullableDeviceUsage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceUsage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
