/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UsageEventsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsageEventsResponse{}

// UsageEventsResponse struct for UsageEventsResponse
type UsageEventsResponse struct {
	Data []UsageEventsData `json:"data"`
}

type _UsageEventsResponse UsageEventsResponse

// NewUsageEventsResponse instantiates a new UsageEventsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsageEventsResponse(data []UsageEventsData) *UsageEventsResponse {
	this := UsageEventsResponse{}
	this.Data = data
	return &this
}

// NewUsageEventsResponseWithDefaults instantiates a new UsageEventsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsageEventsResponseWithDefaults() *UsageEventsResponse {
	this := UsageEventsResponse{}
	return &this
}

// GetData returns the Data field value
func (o *UsageEventsResponse) GetData() []UsageEventsData {
	if o == nil {
		var ret []UsageEventsData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UsageEventsResponse) GetDataOk() ([]UsageEventsData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *UsageEventsResponse) SetData(v []UsageEventsData) {
	o.Data = v
}

func (o UsageEventsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsageEventsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UsageEventsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUsageEventsResponse := _UsageEventsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUsageEventsResponse)

	if err != nil {
		return err
	}

	*o = UsageEventsResponse(varUsageEventsResponse)

	return err
}

type NullableUsageEventsResponse struct {
	value *UsageEventsResponse
	isSet bool
}

func (v NullableUsageEventsResponse) Get() *UsageEventsResponse {
	return v.value
}

func (v *NullableUsageEventsResponse) Set(val *UsageEventsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUsageEventsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUsageEventsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsageEventsResponse(val *UsageEventsResponse) *NullableUsageEventsResponse {
	return &NullableUsageEventsResponse{value: val, isSet: true}
}

func (v NullableUsageEventsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsageEventsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
