/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"encoding/json"
)

// checks if the GetProducts200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetProducts200Response{}

// GetProducts200Response struct for GetProducts200Response
type GetProducts200Response struct {
	Products []Product `json:"products,omitempty"`
}

// NewGetProducts200Response instantiates a new GetProducts200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetProducts200Response() *GetProducts200Response {
	this := GetProducts200Response{}
	return &this
}

// NewGetProducts200ResponseWithDefaults instantiates a new GetProducts200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetProducts200ResponseWithDefaults() *GetProducts200Response {
	this := GetProducts200Response{}
	return &this
}

// GetProducts returns the Products field value if set, zero value otherwise.
func (o *GetProducts200Response) GetProducts() []Product {
	if o == nil || IsNil(o.Products) {
		var ret []Product
		return ret
	}
	return o.Products
}

// GetProductsOk returns a tuple with the Products field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProducts200Response) GetProductsOk() ([]Product, bool) {
	if o == nil || IsNil(o.Products) {
		return nil, false
	}
	return o.Products, true
}

// HasProducts returns a boolean if a field has been set.
func (o *GetProducts200Response) HasProducts() bool {
	if o != nil && !IsNil(o.Products) {
		return true
	}

	return false
}

// SetProducts gets a reference to the given []Product and assigns it to the Products field.
func (o *GetProducts200Response) SetProducts(v []Product) {
	o.Products = v
}

func (o GetProducts200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetProducts200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Products) {
		toSerialize["products"] = o.Products
	}
	return toSerialize, nil
}

type NullableGetProducts200Response struct {
	value *GetProducts200Response
	isSet bool
}

func (v NullableGetProducts200Response) Get() *GetProducts200Response {
	return v.value
}

func (v *NullableGetProducts200Response) Set(val *GetProducts200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetProducts200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetProducts200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetProducts200Response(val *GetProducts200Response) *NullableGetProducts200Response {
	return &NullableGetProducts200Response{value: val, isSet: true}
}

func (v NullableGetProducts200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetProducts200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
