/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"encoding/json"
	"fmt"
)

// checks if the DescriptionRecordList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DescriptionRecordList{}

// DescriptionRecordList struct for DescriptionRecordList
type DescriptionRecordList struct {
	Descriptions         []DescriptionRecord `json:"descriptions"`
	AdditionalProperties map[string]interface{}
}

type _DescriptionRecordList DescriptionRecordList

// NewDescriptionRecordList instantiates a new DescriptionRecordList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDescriptionRecordList(descriptions []DescriptionRecord) *DescriptionRecordList {
	this := DescriptionRecordList{}
	this.Descriptions = descriptions
	return &this
}

// NewDescriptionRecordListWithDefaults instantiates a new DescriptionRecordList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDescriptionRecordListWithDefaults() *DescriptionRecordList {
	this := DescriptionRecordList{}
	return &this
}

// GetDescriptions returns the Descriptions field value
func (o *DescriptionRecordList) GetDescriptions() []DescriptionRecord {
	if o == nil {
		var ret []DescriptionRecord
		return ret
	}

	return o.Descriptions
}

// GetDescriptionsOk returns a tuple with the Descriptions field value
// and a boolean to check if the value has been set.
func (o *DescriptionRecordList) GetDescriptionsOk() ([]DescriptionRecord, bool) {
	if o == nil {
		return nil, false
	}
	return o.Descriptions, true
}

// SetDescriptions sets field value
func (o *DescriptionRecordList) SetDescriptions(v []DescriptionRecord) {
	o.Descriptions = v
}

func (o DescriptionRecordList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DescriptionRecordList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["descriptions"] = o.Descriptions

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DescriptionRecordList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"descriptions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDescriptionRecordList := _DescriptionRecordList{}

	err = json.Unmarshal(data, &varDescriptionRecordList)

	if err != nil {
		return err
	}

	*o = DescriptionRecordList(varDescriptionRecordList)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "descriptions")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDescriptionRecordList struct {
	value *DescriptionRecordList
	isSet bool
}

func (v NullableDescriptionRecordList) Get() *DescriptionRecordList {
	return v.value
}

func (v *NullableDescriptionRecordList) Set(val *DescriptionRecordList) {
	v.value = val
	v.isSet = true
}

func (v NullableDescriptionRecordList) IsSet() bool {
	return v.isSet
}

func (v *NullableDescriptionRecordList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDescriptionRecordList(val *DescriptionRecordList) *NullableDescriptionRecordList {
	return &NullableDescriptionRecordList{value: val, isSet: true}
}

func (v NullableDescriptionRecordList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDescriptionRecordList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
