/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"encoding/json"
)

// checks if the DeviceDfuStateMachine type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceDfuStateMachine{}

// DeviceDfuStateMachine Represents a single request to update the host or Notecard firmware
type DeviceDfuStateMachine struct {
	// Version of the firmware that was installed prior to this request
	CurrentVersion *string `json:"current_version,omitempty"`
	// RFC3339 datetime of when this update was requested
	Initiated *string `json:"initiated,omitempty"`
	// Version of the firmware that was requested to be installed
	RequestedVersion *string                     `json:"requested_version,omitempty"`
	Updates          []DeviceDfuStateMachineNode `json:"updates,omitempty"`
}

// NewDeviceDfuStateMachine instantiates a new DeviceDfuStateMachine object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceDfuStateMachine() *DeviceDfuStateMachine {
	this := DeviceDfuStateMachine{}
	return &this
}

// NewDeviceDfuStateMachineWithDefaults instantiates a new DeviceDfuStateMachine object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceDfuStateMachineWithDefaults() *DeviceDfuStateMachine {
	this := DeviceDfuStateMachine{}
	return &this
}

// GetCurrentVersion returns the CurrentVersion field value if set, zero value otherwise.
func (o *DeviceDfuStateMachine) GetCurrentVersion() string {
	if o == nil || IsNil(o.CurrentVersion) {
		var ret string
		return ret
	}
	return *o.CurrentVersion
}

// GetCurrentVersionOk returns a tuple with the CurrentVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceDfuStateMachine) GetCurrentVersionOk() (*string, bool) {
	if o == nil || IsNil(o.CurrentVersion) {
		return nil, false
	}
	return o.CurrentVersion, true
}

// HasCurrentVersion returns a boolean if a field has been set.
func (o *DeviceDfuStateMachine) HasCurrentVersion() bool {
	if o != nil && !IsNil(o.CurrentVersion) {
		return true
	}

	return false
}

// SetCurrentVersion gets a reference to the given string and assigns it to the CurrentVersion field.
func (o *DeviceDfuStateMachine) SetCurrentVersion(v string) {
	o.CurrentVersion = &v
}

// GetInitiated returns the Initiated field value if set, zero value otherwise.
func (o *DeviceDfuStateMachine) GetInitiated() string {
	if o == nil || IsNil(o.Initiated) {
		var ret string
		return ret
	}
	return *o.Initiated
}

// GetInitiatedOk returns a tuple with the Initiated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceDfuStateMachine) GetInitiatedOk() (*string, bool) {
	if o == nil || IsNil(o.Initiated) {
		return nil, false
	}
	return o.Initiated, true
}

// HasInitiated returns a boolean if a field has been set.
func (o *DeviceDfuStateMachine) HasInitiated() bool {
	if o != nil && !IsNil(o.Initiated) {
		return true
	}

	return false
}

// SetInitiated gets a reference to the given string and assigns it to the Initiated field.
func (o *DeviceDfuStateMachine) SetInitiated(v string) {
	o.Initiated = &v
}

// GetRequestedVersion returns the RequestedVersion field value if set, zero value otherwise.
func (o *DeviceDfuStateMachine) GetRequestedVersion() string {
	if o == nil || IsNil(o.RequestedVersion) {
		var ret string
		return ret
	}
	return *o.RequestedVersion
}

// GetRequestedVersionOk returns a tuple with the RequestedVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceDfuStateMachine) GetRequestedVersionOk() (*string, bool) {
	if o == nil || IsNil(o.RequestedVersion) {
		return nil, false
	}
	return o.RequestedVersion, true
}

// HasRequestedVersion returns a boolean if a field has been set.
func (o *DeviceDfuStateMachine) HasRequestedVersion() bool {
	if o != nil && !IsNil(o.RequestedVersion) {
		return true
	}

	return false
}

// SetRequestedVersion gets a reference to the given string and assigns it to the RequestedVersion field.
func (o *DeviceDfuStateMachine) SetRequestedVersion(v string) {
	o.RequestedVersion = &v
}

// GetUpdates returns the Updates field value if set, zero value otherwise.
func (o *DeviceDfuStateMachine) GetUpdates() []DeviceDfuStateMachineNode {
	if o == nil || IsNil(o.Updates) {
		var ret []DeviceDfuStateMachineNode
		return ret
	}
	return o.Updates
}

// GetUpdatesOk returns a tuple with the Updates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceDfuStateMachine) GetUpdatesOk() ([]DeviceDfuStateMachineNode, bool) {
	if o == nil || IsNil(o.Updates) {
		return nil, false
	}
	return o.Updates, true
}

// HasUpdates returns a boolean if a field has been set.
func (o *DeviceDfuStateMachine) HasUpdates() bool {
	if o != nil && !IsNil(o.Updates) {
		return true
	}

	return false
}

// SetUpdates gets a reference to the given []DeviceDfuStateMachineNode and assigns it to the Updates field.
func (o *DeviceDfuStateMachine) SetUpdates(v []DeviceDfuStateMachineNode) {
	o.Updates = v
}

func (o DeviceDfuStateMachine) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceDfuStateMachine) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CurrentVersion) {
		toSerialize["current_version"] = o.CurrentVersion
	}
	if !IsNil(o.Initiated) {
		toSerialize["initiated"] = o.Initiated
	}
	if !IsNil(o.RequestedVersion) {
		toSerialize["requested_version"] = o.RequestedVersion
	}
	if !IsNil(o.Updates) {
		toSerialize["updates"] = o.Updates
	}
	return toSerialize, nil
}

type NullableDeviceDfuStateMachine struct {
	value *DeviceDfuStateMachine
	isSet bool
}

func (v NullableDeviceDfuStateMachine) Get() *DeviceDfuStateMachine {
	return v.value
}

func (v *NullableDeviceDfuStateMachine) Set(val *DeviceDfuStateMachine) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceDfuStateMachine) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceDfuStateMachine) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceDfuStateMachine(val *DeviceDfuStateMachine) *NullableDeviceDfuStateMachine {
	return &NullableDeviceDfuStateMachine{value: val, isSet: true}
}

func (v NullableDeviceDfuStateMachine) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceDfuStateMachine) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
