/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"encoding/json"
)

// checks if the DeviceDfuStatusPage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceDfuStatusPage{}

// DeviceDfuStatusPage struct for DeviceDfuStatusPage
type DeviceDfuStatusPage struct {
	Devices []DeviceDfuStatus `json:"devices,omitempty"`
	HasMore *bool             `json:"has_more,omitempty"`
}

// NewDeviceDfuStatusPage instantiates a new DeviceDfuStatusPage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceDfuStatusPage() *DeviceDfuStatusPage {
	this := DeviceDfuStatusPage{}
	var hasMore bool = false
	this.HasMore = &hasMore
	return &this
}

// NewDeviceDfuStatusPageWithDefaults instantiates a new DeviceDfuStatusPage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceDfuStatusPageWithDefaults() *DeviceDfuStatusPage {
	this := DeviceDfuStatusPage{}
	var hasMore bool = false
	this.HasMore = &hasMore
	return &this
}

// GetDevices returns the Devices field value if set, zero value otherwise.
func (o *DeviceDfuStatusPage) GetDevices() []DeviceDfuStatus {
	if o == nil || IsNil(o.Devices) {
		var ret []DeviceDfuStatus
		return ret
	}
	return o.Devices
}

// GetDevicesOk returns a tuple with the Devices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceDfuStatusPage) GetDevicesOk() ([]DeviceDfuStatus, bool) {
	if o == nil || IsNil(o.Devices) {
		return nil, false
	}
	return o.Devices, true
}

// HasDevices returns a boolean if a field has been set.
func (o *DeviceDfuStatusPage) HasDevices() bool {
	if o != nil && !IsNil(o.Devices) {
		return true
	}

	return false
}

// SetDevices gets a reference to the given []DeviceDfuStatus and assigns it to the Devices field.
func (o *DeviceDfuStatusPage) SetDevices(v []DeviceDfuStatus) {
	o.Devices = v
}

// GetHasMore returns the HasMore field value if set, zero value otherwise.
func (o *DeviceDfuStatusPage) GetHasMore() bool {
	if o == nil || IsNil(o.HasMore) {
		var ret bool
		return ret
	}
	return *o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceDfuStatusPage) GetHasMoreOk() (*bool, bool) {
	if o == nil || IsNil(o.HasMore) {
		return nil, false
	}
	return o.HasMore, true
}

// HasHasMore returns a boolean if a field has been set.
func (o *DeviceDfuStatusPage) HasHasMore() bool {
	if o != nil && !IsNil(o.HasMore) {
		return true
	}

	return false
}

// SetHasMore gets a reference to the given bool and assigns it to the HasMore field.
func (o *DeviceDfuStatusPage) SetHasMore(v bool) {
	o.HasMore = &v
}

func (o DeviceDfuStatusPage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceDfuStatusPage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Devices) {
		toSerialize["devices"] = o.Devices
	}
	if !IsNil(o.HasMore) {
		toSerialize["has_more"] = o.HasMore
	}
	return toSerialize, nil
}

type NullableDeviceDfuStatusPage struct {
	value *DeviceDfuStatusPage
	isSet bool
}

func (v NullableDeviceDfuStatusPage) Get() *DeviceDfuStatusPage {
	return v.value
}

func (v *NullableDeviceDfuStatusPage) Set(val *DeviceDfuStatusPage) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceDfuStatusPage) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceDfuStatusPage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceDfuStatusPage(val *DeviceDfuStatusPage) *NullableDeviceDfuStatusPage {
	return &NullableDeviceDfuStatusPage{value: val, isSet: true}
}

func (v NullableDeviceDfuStatusPage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceDfuStatusPage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
