/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"encoding/json"
)

// checks if the GetDeviceLatestEvents200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetDeviceLatestEvents200Response{}

// GetDeviceLatestEvents200Response struct for GetDeviceLatestEvents200Response
type GetDeviceLatestEvents200Response struct {
	// The set of latest events.  Will always include the current \"session.begin\" event.
	LatestEvents []Event `json:"latest_events,omitempty"`
}

// NewGetDeviceLatestEvents200Response instantiates a new GetDeviceLatestEvents200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetDeviceLatestEvents200Response() *GetDeviceLatestEvents200Response {
	this := GetDeviceLatestEvents200Response{}
	return &this
}

// NewGetDeviceLatestEvents200ResponseWithDefaults instantiates a new GetDeviceLatestEvents200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetDeviceLatestEvents200ResponseWithDefaults() *GetDeviceLatestEvents200Response {
	this := GetDeviceLatestEvents200Response{}
	return &this
}

// GetLatestEvents returns the LatestEvents field value if set, zero value otherwise.
func (o *GetDeviceLatestEvents200Response) GetLatestEvents() []Event {
	if o == nil || IsNil(o.LatestEvents) {
		var ret []Event
		return ret
	}
	return o.LatestEvents
}

// GetLatestEventsOk returns a tuple with the LatestEvents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDeviceLatestEvents200Response) GetLatestEventsOk() ([]Event, bool) {
	if o == nil || IsNil(o.LatestEvents) {
		return nil, false
	}
	return o.LatestEvents, true
}

// HasLatestEvents returns a boolean if a field has been set.
func (o *GetDeviceLatestEvents200Response) HasLatestEvents() bool {
	if o != nil && !IsNil(o.LatestEvents) {
		return true
	}

	return false
}

// SetLatestEvents gets a reference to the given []Event and assigns it to the LatestEvents field.
func (o *GetDeviceLatestEvents200Response) SetLatestEvents(v []Event) {
	o.LatestEvents = v
}

func (o GetDeviceLatestEvents200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetDeviceLatestEvents200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LatestEvents) {
		toSerialize["latest_events"] = o.LatestEvents
	}
	return toSerialize, nil
}

type NullableGetDeviceLatestEvents200Response struct {
	value *GetDeviceLatestEvents200Response
	isSet bool
}

func (v NullableGetDeviceLatestEvents200Response) Get() *GetDeviceLatestEvents200Response {
	return v.value
}

func (v *NullableGetDeviceLatestEvents200Response) Set(val *GetDeviceLatestEvents200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDeviceLatestEvents200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDeviceLatestEvents200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDeviceLatestEvents200Response(val *GetDeviceLatestEvents200Response) *NullableGetDeviceLatestEvents200Response {
	return &NullableGetDeviceLatestEvents200Response{value: val, isSet: true}
}

func (v NullableGetDeviceLatestEvents200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetDeviceLatestEvents200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
