/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"encoding/json"
)

// checks if the Event type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Event{}

// Event struct for Event
type Event struct {
	// App UID (globally unique)
	App *string `json:"app,omitempty"`
	// Bars. Only available on _session.qo events.
	Bars *float32 `json:"bars,omitempty"`
	// Country
	BestCountry *string `json:"best_country,omitempty"`
	// The device serial number, or the DeviceUID if the serial number is not set
	BestId *string `json:"best_id,omitempty"`
	// Latitude
	BestLat *float64 `json:"best_lat,omitempty"`
	// Location
	BestLocation *string `json:"best_location,omitempty"`
	// One of \"gps\", \"triangulated\", or \"tower\"
	BestLocationType *string `json:"best_location_type,omitempty"`
	// Unix timestamp
	BestLocationWhen *float32 `json:"best_location_when,omitempty"`
	// Longitude
	BestLon *float64 `json:"best_lon,omitempty"`
	// Timezone
	BestTimezone *string `json:"best_timezone,omitempty"`
	// A JSON object containing event details
	Body map[string]interface{} `json:"body,omitempty"`
	// BSSID. Only available on _session.qo events.
	Bssid *string `json:"bssid,omitempty"`
	// Device UID (globally unique)
	Device *string `json:"device,omitempty"`
	// Routed environment variables beginning with \"$\". Only available on _session.qo events.
	Environment map[string]interface{} `json:"environment,omitempty"`
	// Event UID (globally unique)
	Event *string `json:"event,omitempty"`
	// The notefile associated with this event
	File *string `json:"file,omitempty"`
	// The number of times the device was sensed to have moved between the last session and this session. Only available on _session.qo events.
	Moved *float32 `json:"moved,omitempty"`
	// The note ID in the notefile
	Note *string `json:"note,omitempty"`
	// Ordering code. Only available on _session.qo events.
	OrderingCode *string `json:"ordering_code,omitempty"`
	// The orientation of the device. Only available on _session.qo events.
	Orientation *string `json:"orientation,omitempty"`
	// A base64-encoded binary payload
	Payload *string `json:"payload,omitempty"`
	// Product UID (globally unique)
	Product *string `json:"product,omitempty"`
	// Rat. Only available on _session.qo events.
	Rat *string `json:"rat,omitempty"`
	// The unix timestamp when the event was received
	Received *float64 `json:"received,omitempty"`
	// The notecard request
	Req *string `json:"req,omitempty"`
	// RSRP. Only available on _session.qo events.
	Rsrp *float32 `json:"rsrp,omitempty"`
	// RSRQ. Only available on _session.qo events.
	Rsrq *float32 `json:"rsrq,omitempty"`
	// Received Signal Strength Indicator (RSSI) is an estimated measurement of how well a device can receive signals. Only available on _session.qo events.
	Rssi *float32 `json:"rssi,omitempty"`
	// Session UID (globally unique)
	Session *string `json:"session,omitempty"`
	// SINR. Only available on _session.qo events.
	Sinr *float32 `json:"sinr,omitempty"`
	// SKU. Only available on _session.qo events.
	Sku *string `json:"sku,omitempty"`
	// The device serial number
	Sn *string `json:"sn,omitempty"`
	// SSID. Only available on _session.qo events.
	Ssid *string `json:"ssid,omitempty"`
	// Device temperature. Only available on _session.qo events.
	Temp *float64 `json:"temp,omitempty"`
	// Whether TLS was used on the connection between the device and notehub. Only available on _session.qo events.
	Tls *bool `json:"tls,omitempty"`
	// Country
	TowerCountry *string `json:"tower_country,omitempty"`
	// Tower ID
	TowerId *string `json:"tower_id,omitempty"`
	// Latitude
	TowerLat *float64 `json:"tower_lat,omitempty"`
	// Location
	TowerLocation *string `json:"tower_location,omitempty"`
	// Longitude
	TowerLon *float64 `json:"tower_lon,omitempty"`
	// Timezone
	TowerTimezone *string `json:"tower_timezone,omitempty"`
	// Unix timestamp
	TowerWhen *float32 `json:"tower_when,omitempty"`
	// The transport used for this event, e.g., \"cellular\", \"wifi\", \", etc.
	Transport *string `json:"transport,omitempty"`
	// Country
	TriCountry *string `json:"tri_country,omitempty"`
	// Latitude
	TriLat *float64 `json:"tri_lat,omitempty"`
	// Location
	TriLocation *string `json:"tri_location,omitempty"`
	// Longitude
	TriLon *float64 `json:"tri_lon,omitempty"`
	// Triangulation points
	TriPoints *float32 `json:"tri_points,omitempty"`
	// Timezone
	TriTimezone *string `json:"tri_timezone,omitempty"`
	// Unix timestamp
	TriWhen *float32 `json:"tri_when,omitempty"`
	Updates *float32 `json:"updates,omitempty"`
	// Device voltage. Only available on _session.qo events.
	Voltage *float64 `json:"voltage,omitempty"`
	// When the event was captured on the device
	When *float32 `json:"when,omitempty"`
	// Country
	WhereCountry *string `json:"where_country,omitempty"`
	// Latitude
	WhereLat *float64 `json:"where_lat,omitempty"`
	// Location
	WhereLocation *string `json:"where_location,omitempty"`
	// Longitude
	WhereLon *float64 `json:"where_lon,omitempty"`
	// Open Location Code
	WhereOlc *string `json:"where_olc,omitempty"`
	// Timezone
	WhereTimezone *string `json:"where_timezone,omitempty"`
	// Unix timestamp
	WhereWhen *float32 `json:"where_when,omitempty"`
}

// NewEvent instantiates a new Event object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEvent() *Event {
	this := Event{}
	return &this
}

// NewEventWithDefaults instantiates a new Event object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventWithDefaults() *Event {
	this := Event{}
	return &this
}

// GetApp returns the App field value if set, zero value otherwise.
func (o *Event) GetApp() string {
	if o == nil || IsNil(o.App) {
		var ret string
		return ret
	}
	return *o.App
}

// GetAppOk returns a tuple with the App field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetAppOk() (*string, bool) {
	if o == nil || IsNil(o.App) {
		return nil, false
	}
	return o.App, true
}

// HasApp returns a boolean if a field has been set.
func (o *Event) HasApp() bool {
	if o != nil && !IsNil(o.App) {
		return true
	}

	return false
}

// SetApp gets a reference to the given string and assigns it to the App field.
func (o *Event) SetApp(v string) {
	o.App = &v
}

// GetBars returns the Bars field value if set, zero value otherwise.
func (o *Event) GetBars() float32 {
	if o == nil || IsNil(o.Bars) {
		var ret float32
		return ret
	}
	return *o.Bars
}

// GetBarsOk returns a tuple with the Bars field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetBarsOk() (*float32, bool) {
	if o == nil || IsNil(o.Bars) {
		return nil, false
	}
	return o.Bars, true
}

// HasBars returns a boolean if a field has been set.
func (o *Event) HasBars() bool {
	if o != nil && !IsNil(o.Bars) {
		return true
	}

	return false
}

// SetBars gets a reference to the given float32 and assigns it to the Bars field.
func (o *Event) SetBars(v float32) {
	o.Bars = &v
}

// GetBestCountry returns the BestCountry field value if set, zero value otherwise.
func (o *Event) GetBestCountry() string {
	if o == nil || IsNil(o.BestCountry) {
		var ret string
		return ret
	}
	return *o.BestCountry
}

// GetBestCountryOk returns a tuple with the BestCountry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetBestCountryOk() (*string, bool) {
	if o == nil || IsNil(o.BestCountry) {
		return nil, false
	}
	return o.BestCountry, true
}

// HasBestCountry returns a boolean if a field has been set.
func (o *Event) HasBestCountry() bool {
	if o != nil && !IsNil(o.BestCountry) {
		return true
	}

	return false
}

// SetBestCountry gets a reference to the given string and assigns it to the BestCountry field.
func (o *Event) SetBestCountry(v string) {
	o.BestCountry = &v
}

// GetBestId returns the BestId field value if set, zero value otherwise.
func (o *Event) GetBestId() string {
	if o == nil || IsNil(o.BestId) {
		var ret string
		return ret
	}
	return *o.BestId
}

// GetBestIdOk returns a tuple with the BestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetBestIdOk() (*string, bool) {
	if o == nil || IsNil(o.BestId) {
		return nil, false
	}
	return o.BestId, true
}

// HasBestId returns a boolean if a field has been set.
func (o *Event) HasBestId() bool {
	if o != nil && !IsNil(o.BestId) {
		return true
	}

	return false
}

// SetBestId gets a reference to the given string and assigns it to the BestId field.
func (o *Event) SetBestId(v string) {
	o.BestId = &v
}

// GetBestLat returns the BestLat field value if set, zero value otherwise.
func (o *Event) GetBestLat() float64 {
	if o == nil || IsNil(o.BestLat) {
		var ret float64
		return ret
	}
	return *o.BestLat
}

// GetBestLatOk returns a tuple with the BestLat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetBestLatOk() (*float64, bool) {
	if o == nil || IsNil(o.BestLat) {
		return nil, false
	}
	return o.BestLat, true
}

// HasBestLat returns a boolean if a field has been set.
func (o *Event) HasBestLat() bool {
	if o != nil && !IsNil(o.BestLat) {
		return true
	}

	return false
}

// SetBestLat gets a reference to the given float64 and assigns it to the BestLat field.
func (o *Event) SetBestLat(v float64) {
	o.BestLat = &v
}

// GetBestLocation returns the BestLocation field value if set, zero value otherwise.
func (o *Event) GetBestLocation() string {
	if o == nil || IsNil(o.BestLocation) {
		var ret string
		return ret
	}
	return *o.BestLocation
}

// GetBestLocationOk returns a tuple with the BestLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetBestLocationOk() (*string, bool) {
	if o == nil || IsNil(o.BestLocation) {
		return nil, false
	}
	return o.BestLocation, true
}

// HasBestLocation returns a boolean if a field has been set.
func (o *Event) HasBestLocation() bool {
	if o != nil && !IsNil(o.BestLocation) {
		return true
	}

	return false
}

// SetBestLocation gets a reference to the given string and assigns it to the BestLocation field.
func (o *Event) SetBestLocation(v string) {
	o.BestLocation = &v
}

// GetBestLocationType returns the BestLocationType field value if set, zero value otherwise.
func (o *Event) GetBestLocationType() string {
	if o == nil || IsNil(o.BestLocationType) {
		var ret string
		return ret
	}
	return *o.BestLocationType
}

// GetBestLocationTypeOk returns a tuple with the BestLocationType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetBestLocationTypeOk() (*string, bool) {
	if o == nil || IsNil(o.BestLocationType) {
		return nil, false
	}
	return o.BestLocationType, true
}

// HasBestLocationType returns a boolean if a field has been set.
func (o *Event) HasBestLocationType() bool {
	if o != nil && !IsNil(o.BestLocationType) {
		return true
	}

	return false
}

// SetBestLocationType gets a reference to the given string and assigns it to the BestLocationType field.
func (o *Event) SetBestLocationType(v string) {
	o.BestLocationType = &v
}

// GetBestLocationWhen returns the BestLocationWhen field value if set, zero value otherwise.
func (o *Event) GetBestLocationWhen() float32 {
	if o == nil || IsNil(o.BestLocationWhen) {
		var ret float32
		return ret
	}
	return *o.BestLocationWhen
}

// GetBestLocationWhenOk returns a tuple with the BestLocationWhen field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetBestLocationWhenOk() (*float32, bool) {
	if o == nil || IsNil(o.BestLocationWhen) {
		return nil, false
	}
	return o.BestLocationWhen, true
}

// HasBestLocationWhen returns a boolean if a field has been set.
func (o *Event) HasBestLocationWhen() bool {
	if o != nil && !IsNil(o.BestLocationWhen) {
		return true
	}

	return false
}

// SetBestLocationWhen gets a reference to the given float32 and assigns it to the BestLocationWhen field.
func (o *Event) SetBestLocationWhen(v float32) {
	o.BestLocationWhen = &v
}

// GetBestLon returns the BestLon field value if set, zero value otherwise.
func (o *Event) GetBestLon() float64 {
	if o == nil || IsNil(o.BestLon) {
		var ret float64
		return ret
	}
	return *o.BestLon
}

// GetBestLonOk returns a tuple with the BestLon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetBestLonOk() (*float64, bool) {
	if o == nil || IsNil(o.BestLon) {
		return nil, false
	}
	return o.BestLon, true
}

// HasBestLon returns a boolean if a field has been set.
func (o *Event) HasBestLon() bool {
	if o != nil && !IsNil(o.BestLon) {
		return true
	}

	return false
}

// SetBestLon gets a reference to the given float64 and assigns it to the BestLon field.
func (o *Event) SetBestLon(v float64) {
	o.BestLon = &v
}

// GetBestTimezone returns the BestTimezone field value if set, zero value otherwise.
func (o *Event) GetBestTimezone() string {
	if o == nil || IsNil(o.BestTimezone) {
		var ret string
		return ret
	}
	return *o.BestTimezone
}

// GetBestTimezoneOk returns a tuple with the BestTimezone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetBestTimezoneOk() (*string, bool) {
	if o == nil || IsNil(o.BestTimezone) {
		return nil, false
	}
	return o.BestTimezone, true
}

// HasBestTimezone returns a boolean if a field has been set.
func (o *Event) HasBestTimezone() bool {
	if o != nil && !IsNil(o.BestTimezone) {
		return true
	}

	return false
}

// SetBestTimezone gets a reference to the given string and assigns it to the BestTimezone field.
func (o *Event) SetBestTimezone(v string) {
	o.BestTimezone = &v
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *Event) GetBody() map[string]interface{} {
	if o == nil || IsNil(o.Body) {
		var ret map[string]interface{}
		return ret
	}
	return o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetBodyOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Body) {
		return map[string]interface{}{}, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *Event) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given map[string]interface{} and assigns it to the Body field.
func (o *Event) SetBody(v map[string]interface{}) {
	o.Body = v
}

// GetBssid returns the Bssid field value if set, zero value otherwise.
func (o *Event) GetBssid() string {
	if o == nil || IsNil(o.Bssid) {
		var ret string
		return ret
	}
	return *o.Bssid
}

// GetBssidOk returns a tuple with the Bssid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetBssidOk() (*string, bool) {
	if o == nil || IsNil(o.Bssid) {
		return nil, false
	}
	return o.Bssid, true
}

// HasBssid returns a boolean if a field has been set.
func (o *Event) HasBssid() bool {
	if o != nil && !IsNil(o.Bssid) {
		return true
	}

	return false
}

// SetBssid gets a reference to the given string and assigns it to the Bssid field.
func (o *Event) SetBssid(v string) {
	o.Bssid = &v
}

// GetDevice returns the Device field value if set, zero value otherwise.
func (o *Event) GetDevice() string {
	if o == nil || IsNil(o.Device) {
		var ret string
		return ret
	}
	return *o.Device
}

// GetDeviceOk returns a tuple with the Device field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetDeviceOk() (*string, bool) {
	if o == nil || IsNil(o.Device) {
		return nil, false
	}
	return o.Device, true
}

// HasDevice returns a boolean if a field has been set.
func (o *Event) HasDevice() bool {
	if o != nil && !IsNil(o.Device) {
		return true
	}

	return false
}

// SetDevice gets a reference to the given string and assigns it to the Device field.
func (o *Event) SetDevice(v string) {
	o.Device = &v
}

// GetEnvironment returns the Environment field value if set, zero value otherwise.
func (o *Event) GetEnvironment() map[string]interface{} {
	if o == nil || IsNil(o.Environment) {
		var ret map[string]interface{}
		return ret
	}
	return o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetEnvironmentOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Environment) {
		return map[string]interface{}{}, false
	}
	return o.Environment, true
}

// HasEnvironment returns a boolean if a field has been set.
func (o *Event) HasEnvironment() bool {
	if o != nil && !IsNil(o.Environment) {
		return true
	}

	return false
}

// SetEnvironment gets a reference to the given map[string]interface{} and assigns it to the Environment field.
func (o *Event) SetEnvironment(v map[string]interface{}) {
	o.Environment = v
}

// GetEvent returns the Event field value if set, zero value otherwise.
func (o *Event) GetEvent() string {
	if o == nil || IsNil(o.Event) {
		var ret string
		return ret
	}
	return *o.Event
}

// GetEventOk returns a tuple with the Event field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetEventOk() (*string, bool) {
	if o == nil || IsNil(o.Event) {
		return nil, false
	}
	return o.Event, true
}

// HasEvent returns a boolean if a field has been set.
func (o *Event) HasEvent() bool {
	if o != nil && !IsNil(o.Event) {
		return true
	}

	return false
}

// SetEvent gets a reference to the given string and assigns it to the Event field.
func (o *Event) SetEvent(v string) {
	o.Event = &v
}

// GetFile returns the File field value if set, zero value otherwise.
func (o *Event) GetFile() string {
	if o == nil || IsNil(o.File) {
		var ret string
		return ret
	}
	return *o.File
}

// GetFileOk returns a tuple with the File field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetFileOk() (*string, bool) {
	if o == nil || IsNil(o.File) {
		return nil, false
	}
	return o.File, true
}

// HasFile returns a boolean if a field has been set.
func (o *Event) HasFile() bool {
	if o != nil && !IsNil(o.File) {
		return true
	}

	return false
}

// SetFile gets a reference to the given string and assigns it to the File field.
func (o *Event) SetFile(v string) {
	o.File = &v
}

// GetMoved returns the Moved field value if set, zero value otherwise.
func (o *Event) GetMoved() float32 {
	if o == nil || IsNil(o.Moved) {
		var ret float32
		return ret
	}
	return *o.Moved
}

// GetMovedOk returns a tuple with the Moved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetMovedOk() (*float32, bool) {
	if o == nil || IsNil(o.Moved) {
		return nil, false
	}
	return o.Moved, true
}

// HasMoved returns a boolean if a field has been set.
func (o *Event) HasMoved() bool {
	if o != nil && !IsNil(o.Moved) {
		return true
	}

	return false
}

// SetMoved gets a reference to the given float32 and assigns it to the Moved field.
func (o *Event) SetMoved(v float32) {
	o.Moved = &v
}

// GetNote returns the Note field value if set, zero value otherwise.
func (o *Event) GetNote() string {
	if o == nil || IsNil(o.Note) {
		var ret string
		return ret
	}
	return *o.Note
}

// GetNoteOk returns a tuple with the Note field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetNoteOk() (*string, bool) {
	if o == nil || IsNil(o.Note) {
		return nil, false
	}
	return o.Note, true
}

// HasNote returns a boolean if a field has been set.
func (o *Event) HasNote() bool {
	if o != nil && !IsNil(o.Note) {
		return true
	}

	return false
}

// SetNote gets a reference to the given string and assigns it to the Note field.
func (o *Event) SetNote(v string) {
	o.Note = &v
}

// GetOrderingCode returns the OrderingCode field value if set, zero value otherwise.
func (o *Event) GetOrderingCode() string {
	if o == nil || IsNil(o.OrderingCode) {
		var ret string
		return ret
	}
	return *o.OrderingCode
}

// GetOrderingCodeOk returns a tuple with the OrderingCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetOrderingCodeOk() (*string, bool) {
	if o == nil || IsNil(o.OrderingCode) {
		return nil, false
	}
	return o.OrderingCode, true
}

// HasOrderingCode returns a boolean if a field has been set.
func (o *Event) HasOrderingCode() bool {
	if o != nil && !IsNil(o.OrderingCode) {
		return true
	}

	return false
}

// SetOrderingCode gets a reference to the given string and assigns it to the OrderingCode field.
func (o *Event) SetOrderingCode(v string) {
	o.OrderingCode = &v
}

// GetOrientation returns the Orientation field value if set, zero value otherwise.
func (o *Event) GetOrientation() string {
	if o == nil || IsNil(o.Orientation) {
		var ret string
		return ret
	}
	return *o.Orientation
}

// GetOrientationOk returns a tuple with the Orientation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetOrientationOk() (*string, bool) {
	if o == nil || IsNil(o.Orientation) {
		return nil, false
	}
	return o.Orientation, true
}

// HasOrientation returns a boolean if a field has been set.
func (o *Event) HasOrientation() bool {
	if o != nil && !IsNil(o.Orientation) {
		return true
	}

	return false
}

// SetOrientation gets a reference to the given string and assigns it to the Orientation field.
func (o *Event) SetOrientation(v string) {
	o.Orientation = &v
}

// GetPayload returns the Payload field value if set, zero value otherwise.
func (o *Event) GetPayload() string {
	if o == nil || IsNil(o.Payload) {
		var ret string
		return ret
	}
	return *o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetPayloadOk() (*string, bool) {
	if o == nil || IsNil(o.Payload) {
		return nil, false
	}
	return o.Payload, true
}

// HasPayload returns a boolean if a field has been set.
func (o *Event) HasPayload() bool {
	if o != nil && !IsNil(o.Payload) {
		return true
	}

	return false
}

// SetPayload gets a reference to the given string and assigns it to the Payload field.
func (o *Event) SetPayload(v string) {
	o.Payload = &v
}

// GetProduct returns the Product field value if set, zero value otherwise.
func (o *Event) GetProduct() string {
	if o == nil || IsNil(o.Product) {
		var ret string
		return ret
	}
	return *o.Product
}

// GetProductOk returns a tuple with the Product field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetProductOk() (*string, bool) {
	if o == nil || IsNil(o.Product) {
		return nil, false
	}
	return o.Product, true
}

// HasProduct returns a boolean if a field has been set.
func (o *Event) HasProduct() bool {
	if o != nil && !IsNil(o.Product) {
		return true
	}

	return false
}

// SetProduct gets a reference to the given string and assigns it to the Product field.
func (o *Event) SetProduct(v string) {
	o.Product = &v
}

// GetRat returns the Rat field value if set, zero value otherwise.
func (o *Event) GetRat() string {
	if o == nil || IsNil(o.Rat) {
		var ret string
		return ret
	}
	return *o.Rat
}

// GetRatOk returns a tuple with the Rat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetRatOk() (*string, bool) {
	if o == nil || IsNil(o.Rat) {
		return nil, false
	}
	return o.Rat, true
}

// HasRat returns a boolean if a field has been set.
func (o *Event) HasRat() bool {
	if o != nil && !IsNil(o.Rat) {
		return true
	}

	return false
}

// SetRat gets a reference to the given string and assigns it to the Rat field.
func (o *Event) SetRat(v string) {
	o.Rat = &v
}

// GetReceived returns the Received field value if set, zero value otherwise.
func (o *Event) GetReceived() float64 {
	if o == nil || IsNil(o.Received) {
		var ret float64
		return ret
	}
	return *o.Received
}

// GetReceivedOk returns a tuple with the Received field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetReceivedOk() (*float64, bool) {
	if o == nil || IsNil(o.Received) {
		return nil, false
	}
	return o.Received, true
}

// HasReceived returns a boolean if a field has been set.
func (o *Event) HasReceived() bool {
	if o != nil && !IsNil(o.Received) {
		return true
	}

	return false
}

// SetReceived gets a reference to the given float64 and assigns it to the Received field.
func (o *Event) SetReceived(v float64) {
	o.Received = &v
}

// GetReq returns the Req field value if set, zero value otherwise.
func (o *Event) GetReq() string {
	if o == nil || IsNil(o.Req) {
		var ret string
		return ret
	}
	return *o.Req
}

// GetReqOk returns a tuple with the Req field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetReqOk() (*string, bool) {
	if o == nil || IsNil(o.Req) {
		return nil, false
	}
	return o.Req, true
}

// HasReq returns a boolean if a field has been set.
func (o *Event) HasReq() bool {
	if o != nil && !IsNil(o.Req) {
		return true
	}

	return false
}

// SetReq gets a reference to the given string and assigns it to the Req field.
func (o *Event) SetReq(v string) {
	o.Req = &v
}

// GetRsrp returns the Rsrp field value if set, zero value otherwise.
func (o *Event) GetRsrp() float32 {
	if o == nil || IsNil(o.Rsrp) {
		var ret float32
		return ret
	}
	return *o.Rsrp
}

// GetRsrpOk returns a tuple with the Rsrp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetRsrpOk() (*float32, bool) {
	if o == nil || IsNil(o.Rsrp) {
		return nil, false
	}
	return o.Rsrp, true
}

// HasRsrp returns a boolean if a field has been set.
func (o *Event) HasRsrp() bool {
	if o != nil && !IsNil(o.Rsrp) {
		return true
	}

	return false
}

// SetRsrp gets a reference to the given float32 and assigns it to the Rsrp field.
func (o *Event) SetRsrp(v float32) {
	o.Rsrp = &v
}

// GetRsrq returns the Rsrq field value if set, zero value otherwise.
func (o *Event) GetRsrq() float32 {
	if o == nil || IsNil(o.Rsrq) {
		var ret float32
		return ret
	}
	return *o.Rsrq
}

// GetRsrqOk returns a tuple with the Rsrq field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetRsrqOk() (*float32, bool) {
	if o == nil || IsNil(o.Rsrq) {
		return nil, false
	}
	return o.Rsrq, true
}

// HasRsrq returns a boolean if a field has been set.
func (o *Event) HasRsrq() bool {
	if o != nil && !IsNil(o.Rsrq) {
		return true
	}

	return false
}

// SetRsrq gets a reference to the given float32 and assigns it to the Rsrq field.
func (o *Event) SetRsrq(v float32) {
	o.Rsrq = &v
}

// GetRssi returns the Rssi field value if set, zero value otherwise.
func (o *Event) GetRssi() float32 {
	if o == nil || IsNil(o.Rssi) {
		var ret float32
		return ret
	}
	return *o.Rssi
}

// GetRssiOk returns a tuple with the Rssi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetRssiOk() (*float32, bool) {
	if o == nil || IsNil(o.Rssi) {
		return nil, false
	}
	return o.Rssi, true
}

// HasRssi returns a boolean if a field has been set.
func (o *Event) HasRssi() bool {
	if o != nil && !IsNil(o.Rssi) {
		return true
	}

	return false
}

// SetRssi gets a reference to the given float32 and assigns it to the Rssi field.
func (o *Event) SetRssi(v float32) {
	o.Rssi = &v
}

// GetSession returns the Session field value if set, zero value otherwise.
func (o *Event) GetSession() string {
	if o == nil || IsNil(o.Session) {
		var ret string
		return ret
	}
	return *o.Session
}

// GetSessionOk returns a tuple with the Session field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetSessionOk() (*string, bool) {
	if o == nil || IsNil(o.Session) {
		return nil, false
	}
	return o.Session, true
}

// HasSession returns a boolean if a field has been set.
func (o *Event) HasSession() bool {
	if o != nil && !IsNil(o.Session) {
		return true
	}

	return false
}

// SetSession gets a reference to the given string and assigns it to the Session field.
func (o *Event) SetSession(v string) {
	o.Session = &v
}

// GetSinr returns the Sinr field value if set, zero value otherwise.
func (o *Event) GetSinr() float32 {
	if o == nil || IsNil(o.Sinr) {
		var ret float32
		return ret
	}
	return *o.Sinr
}

// GetSinrOk returns a tuple with the Sinr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetSinrOk() (*float32, bool) {
	if o == nil || IsNil(o.Sinr) {
		return nil, false
	}
	return o.Sinr, true
}

// HasSinr returns a boolean if a field has been set.
func (o *Event) HasSinr() bool {
	if o != nil && !IsNil(o.Sinr) {
		return true
	}

	return false
}

// SetSinr gets a reference to the given float32 and assigns it to the Sinr field.
func (o *Event) SetSinr(v float32) {
	o.Sinr = &v
}

// GetSku returns the Sku field value if set, zero value otherwise.
func (o *Event) GetSku() string {
	if o == nil || IsNil(o.Sku) {
		var ret string
		return ret
	}
	return *o.Sku
}

// GetSkuOk returns a tuple with the Sku field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetSkuOk() (*string, bool) {
	if o == nil || IsNil(o.Sku) {
		return nil, false
	}
	return o.Sku, true
}

// HasSku returns a boolean if a field has been set.
func (o *Event) HasSku() bool {
	if o != nil && !IsNil(o.Sku) {
		return true
	}

	return false
}

// SetSku gets a reference to the given string and assigns it to the Sku field.
func (o *Event) SetSku(v string) {
	o.Sku = &v
}

// GetSn returns the Sn field value if set, zero value otherwise.
func (o *Event) GetSn() string {
	if o == nil || IsNil(o.Sn) {
		var ret string
		return ret
	}
	return *o.Sn
}

// GetSnOk returns a tuple with the Sn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetSnOk() (*string, bool) {
	if o == nil || IsNil(o.Sn) {
		return nil, false
	}
	return o.Sn, true
}

// HasSn returns a boolean if a field has been set.
func (o *Event) HasSn() bool {
	if o != nil && !IsNil(o.Sn) {
		return true
	}

	return false
}

// SetSn gets a reference to the given string and assigns it to the Sn field.
func (o *Event) SetSn(v string) {
	o.Sn = &v
}

// GetSsid returns the Ssid field value if set, zero value otherwise.
func (o *Event) GetSsid() string {
	if o == nil || IsNil(o.Ssid) {
		var ret string
		return ret
	}
	return *o.Ssid
}

// GetSsidOk returns a tuple with the Ssid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetSsidOk() (*string, bool) {
	if o == nil || IsNil(o.Ssid) {
		return nil, false
	}
	return o.Ssid, true
}

// HasSsid returns a boolean if a field has been set.
func (o *Event) HasSsid() bool {
	if o != nil && !IsNil(o.Ssid) {
		return true
	}

	return false
}

// SetSsid gets a reference to the given string and assigns it to the Ssid field.
func (o *Event) SetSsid(v string) {
	o.Ssid = &v
}

// GetTemp returns the Temp field value if set, zero value otherwise.
func (o *Event) GetTemp() float64 {
	if o == nil || IsNil(o.Temp) {
		var ret float64
		return ret
	}
	return *o.Temp
}

// GetTempOk returns a tuple with the Temp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetTempOk() (*float64, bool) {
	if o == nil || IsNil(o.Temp) {
		return nil, false
	}
	return o.Temp, true
}

// HasTemp returns a boolean if a field has been set.
func (o *Event) HasTemp() bool {
	if o != nil && !IsNil(o.Temp) {
		return true
	}

	return false
}

// SetTemp gets a reference to the given float64 and assigns it to the Temp field.
func (o *Event) SetTemp(v float64) {
	o.Temp = &v
}

// GetTls returns the Tls field value if set, zero value otherwise.
func (o *Event) GetTls() bool {
	if o == nil || IsNil(o.Tls) {
		var ret bool
		return ret
	}
	return *o.Tls
}

// GetTlsOk returns a tuple with the Tls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetTlsOk() (*bool, bool) {
	if o == nil || IsNil(o.Tls) {
		return nil, false
	}
	return o.Tls, true
}

// HasTls returns a boolean if a field has been set.
func (o *Event) HasTls() bool {
	if o != nil && !IsNil(o.Tls) {
		return true
	}

	return false
}

// SetTls gets a reference to the given bool and assigns it to the Tls field.
func (o *Event) SetTls(v bool) {
	o.Tls = &v
}

// GetTowerCountry returns the TowerCountry field value if set, zero value otherwise.
func (o *Event) GetTowerCountry() string {
	if o == nil || IsNil(o.TowerCountry) {
		var ret string
		return ret
	}
	return *o.TowerCountry
}

// GetTowerCountryOk returns a tuple with the TowerCountry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetTowerCountryOk() (*string, bool) {
	if o == nil || IsNil(o.TowerCountry) {
		return nil, false
	}
	return o.TowerCountry, true
}

// HasTowerCountry returns a boolean if a field has been set.
func (o *Event) HasTowerCountry() bool {
	if o != nil && !IsNil(o.TowerCountry) {
		return true
	}

	return false
}

// SetTowerCountry gets a reference to the given string and assigns it to the TowerCountry field.
func (o *Event) SetTowerCountry(v string) {
	o.TowerCountry = &v
}

// GetTowerId returns the TowerId field value if set, zero value otherwise.
func (o *Event) GetTowerId() string {
	if o == nil || IsNil(o.TowerId) {
		var ret string
		return ret
	}
	return *o.TowerId
}

// GetTowerIdOk returns a tuple with the TowerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetTowerIdOk() (*string, bool) {
	if o == nil || IsNil(o.TowerId) {
		return nil, false
	}
	return o.TowerId, true
}

// HasTowerId returns a boolean if a field has been set.
func (o *Event) HasTowerId() bool {
	if o != nil && !IsNil(o.TowerId) {
		return true
	}

	return false
}

// SetTowerId gets a reference to the given string and assigns it to the TowerId field.
func (o *Event) SetTowerId(v string) {
	o.TowerId = &v
}

// GetTowerLat returns the TowerLat field value if set, zero value otherwise.
func (o *Event) GetTowerLat() float64 {
	if o == nil || IsNil(o.TowerLat) {
		var ret float64
		return ret
	}
	return *o.TowerLat
}

// GetTowerLatOk returns a tuple with the TowerLat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetTowerLatOk() (*float64, bool) {
	if o == nil || IsNil(o.TowerLat) {
		return nil, false
	}
	return o.TowerLat, true
}

// HasTowerLat returns a boolean if a field has been set.
func (o *Event) HasTowerLat() bool {
	if o != nil && !IsNil(o.TowerLat) {
		return true
	}

	return false
}

// SetTowerLat gets a reference to the given float64 and assigns it to the TowerLat field.
func (o *Event) SetTowerLat(v float64) {
	o.TowerLat = &v
}

// GetTowerLocation returns the TowerLocation field value if set, zero value otherwise.
func (o *Event) GetTowerLocation() string {
	if o == nil || IsNil(o.TowerLocation) {
		var ret string
		return ret
	}
	return *o.TowerLocation
}

// GetTowerLocationOk returns a tuple with the TowerLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetTowerLocationOk() (*string, bool) {
	if o == nil || IsNil(o.TowerLocation) {
		return nil, false
	}
	return o.TowerLocation, true
}

// HasTowerLocation returns a boolean if a field has been set.
func (o *Event) HasTowerLocation() bool {
	if o != nil && !IsNil(o.TowerLocation) {
		return true
	}

	return false
}

// SetTowerLocation gets a reference to the given string and assigns it to the TowerLocation field.
func (o *Event) SetTowerLocation(v string) {
	o.TowerLocation = &v
}

// GetTowerLon returns the TowerLon field value if set, zero value otherwise.
func (o *Event) GetTowerLon() float64 {
	if o == nil || IsNil(o.TowerLon) {
		var ret float64
		return ret
	}
	return *o.TowerLon
}

// GetTowerLonOk returns a tuple with the TowerLon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetTowerLonOk() (*float64, bool) {
	if o == nil || IsNil(o.TowerLon) {
		return nil, false
	}
	return o.TowerLon, true
}

// HasTowerLon returns a boolean if a field has been set.
func (o *Event) HasTowerLon() bool {
	if o != nil && !IsNil(o.TowerLon) {
		return true
	}

	return false
}

// SetTowerLon gets a reference to the given float64 and assigns it to the TowerLon field.
func (o *Event) SetTowerLon(v float64) {
	o.TowerLon = &v
}

// GetTowerTimezone returns the TowerTimezone field value if set, zero value otherwise.
func (o *Event) GetTowerTimezone() string {
	if o == nil || IsNil(o.TowerTimezone) {
		var ret string
		return ret
	}
	return *o.TowerTimezone
}

// GetTowerTimezoneOk returns a tuple with the TowerTimezone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetTowerTimezoneOk() (*string, bool) {
	if o == nil || IsNil(o.TowerTimezone) {
		return nil, false
	}
	return o.TowerTimezone, true
}

// HasTowerTimezone returns a boolean if a field has been set.
func (o *Event) HasTowerTimezone() bool {
	if o != nil && !IsNil(o.TowerTimezone) {
		return true
	}

	return false
}

// SetTowerTimezone gets a reference to the given string and assigns it to the TowerTimezone field.
func (o *Event) SetTowerTimezone(v string) {
	o.TowerTimezone = &v
}

// GetTowerWhen returns the TowerWhen field value if set, zero value otherwise.
func (o *Event) GetTowerWhen() float32 {
	if o == nil || IsNil(o.TowerWhen) {
		var ret float32
		return ret
	}
	return *o.TowerWhen
}

// GetTowerWhenOk returns a tuple with the TowerWhen field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetTowerWhenOk() (*float32, bool) {
	if o == nil || IsNil(o.TowerWhen) {
		return nil, false
	}
	return o.TowerWhen, true
}

// HasTowerWhen returns a boolean if a field has been set.
func (o *Event) HasTowerWhen() bool {
	if o != nil && !IsNil(o.TowerWhen) {
		return true
	}

	return false
}

// SetTowerWhen gets a reference to the given float32 and assigns it to the TowerWhen field.
func (o *Event) SetTowerWhen(v float32) {
	o.TowerWhen = &v
}

// GetTransport returns the Transport field value if set, zero value otherwise.
func (o *Event) GetTransport() string {
	if o == nil || IsNil(o.Transport) {
		var ret string
		return ret
	}
	return *o.Transport
}

// GetTransportOk returns a tuple with the Transport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetTransportOk() (*string, bool) {
	if o == nil || IsNil(o.Transport) {
		return nil, false
	}
	return o.Transport, true
}

// HasTransport returns a boolean if a field has been set.
func (o *Event) HasTransport() bool {
	if o != nil && !IsNil(o.Transport) {
		return true
	}

	return false
}

// SetTransport gets a reference to the given string and assigns it to the Transport field.
func (o *Event) SetTransport(v string) {
	o.Transport = &v
}

// GetTriCountry returns the TriCountry field value if set, zero value otherwise.
func (o *Event) GetTriCountry() string {
	if o == nil || IsNil(o.TriCountry) {
		var ret string
		return ret
	}
	return *o.TriCountry
}

// GetTriCountryOk returns a tuple with the TriCountry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetTriCountryOk() (*string, bool) {
	if o == nil || IsNil(o.TriCountry) {
		return nil, false
	}
	return o.TriCountry, true
}

// HasTriCountry returns a boolean if a field has been set.
func (o *Event) HasTriCountry() bool {
	if o != nil && !IsNil(o.TriCountry) {
		return true
	}

	return false
}

// SetTriCountry gets a reference to the given string and assigns it to the TriCountry field.
func (o *Event) SetTriCountry(v string) {
	o.TriCountry = &v
}

// GetTriLat returns the TriLat field value if set, zero value otherwise.
func (o *Event) GetTriLat() float64 {
	if o == nil || IsNil(o.TriLat) {
		var ret float64
		return ret
	}
	return *o.TriLat
}

// GetTriLatOk returns a tuple with the TriLat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetTriLatOk() (*float64, bool) {
	if o == nil || IsNil(o.TriLat) {
		return nil, false
	}
	return o.TriLat, true
}

// HasTriLat returns a boolean if a field has been set.
func (o *Event) HasTriLat() bool {
	if o != nil && !IsNil(o.TriLat) {
		return true
	}

	return false
}

// SetTriLat gets a reference to the given float64 and assigns it to the TriLat field.
func (o *Event) SetTriLat(v float64) {
	o.TriLat = &v
}

// GetTriLocation returns the TriLocation field value if set, zero value otherwise.
func (o *Event) GetTriLocation() string {
	if o == nil || IsNil(o.TriLocation) {
		var ret string
		return ret
	}
	return *o.TriLocation
}

// GetTriLocationOk returns a tuple with the TriLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetTriLocationOk() (*string, bool) {
	if o == nil || IsNil(o.TriLocation) {
		return nil, false
	}
	return o.TriLocation, true
}

// HasTriLocation returns a boolean if a field has been set.
func (o *Event) HasTriLocation() bool {
	if o != nil && !IsNil(o.TriLocation) {
		return true
	}

	return false
}

// SetTriLocation gets a reference to the given string and assigns it to the TriLocation field.
func (o *Event) SetTriLocation(v string) {
	o.TriLocation = &v
}

// GetTriLon returns the TriLon field value if set, zero value otherwise.
func (o *Event) GetTriLon() float64 {
	if o == nil || IsNil(o.TriLon) {
		var ret float64
		return ret
	}
	return *o.TriLon
}

// GetTriLonOk returns a tuple with the TriLon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetTriLonOk() (*float64, bool) {
	if o == nil || IsNil(o.TriLon) {
		return nil, false
	}
	return o.TriLon, true
}

// HasTriLon returns a boolean if a field has been set.
func (o *Event) HasTriLon() bool {
	if o != nil && !IsNil(o.TriLon) {
		return true
	}

	return false
}

// SetTriLon gets a reference to the given float64 and assigns it to the TriLon field.
func (o *Event) SetTriLon(v float64) {
	o.TriLon = &v
}

// GetTriPoints returns the TriPoints field value if set, zero value otherwise.
func (o *Event) GetTriPoints() float32 {
	if o == nil || IsNil(o.TriPoints) {
		var ret float32
		return ret
	}
	return *o.TriPoints
}

// GetTriPointsOk returns a tuple with the TriPoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetTriPointsOk() (*float32, bool) {
	if o == nil || IsNil(o.TriPoints) {
		return nil, false
	}
	return o.TriPoints, true
}

// HasTriPoints returns a boolean if a field has been set.
func (o *Event) HasTriPoints() bool {
	if o != nil && !IsNil(o.TriPoints) {
		return true
	}

	return false
}

// SetTriPoints gets a reference to the given float32 and assigns it to the TriPoints field.
func (o *Event) SetTriPoints(v float32) {
	o.TriPoints = &v
}

// GetTriTimezone returns the TriTimezone field value if set, zero value otherwise.
func (o *Event) GetTriTimezone() string {
	if o == nil || IsNil(o.TriTimezone) {
		var ret string
		return ret
	}
	return *o.TriTimezone
}

// GetTriTimezoneOk returns a tuple with the TriTimezone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetTriTimezoneOk() (*string, bool) {
	if o == nil || IsNil(o.TriTimezone) {
		return nil, false
	}
	return o.TriTimezone, true
}

// HasTriTimezone returns a boolean if a field has been set.
func (o *Event) HasTriTimezone() bool {
	if o != nil && !IsNil(o.TriTimezone) {
		return true
	}

	return false
}

// SetTriTimezone gets a reference to the given string and assigns it to the TriTimezone field.
func (o *Event) SetTriTimezone(v string) {
	o.TriTimezone = &v
}

// GetTriWhen returns the TriWhen field value if set, zero value otherwise.
func (o *Event) GetTriWhen() float32 {
	if o == nil || IsNil(o.TriWhen) {
		var ret float32
		return ret
	}
	return *o.TriWhen
}

// GetTriWhenOk returns a tuple with the TriWhen field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetTriWhenOk() (*float32, bool) {
	if o == nil || IsNil(o.TriWhen) {
		return nil, false
	}
	return o.TriWhen, true
}

// HasTriWhen returns a boolean if a field has been set.
func (o *Event) HasTriWhen() bool {
	if o != nil && !IsNil(o.TriWhen) {
		return true
	}

	return false
}

// SetTriWhen gets a reference to the given float32 and assigns it to the TriWhen field.
func (o *Event) SetTriWhen(v float32) {
	o.TriWhen = &v
}

// GetUpdates returns the Updates field value if set, zero value otherwise.
func (o *Event) GetUpdates() float32 {
	if o == nil || IsNil(o.Updates) {
		var ret float32
		return ret
	}
	return *o.Updates
}

// GetUpdatesOk returns a tuple with the Updates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetUpdatesOk() (*float32, bool) {
	if o == nil || IsNil(o.Updates) {
		return nil, false
	}
	return o.Updates, true
}

// HasUpdates returns a boolean if a field has been set.
func (o *Event) HasUpdates() bool {
	if o != nil && !IsNil(o.Updates) {
		return true
	}

	return false
}

// SetUpdates gets a reference to the given float32 and assigns it to the Updates field.
func (o *Event) SetUpdates(v float32) {
	o.Updates = &v
}

// GetVoltage returns the Voltage field value if set, zero value otherwise.
func (o *Event) GetVoltage() float64 {
	if o == nil || IsNil(o.Voltage) {
		var ret float64
		return ret
	}
	return *o.Voltage
}

// GetVoltageOk returns a tuple with the Voltage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetVoltageOk() (*float64, bool) {
	if o == nil || IsNil(o.Voltage) {
		return nil, false
	}
	return o.Voltage, true
}

// HasVoltage returns a boolean if a field has been set.
func (o *Event) HasVoltage() bool {
	if o != nil && !IsNil(o.Voltage) {
		return true
	}

	return false
}

// SetVoltage gets a reference to the given float64 and assigns it to the Voltage field.
func (o *Event) SetVoltage(v float64) {
	o.Voltage = &v
}

// GetWhen returns the When field value if set, zero value otherwise.
func (o *Event) GetWhen() float32 {
	if o == nil || IsNil(o.When) {
		var ret float32
		return ret
	}
	return *o.When
}

// GetWhenOk returns a tuple with the When field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetWhenOk() (*float32, bool) {
	if o == nil || IsNil(o.When) {
		return nil, false
	}
	return o.When, true
}

// HasWhen returns a boolean if a field has been set.
func (o *Event) HasWhen() bool {
	if o != nil && !IsNil(o.When) {
		return true
	}

	return false
}

// SetWhen gets a reference to the given float32 and assigns it to the When field.
func (o *Event) SetWhen(v float32) {
	o.When = &v
}

// GetWhereCountry returns the WhereCountry field value if set, zero value otherwise.
func (o *Event) GetWhereCountry() string {
	if o == nil || IsNil(o.WhereCountry) {
		var ret string
		return ret
	}
	return *o.WhereCountry
}

// GetWhereCountryOk returns a tuple with the WhereCountry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetWhereCountryOk() (*string, bool) {
	if o == nil || IsNil(o.WhereCountry) {
		return nil, false
	}
	return o.WhereCountry, true
}

// HasWhereCountry returns a boolean if a field has been set.
func (o *Event) HasWhereCountry() bool {
	if o != nil && !IsNil(o.WhereCountry) {
		return true
	}

	return false
}

// SetWhereCountry gets a reference to the given string and assigns it to the WhereCountry field.
func (o *Event) SetWhereCountry(v string) {
	o.WhereCountry = &v
}

// GetWhereLat returns the WhereLat field value if set, zero value otherwise.
func (o *Event) GetWhereLat() float64 {
	if o == nil || IsNil(o.WhereLat) {
		var ret float64
		return ret
	}
	return *o.WhereLat
}

// GetWhereLatOk returns a tuple with the WhereLat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetWhereLatOk() (*float64, bool) {
	if o == nil || IsNil(o.WhereLat) {
		return nil, false
	}
	return o.WhereLat, true
}

// HasWhereLat returns a boolean if a field has been set.
func (o *Event) HasWhereLat() bool {
	if o != nil && !IsNil(o.WhereLat) {
		return true
	}

	return false
}

// SetWhereLat gets a reference to the given float64 and assigns it to the WhereLat field.
func (o *Event) SetWhereLat(v float64) {
	o.WhereLat = &v
}

// GetWhereLocation returns the WhereLocation field value if set, zero value otherwise.
func (o *Event) GetWhereLocation() string {
	if o == nil || IsNil(o.WhereLocation) {
		var ret string
		return ret
	}
	return *o.WhereLocation
}

// GetWhereLocationOk returns a tuple with the WhereLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetWhereLocationOk() (*string, bool) {
	if o == nil || IsNil(o.WhereLocation) {
		return nil, false
	}
	return o.WhereLocation, true
}

// HasWhereLocation returns a boolean if a field has been set.
func (o *Event) HasWhereLocation() bool {
	if o != nil && !IsNil(o.WhereLocation) {
		return true
	}

	return false
}

// SetWhereLocation gets a reference to the given string and assigns it to the WhereLocation field.
func (o *Event) SetWhereLocation(v string) {
	o.WhereLocation = &v
}

// GetWhereLon returns the WhereLon field value if set, zero value otherwise.
func (o *Event) GetWhereLon() float64 {
	if o == nil || IsNil(o.WhereLon) {
		var ret float64
		return ret
	}
	return *o.WhereLon
}

// GetWhereLonOk returns a tuple with the WhereLon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetWhereLonOk() (*float64, bool) {
	if o == nil || IsNil(o.WhereLon) {
		return nil, false
	}
	return o.WhereLon, true
}

// HasWhereLon returns a boolean if a field has been set.
func (o *Event) HasWhereLon() bool {
	if o != nil && !IsNil(o.WhereLon) {
		return true
	}

	return false
}

// SetWhereLon gets a reference to the given float64 and assigns it to the WhereLon field.
func (o *Event) SetWhereLon(v float64) {
	o.WhereLon = &v
}

// GetWhereOlc returns the WhereOlc field value if set, zero value otherwise.
func (o *Event) GetWhereOlc() string {
	if o == nil || IsNil(o.WhereOlc) {
		var ret string
		return ret
	}
	return *o.WhereOlc
}

// GetWhereOlcOk returns a tuple with the WhereOlc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetWhereOlcOk() (*string, bool) {
	if o == nil || IsNil(o.WhereOlc) {
		return nil, false
	}
	return o.WhereOlc, true
}

// HasWhereOlc returns a boolean if a field has been set.
func (o *Event) HasWhereOlc() bool {
	if o != nil && !IsNil(o.WhereOlc) {
		return true
	}

	return false
}

// SetWhereOlc gets a reference to the given string and assigns it to the WhereOlc field.
func (o *Event) SetWhereOlc(v string) {
	o.WhereOlc = &v
}

// GetWhereTimezone returns the WhereTimezone field value if set, zero value otherwise.
func (o *Event) GetWhereTimezone() string {
	if o == nil || IsNil(o.WhereTimezone) {
		var ret string
		return ret
	}
	return *o.WhereTimezone
}

// GetWhereTimezoneOk returns a tuple with the WhereTimezone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetWhereTimezoneOk() (*string, bool) {
	if o == nil || IsNil(o.WhereTimezone) {
		return nil, false
	}
	return o.WhereTimezone, true
}

// HasWhereTimezone returns a boolean if a field has been set.
func (o *Event) HasWhereTimezone() bool {
	if o != nil && !IsNil(o.WhereTimezone) {
		return true
	}

	return false
}

// SetWhereTimezone gets a reference to the given string and assigns it to the WhereTimezone field.
func (o *Event) SetWhereTimezone(v string) {
	o.WhereTimezone = &v
}

// GetWhereWhen returns the WhereWhen field value if set, zero value otherwise.
func (o *Event) GetWhereWhen() float32 {
	if o == nil || IsNil(o.WhereWhen) {
		var ret float32
		return ret
	}
	return *o.WhereWhen
}

// GetWhereWhenOk returns a tuple with the WhereWhen field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetWhereWhenOk() (*float32, bool) {
	if o == nil || IsNil(o.WhereWhen) {
		return nil, false
	}
	return o.WhereWhen, true
}

// HasWhereWhen returns a boolean if a field has been set.
func (o *Event) HasWhereWhen() bool {
	if o != nil && !IsNil(o.WhereWhen) {
		return true
	}

	return false
}

// SetWhereWhen gets a reference to the given float32 and assigns it to the WhereWhen field.
func (o *Event) SetWhereWhen(v float32) {
	o.WhereWhen = &v
}

func (o Event) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Event) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.App) {
		toSerialize["app"] = o.App
	}
	if !IsNil(o.Bars) {
		toSerialize["bars"] = o.Bars
	}
	if !IsNil(o.BestCountry) {
		toSerialize["best_country"] = o.BestCountry
	}
	if !IsNil(o.BestId) {
		toSerialize["best_id"] = o.BestId
	}
	if !IsNil(o.BestLat) {
		toSerialize["best_lat"] = o.BestLat
	}
	if !IsNil(o.BestLocation) {
		toSerialize["best_location"] = o.BestLocation
	}
	if !IsNil(o.BestLocationType) {
		toSerialize["best_location_type"] = o.BestLocationType
	}
	if !IsNil(o.BestLocationWhen) {
		toSerialize["best_location_when"] = o.BestLocationWhen
	}
	if !IsNil(o.BestLon) {
		toSerialize["best_lon"] = o.BestLon
	}
	if !IsNil(o.BestTimezone) {
		toSerialize["best_timezone"] = o.BestTimezone
	}
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	if !IsNil(o.Bssid) {
		toSerialize["bssid"] = o.Bssid
	}
	if !IsNil(o.Device) {
		toSerialize["device"] = o.Device
	}
	if !IsNil(o.Environment) {
		toSerialize["environment"] = o.Environment
	}
	if !IsNil(o.Event) {
		toSerialize["event"] = o.Event
	}
	if !IsNil(o.File) {
		toSerialize["file"] = o.File
	}
	if !IsNil(o.Moved) {
		toSerialize["moved"] = o.Moved
	}
	if !IsNil(o.Note) {
		toSerialize["note"] = o.Note
	}
	if !IsNil(o.OrderingCode) {
		toSerialize["ordering_code"] = o.OrderingCode
	}
	if !IsNil(o.Orientation) {
		toSerialize["orientation"] = o.Orientation
	}
	if !IsNil(o.Payload) {
		toSerialize["payload"] = o.Payload
	}
	if !IsNil(o.Product) {
		toSerialize["product"] = o.Product
	}
	if !IsNil(o.Rat) {
		toSerialize["rat"] = o.Rat
	}
	if !IsNil(o.Received) {
		toSerialize["received"] = o.Received
	}
	if !IsNil(o.Req) {
		toSerialize["req"] = o.Req
	}
	if !IsNil(o.Rsrp) {
		toSerialize["rsrp"] = o.Rsrp
	}
	if !IsNil(o.Rsrq) {
		toSerialize["rsrq"] = o.Rsrq
	}
	if !IsNil(o.Rssi) {
		toSerialize["rssi"] = o.Rssi
	}
	if !IsNil(o.Session) {
		toSerialize["session"] = o.Session
	}
	if !IsNil(o.Sinr) {
		toSerialize["sinr"] = o.Sinr
	}
	if !IsNil(o.Sku) {
		toSerialize["sku"] = o.Sku
	}
	if !IsNil(o.Sn) {
		toSerialize["sn"] = o.Sn
	}
	if !IsNil(o.Ssid) {
		toSerialize["ssid"] = o.Ssid
	}
	if !IsNil(o.Temp) {
		toSerialize["temp"] = o.Temp
	}
	if !IsNil(o.Tls) {
		toSerialize["tls"] = o.Tls
	}
	if !IsNil(o.TowerCountry) {
		toSerialize["tower_country"] = o.TowerCountry
	}
	if !IsNil(o.TowerId) {
		toSerialize["tower_id"] = o.TowerId
	}
	if !IsNil(o.TowerLat) {
		toSerialize["tower_lat"] = o.TowerLat
	}
	if !IsNil(o.TowerLocation) {
		toSerialize["tower_location"] = o.TowerLocation
	}
	if !IsNil(o.TowerLon) {
		toSerialize["tower_lon"] = o.TowerLon
	}
	if !IsNil(o.TowerTimezone) {
		toSerialize["tower_timezone"] = o.TowerTimezone
	}
	if !IsNil(o.TowerWhen) {
		toSerialize["tower_when"] = o.TowerWhen
	}
	if !IsNil(o.Transport) {
		toSerialize["transport"] = o.Transport
	}
	if !IsNil(o.TriCountry) {
		toSerialize["tri_country"] = o.TriCountry
	}
	if !IsNil(o.TriLat) {
		toSerialize["tri_lat"] = o.TriLat
	}
	if !IsNil(o.TriLocation) {
		toSerialize["tri_location"] = o.TriLocation
	}
	if !IsNil(o.TriLon) {
		toSerialize["tri_lon"] = o.TriLon
	}
	if !IsNil(o.TriPoints) {
		toSerialize["tri_points"] = o.TriPoints
	}
	if !IsNil(o.TriTimezone) {
		toSerialize["tri_timezone"] = o.TriTimezone
	}
	if !IsNil(o.TriWhen) {
		toSerialize["tri_when"] = o.TriWhen
	}
	if !IsNil(o.Updates) {
		toSerialize["updates"] = o.Updates
	}
	if !IsNil(o.Voltage) {
		toSerialize["voltage"] = o.Voltage
	}
	if !IsNil(o.When) {
		toSerialize["when"] = o.When
	}
	if !IsNil(o.WhereCountry) {
		toSerialize["where_country"] = o.WhereCountry
	}
	if !IsNil(o.WhereLat) {
		toSerialize["where_lat"] = o.WhereLat
	}
	if !IsNil(o.WhereLocation) {
		toSerialize["where_location"] = o.WhereLocation
	}
	if !IsNil(o.WhereLon) {
		toSerialize["where_lon"] = o.WhereLon
	}
	if !IsNil(o.WhereOlc) {
		toSerialize["where_olc"] = o.WhereOlc
	}
	if !IsNil(o.WhereTimezone) {
		toSerialize["where_timezone"] = o.WhereTimezone
	}
	if !IsNil(o.WhereWhen) {
		toSerialize["where_when"] = o.WhereWhen
	}
	return toSerialize, nil
}

type NullableEvent struct {
	value *Event
	isSet bool
}

func (v NullableEvent) Get() *Event {
	return v.value
}

func (v *NullableEvent) Set(val *Event) {
	v.value = val
	v.isSet = true
}

func (v NullableEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEvent(val *Event) *NullableEvent {
	return &NullableEvent{value: val, isSet: true}
}

func (v NullableEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
