/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"encoding/json"
)

// checks if the BatchJobRequests type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchJobRequests{}

// BatchJobRequests Operations to apply to a device
type BatchJobRequests struct {
	Comment *string `json:"comment,omitempty"`
	// Disable connectivity assurance for the device
	ConnectivityAssuranceDisable *bool `json:"connectivity_assurance_disable,omitempty"`
	// Enable connectivity assurance for the device
	ConnectivityAssuranceEnable *bool `json:"connectivity_assurance_enable,omitempty"`
	// Disable the device
	Disable *bool `json:"disable,omitempty"`
	// Enable the device
	Enable *bool `json:"enable,omitempty"`
	// Fleet UIDs to assign to the device if it has no fleets
	FleetsToDefault []string `json:"fleets_to_default,omitempty"`
	// Fleet UIDs to add the device to
	FleetsToJoin []string `json:"fleets_to_join,omitempty"`
	// Fleet UIDs to remove the device from
	FleetsToLeave []string `json:"fleets_to_leave,omitempty"`
	// Product UID to provision the device with if not already provisioned
	ProvisionProduct *string `json:"provision_product,omitempty"`
	// Set the device serial number only if not already set
	SnToDefault *string `json:"sn_to_default,omitempty"`
	// Set the device serial number (\"-\" to clear)
	SnToSet *string `json:"sn_to_set,omitempty"`
	// Environment variables to set only if not already set
	VarsToDefault *map[string]string `json:"vars_to_default,omitempty"`
	// Environment variables to set (use \"-\" as value to clear)
	VarsToSet            *map[string]string `json:"vars_to_set,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BatchJobRequests BatchJobRequests

// NewBatchJobRequests instantiates a new BatchJobRequests object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchJobRequests() *BatchJobRequests {
	this := BatchJobRequests{}
	return &this
}

// NewBatchJobRequestsWithDefaults instantiates a new BatchJobRequests object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchJobRequestsWithDefaults() *BatchJobRequests {
	this := BatchJobRequests{}
	return &this
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *BatchJobRequests) GetComment() string {
	if o == nil || IsNil(o.Comment) {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchJobRequests) GetCommentOk() (*string, bool) {
	if o == nil || IsNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *BatchJobRequests) HasComment() bool {
	if o != nil && !IsNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *BatchJobRequests) SetComment(v string) {
	o.Comment = &v
}

// GetConnectivityAssuranceDisable returns the ConnectivityAssuranceDisable field value if set, zero value otherwise.
func (o *BatchJobRequests) GetConnectivityAssuranceDisable() bool {
	if o == nil || IsNil(o.ConnectivityAssuranceDisable) {
		var ret bool
		return ret
	}
	return *o.ConnectivityAssuranceDisable
}

// GetConnectivityAssuranceDisableOk returns a tuple with the ConnectivityAssuranceDisable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchJobRequests) GetConnectivityAssuranceDisableOk() (*bool, bool) {
	if o == nil || IsNil(o.ConnectivityAssuranceDisable) {
		return nil, false
	}
	return o.ConnectivityAssuranceDisable, true
}

// HasConnectivityAssuranceDisable returns a boolean if a field has been set.
func (o *BatchJobRequests) HasConnectivityAssuranceDisable() bool {
	if o != nil && !IsNil(o.ConnectivityAssuranceDisable) {
		return true
	}

	return false
}

// SetConnectivityAssuranceDisable gets a reference to the given bool and assigns it to the ConnectivityAssuranceDisable field.
func (o *BatchJobRequests) SetConnectivityAssuranceDisable(v bool) {
	o.ConnectivityAssuranceDisable = &v
}

// GetConnectivityAssuranceEnable returns the ConnectivityAssuranceEnable field value if set, zero value otherwise.
func (o *BatchJobRequests) GetConnectivityAssuranceEnable() bool {
	if o == nil || IsNil(o.ConnectivityAssuranceEnable) {
		var ret bool
		return ret
	}
	return *o.ConnectivityAssuranceEnable
}

// GetConnectivityAssuranceEnableOk returns a tuple with the ConnectivityAssuranceEnable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchJobRequests) GetConnectivityAssuranceEnableOk() (*bool, bool) {
	if o == nil || IsNil(o.ConnectivityAssuranceEnable) {
		return nil, false
	}
	return o.ConnectivityAssuranceEnable, true
}

// HasConnectivityAssuranceEnable returns a boolean if a field has been set.
func (o *BatchJobRequests) HasConnectivityAssuranceEnable() bool {
	if o != nil && !IsNil(o.ConnectivityAssuranceEnable) {
		return true
	}

	return false
}

// SetConnectivityAssuranceEnable gets a reference to the given bool and assigns it to the ConnectivityAssuranceEnable field.
func (o *BatchJobRequests) SetConnectivityAssuranceEnable(v bool) {
	o.ConnectivityAssuranceEnable = &v
}

// GetDisable returns the Disable field value if set, zero value otherwise.
func (o *BatchJobRequests) GetDisable() bool {
	if o == nil || IsNil(o.Disable) {
		var ret bool
		return ret
	}
	return *o.Disable
}

// GetDisableOk returns a tuple with the Disable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchJobRequests) GetDisableOk() (*bool, bool) {
	if o == nil || IsNil(o.Disable) {
		return nil, false
	}
	return o.Disable, true
}

// HasDisable returns a boolean if a field has been set.
func (o *BatchJobRequests) HasDisable() bool {
	if o != nil && !IsNil(o.Disable) {
		return true
	}

	return false
}

// SetDisable gets a reference to the given bool and assigns it to the Disable field.
func (o *BatchJobRequests) SetDisable(v bool) {
	o.Disable = &v
}

// GetEnable returns the Enable field value if set, zero value otherwise.
func (o *BatchJobRequests) GetEnable() bool {
	if o == nil || IsNil(o.Enable) {
		var ret bool
		return ret
	}
	return *o.Enable
}

// GetEnableOk returns a tuple with the Enable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchJobRequests) GetEnableOk() (*bool, bool) {
	if o == nil || IsNil(o.Enable) {
		return nil, false
	}
	return o.Enable, true
}

// HasEnable returns a boolean if a field has been set.
func (o *BatchJobRequests) HasEnable() bool {
	if o != nil && !IsNil(o.Enable) {
		return true
	}

	return false
}

// SetEnable gets a reference to the given bool and assigns it to the Enable field.
func (o *BatchJobRequests) SetEnable(v bool) {
	o.Enable = &v
}

// GetFleetsToDefault returns the FleetsToDefault field value if set, zero value otherwise.
func (o *BatchJobRequests) GetFleetsToDefault() []string {
	if o == nil || IsNil(o.FleetsToDefault) {
		var ret []string
		return ret
	}
	return o.FleetsToDefault
}

// GetFleetsToDefaultOk returns a tuple with the FleetsToDefault field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchJobRequests) GetFleetsToDefaultOk() ([]string, bool) {
	if o == nil || IsNil(o.FleetsToDefault) {
		return nil, false
	}
	return o.FleetsToDefault, true
}

// HasFleetsToDefault returns a boolean if a field has been set.
func (o *BatchJobRequests) HasFleetsToDefault() bool {
	if o != nil && !IsNil(o.FleetsToDefault) {
		return true
	}

	return false
}

// SetFleetsToDefault gets a reference to the given []string and assigns it to the FleetsToDefault field.
func (o *BatchJobRequests) SetFleetsToDefault(v []string) {
	o.FleetsToDefault = v
}

// GetFleetsToJoin returns the FleetsToJoin field value if set, zero value otherwise.
func (o *BatchJobRequests) GetFleetsToJoin() []string {
	if o == nil || IsNil(o.FleetsToJoin) {
		var ret []string
		return ret
	}
	return o.FleetsToJoin
}

// GetFleetsToJoinOk returns a tuple with the FleetsToJoin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchJobRequests) GetFleetsToJoinOk() ([]string, bool) {
	if o == nil || IsNil(o.FleetsToJoin) {
		return nil, false
	}
	return o.FleetsToJoin, true
}

// HasFleetsToJoin returns a boolean if a field has been set.
func (o *BatchJobRequests) HasFleetsToJoin() bool {
	if o != nil && !IsNil(o.FleetsToJoin) {
		return true
	}

	return false
}

// SetFleetsToJoin gets a reference to the given []string and assigns it to the FleetsToJoin field.
func (o *BatchJobRequests) SetFleetsToJoin(v []string) {
	o.FleetsToJoin = v
}

// GetFleetsToLeave returns the FleetsToLeave field value if set, zero value otherwise.
func (o *BatchJobRequests) GetFleetsToLeave() []string {
	if o == nil || IsNil(o.FleetsToLeave) {
		var ret []string
		return ret
	}
	return o.FleetsToLeave
}

// GetFleetsToLeaveOk returns a tuple with the FleetsToLeave field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchJobRequests) GetFleetsToLeaveOk() ([]string, bool) {
	if o == nil || IsNil(o.FleetsToLeave) {
		return nil, false
	}
	return o.FleetsToLeave, true
}

// HasFleetsToLeave returns a boolean if a field has been set.
func (o *BatchJobRequests) HasFleetsToLeave() bool {
	if o != nil && !IsNil(o.FleetsToLeave) {
		return true
	}

	return false
}

// SetFleetsToLeave gets a reference to the given []string and assigns it to the FleetsToLeave field.
func (o *BatchJobRequests) SetFleetsToLeave(v []string) {
	o.FleetsToLeave = v
}

// GetProvisionProduct returns the ProvisionProduct field value if set, zero value otherwise.
func (o *BatchJobRequests) GetProvisionProduct() string {
	if o == nil || IsNil(o.ProvisionProduct) {
		var ret string
		return ret
	}
	return *o.ProvisionProduct
}

// GetProvisionProductOk returns a tuple with the ProvisionProduct field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchJobRequests) GetProvisionProductOk() (*string, bool) {
	if o == nil || IsNil(o.ProvisionProduct) {
		return nil, false
	}
	return o.ProvisionProduct, true
}

// HasProvisionProduct returns a boolean if a field has been set.
func (o *BatchJobRequests) HasProvisionProduct() bool {
	if o != nil && !IsNil(o.ProvisionProduct) {
		return true
	}

	return false
}

// SetProvisionProduct gets a reference to the given string and assigns it to the ProvisionProduct field.
func (o *BatchJobRequests) SetProvisionProduct(v string) {
	o.ProvisionProduct = &v
}

// GetSnToDefault returns the SnToDefault field value if set, zero value otherwise.
func (o *BatchJobRequests) GetSnToDefault() string {
	if o == nil || IsNil(o.SnToDefault) {
		var ret string
		return ret
	}
	return *o.SnToDefault
}

// GetSnToDefaultOk returns a tuple with the SnToDefault field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchJobRequests) GetSnToDefaultOk() (*string, bool) {
	if o == nil || IsNil(o.SnToDefault) {
		return nil, false
	}
	return o.SnToDefault, true
}

// HasSnToDefault returns a boolean if a field has been set.
func (o *BatchJobRequests) HasSnToDefault() bool {
	if o != nil && !IsNil(o.SnToDefault) {
		return true
	}

	return false
}

// SetSnToDefault gets a reference to the given string and assigns it to the SnToDefault field.
func (o *BatchJobRequests) SetSnToDefault(v string) {
	o.SnToDefault = &v
}

// GetSnToSet returns the SnToSet field value if set, zero value otherwise.
func (o *BatchJobRequests) GetSnToSet() string {
	if o == nil || IsNil(o.SnToSet) {
		var ret string
		return ret
	}
	return *o.SnToSet
}

// GetSnToSetOk returns a tuple with the SnToSet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchJobRequests) GetSnToSetOk() (*string, bool) {
	if o == nil || IsNil(o.SnToSet) {
		return nil, false
	}
	return o.SnToSet, true
}

// HasSnToSet returns a boolean if a field has been set.
func (o *BatchJobRequests) HasSnToSet() bool {
	if o != nil && !IsNil(o.SnToSet) {
		return true
	}

	return false
}

// SetSnToSet gets a reference to the given string and assigns it to the SnToSet field.
func (o *BatchJobRequests) SetSnToSet(v string) {
	o.SnToSet = &v
}

// GetVarsToDefault returns the VarsToDefault field value if set, zero value otherwise.
func (o *BatchJobRequests) GetVarsToDefault() map[string]string {
	if o == nil || IsNil(o.VarsToDefault) {
		var ret map[string]string
		return ret
	}
	return *o.VarsToDefault
}

// GetVarsToDefaultOk returns a tuple with the VarsToDefault field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchJobRequests) GetVarsToDefaultOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.VarsToDefault) {
		return nil, false
	}
	return o.VarsToDefault, true
}

// HasVarsToDefault returns a boolean if a field has been set.
func (o *BatchJobRequests) HasVarsToDefault() bool {
	if o != nil && !IsNil(o.VarsToDefault) {
		return true
	}

	return false
}

// SetVarsToDefault gets a reference to the given map[string]string and assigns it to the VarsToDefault field.
func (o *BatchJobRequests) SetVarsToDefault(v map[string]string) {
	o.VarsToDefault = &v
}

// GetVarsToSet returns the VarsToSet field value if set, zero value otherwise.
func (o *BatchJobRequests) GetVarsToSet() map[string]string {
	if o == nil || IsNil(o.VarsToSet) {
		var ret map[string]string
		return ret
	}
	return *o.VarsToSet
}

// GetVarsToSetOk returns a tuple with the VarsToSet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchJobRequests) GetVarsToSetOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.VarsToSet) {
		return nil, false
	}
	return o.VarsToSet, true
}

// HasVarsToSet returns a boolean if a field has been set.
func (o *BatchJobRequests) HasVarsToSet() bool {
	if o != nil && !IsNil(o.VarsToSet) {
		return true
	}

	return false
}

// SetVarsToSet gets a reference to the given map[string]string and assigns it to the VarsToSet field.
func (o *BatchJobRequests) SetVarsToSet(v map[string]string) {
	o.VarsToSet = &v
}

func (o BatchJobRequests) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchJobRequests) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Comment) {
		toSerialize["comment"] = o.Comment
	}
	if !IsNil(o.ConnectivityAssuranceDisable) {
		toSerialize["connectivity_assurance_disable"] = o.ConnectivityAssuranceDisable
	}
	if !IsNil(o.ConnectivityAssuranceEnable) {
		toSerialize["connectivity_assurance_enable"] = o.ConnectivityAssuranceEnable
	}
	if !IsNil(o.Disable) {
		toSerialize["disable"] = o.Disable
	}
	if !IsNil(o.Enable) {
		toSerialize["enable"] = o.Enable
	}
	if !IsNil(o.FleetsToDefault) {
		toSerialize["fleets_to_default"] = o.FleetsToDefault
	}
	if !IsNil(o.FleetsToJoin) {
		toSerialize["fleets_to_join"] = o.FleetsToJoin
	}
	if !IsNil(o.FleetsToLeave) {
		toSerialize["fleets_to_leave"] = o.FleetsToLeave
	}
	if !IsNil(o.ProvisionProduct) {
		toSerialize["provision_product"] = o.ProvisionProduct
	}
	if !IsNil(o.SnToDefault) {
		toSerialize["sn_to_default"] = o.SnToDefault
	}
	if !IsNil(o.SnToSet) {
		toSerialize["sn_to_set"] = o.SnToSet
	}
	if !IsNil(o.VarsToDefault) {
		toSerialize["vars_to_default"] = o.VarsToDefault
	}
	if !IsNil(o.VarsToSet) {
		toSerialize["vars_to_set"] = o.VarsToSet
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BatchJobRequests) UnmarshalJSON(data []byte) (err error) {
	varBatchJobRequests := _BatchJobRequests{}

	err = json.Unmarshal(data, &varBatchJobRequests)

	if err != nil {
		return err
	}

	*o = BatchJobRequests(varBatchJobRequests)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "comment")
		delete(additionalProperties, "connectivity_assurance_disable")
		delete(additionalProperties, "connectivity_assurance_enable")
		delete(additionalProperties, "disable")
		delete(additionalProperties, "enable")
		delete(additionalProperties, "fleets_to_default")
		delete(additionalProperties, "fleets_to_join")
		delete(additionalProperties, "fleets_to_leave")
		delete(additionalProperties, "provision_product")
		delete(additionalProperties, "sn_to_default")
		delete(additionalProperties, "sn_to_set")
		delete(additionalProperties, "vars_to_default")
		delete(additionalProperties, "vars_to_set")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBatchJobRequests struct {
	value *BatchJobRequests
	isSet bool
}

func (v NullableBatchJobRequests) Get() *BatchJobRequests {
	return v.value
}

func (v *NullableBatchJobRequests) Set(val *BatchJobRequests) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchJobRequests) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchJobRequests) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchJobRequests(val *BatchJobRequests) *NullableBatchJobRequests {
	return &NullableBatchJobRequests{value: val, isSet: true}
}

func (v NullableBatchJobRequests) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchJobRequests) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
