/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"encoding/json"
)

// checks if the DeviceDfuStateMachineNode type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceDfuStateMachineNode{}

// DeviceDfuStateMachineNode Represents a single request to update the host or Notecard firmware
type DeviceDfuStateMachineNode struct {
	// RFC3339 compatible datetime of when this status update happened
	Datetime *string `json:"datetime,omitempty"`
	// Additional information
	Description *string `json:"description,omitempty"`
	// Phase for this step in the firmware update process
	Phase *string `json:"phase,omitempty"`
	// Status for this step in the firmware update process
	Status *string `json:"status,omitempty"`
}

// NewDeviceDfuStateMachineNode instantiates a new DeviceDfuStateMachineNode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceDfuStateMachineNode() *DeviceDfuStateMachineNode {
	this := DeviceDfuStateMachineNode{}
	return &this
}

// NewDeviceDfuStateMachineNodeWithDefaults instantiates a new DeviceDfuStateMachineNode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceDfuStateMachineNodeWithDefaults() *DeviceDfuStateMachineNode {
	this := DeviceDfuStateMachineNode{}
	return &this
}

// GetDatetime returns the Datetime field value if set, zero value otherwise.
func (o *DeviceDfuStateMachineNode) GetDatetime() string {
	if o == nil || IsNil(o.Datetime) {
		var ret string
		return ret
	}
	return *o.Datetime
}

// GetDatetimeOk returns a tuple with the Datetime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceDfuStateMachineNode) GetDatetimeOk() (*string, bool) {
	if o == nil || IsNil(o.Datetime) {
		return nil, false
	}
	return o.Datetime, true
}

// HasDatetime returns a boolean if a field has been set.
func (o *DeviceDfuStateMachineNode) HasDatetime() bool {
	if o != nil && !IsNil(o.Datetime) {
		return true
	}

	return false
}

// SetDatetime gets a reference to the given string and assigns it to the Datetime field.
func (o *DeviceDfuStateMachineNode) SetDatetime(v string) {
	o.Datetime = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *DeviceDfuStateMachineNode) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceDfuStateMachineNode) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *DeviceDfuStateMachineNode) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *DeviceDfuStateMachineNode) SetDescription(v string) {
	o.Description = &v
}

// GetPhase returns the Phase field value if set, zero value otherwise.
func (o *DeviceDfuStateMachineNode) GetPhase() string {
	if o == nil || IsNil(o.Phase) {
		var ret string
		return ret
	}
	return *o.Phase
}

// GetPhaseOk returns a tuple with the Phase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceDfuStateMachineNode) GetPhaseOk() (*string, bool) {
	if o == nil || IsNil(o.Phase) {
		return nil, false
	}
	return o.Phase, true
}

// HasPhase returns a boolean if a field has been set.
func (o *DeviceDfuStateMachineNode) HasPhase() bool {
	if o != nil && !IsNil(o.Phase) {
		return true
	}

	return false
}

// SetPhase gets a reference to the given string and assigns it to the Phase field.
func (o *DeviceDfuStateMachineNode) SetPhase(v string) {
	o.Phase = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *DeviceDfuStateMachineNode) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceDfuStateMachineNode) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *DeviceDfuStateMachineNode) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *DeviceDfuStateMachineNode) SetStatus(v string) {
	o.Status = &v
}

func (o DeviceDfuStateMachineNode) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceDfuStateMachineNode) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Datetime) {
		toSerialize["datetime"] = o.Datetime
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Phase) {
		toSerialize["phase"] = o.Phase
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableDeviceDfuStateMachineNode struct {
	value *DeviceDfuStateMachineNode
	isSet bool
}

func (v NullableDeviceDfuStateMachineNode) Get() *DeviceDfuStateMachineNode {
	return v.value
}

func (v *NullableDeviceDfuStateMachineNode) Set(val *DeviceDfuStateMachineNode) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceDfuStateMachineNode) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceDfuStateMachineNode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceDfuStateMachineNode(val *DeviceDfuStateMachineNode) *NullableDeviceDfuStateMachineNode {
	return &NullableDeviceDfuStateMachineNode{value: val, isSet: true}
}

func (v NullableDeviceDfuStateMachineNode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceDfuStateMachineNode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
