/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"encoding/json"
)

// checks if the Login200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Login200Response{}

// Login200Response struct for Login200Response
type Login200Response struct {
	SessionToken *string `json:"session_token,omitempty"`
}

// NewLogin200Response instantiates a new Login200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLogin200Response() *Login200Response {
	this := Login200Response{}
	return &this
}

// NewLogin200ResponseWithDefaults instantiates a new Login200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLogin200ResponseWithDefaults() *Login200Response {
	this := Login200Response{}
	return &this
}

// GetSessionToken returns the SessionToken field value if set, zero value otherwise.
func (o *Login200Response) GetSessionToken() string {
	if o == nil || IsNil(o.SessionToken) {
		var ret string
		return ret
	}
	return *o.SessionToken
}

// GetSessionTokenOk returns a tuple with the SessionToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Login200Response) GetSessionTokenOk() (*string, bool) {
	if o == nil || IsNil(o.SessionToken) {
		return nil, false
	}
	return o.SessionToken, true
}

// HasSessionToken returns a boolean if a field has been set.
func (o *Login200Response) HasSessionToken() bool {
	if o != nil && !IsNil(o.SessionToken) {
		return true
	}

	return false
}

// SetSessionToken gets a reference to the given string and assigns it to the SessionToken field.
func (o *Login200Response) SetSessionToken(v string) {
	o.SessionToken = &v
}

func (o Login200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Login200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SessionToken) {
		toSerialize["session_token"] = o.SessionToken
	}
	return toSerialize, nil
}

type NullableLogin200Response struct {
	value *Login200Response
	isSet bool
}

func (v NullableLogin200Response) Get() *Login200Response {
	return v.value
}

func (v *NullableLogin200Response) Set(val *Login200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableLogin200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableLogin200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLogin200Response(val *Login200Response) *NullableLogin200Response {
	return &NullableLogin200Response{value: val, isSet: true}
}

func (v NullableLogin200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLogin200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
