/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"encoding/json"
	"fmt"
)

// checks if the JobRun type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobRun{}

// JobRun struct for JobRun
type JobRun struct {
	// Whether cancellation was requested
	Cancel *bool `json:"cancel,omitempty"`
	// Unix timestamp when completed
	Completed *int64 `json:"completed,omitempty"`
	// Whether this was a dry run
	DryRun bool `json:"dry_run"`
	// Name of the job
	JobName string `json:"job_name"`
	// Unique identifier for the job
	JobUid string `json:"job_uid"`
	// Unique identifier for this run
	ReportUid string `json:"report_uid"`
	// Full results (only in detail view)
	Results map[string]interface{} `json:"results,omitempty"`
	// Unix timestamp when started
	Started *int64 `json:"started,omitempty"`
	// Current status (submitted, running, completed, cancelled, failed)
	Status string `json:"status"`
	// Unix timestamp when submitted
	Submitted int64 `json:"submitted"`
	// User who submitted the run
	SubmittedBy string `json:"submitted_by"`
	// Unix timestamp of last update
	Updated              int64 `json:"updated"`
	AdditionalProperties map[string]interface{}
}

type _JobRun JobRun

// NewJobRun instantiates a new JobRun object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobRun(dryRun bool, jobName string, jobUid string, reportUid string, status string, submitted int64, submittedBy string, updated int64) *JobRun {
	this := JobRun{}
	this.DryRun = dryRun
	this.JobName = jobName
	this.JobUid = jobUid
	this.ReportUid = reportUid
	this.Status = status
	this.Submitted = submitted
	this.SubmittedBy = submittedBy
	this.Updated = updated
	return &this
}

// NewJobRunWithDefaults instantiates a new JobRun object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobRunWithDefaults() *JobRun {
	this := JobRun{}
	return &this
}

// GetCancel returns the Cancel field value if set, zero value otherwise.
func (o *JobRun) GetCancel() bool {
	if o == nil || IsNil(o.Cancel) {
		var ret bool
		return ret
	}
	return *o.Cancel
}

// GetCancelOk returns a tuple with the Cancel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRun) GetCancelOk() (*bool, bool) {
	if o == nil || IsNil(o.Cancel) {
		return nil, false
	}
	return o.Cancel, true
}

// HasCancel returns a boolean if a field has been set.
func (o *JobRun) HasCancel() bool {
	if o != nil && !IsNil(o.Cancel) {
		return true
	}

	return false
}

// SetCancel gets a reference to the given bool and assigns it to the Cancel field.
func (o *JobRun) SetCancel(v bool) {
	o.Cancel = &v
}

// GetCompleted returns the Completed field value if set, zero value otherwise.
func (o *JobRun) GetCompleted() int64 {
	if o == nil || IsNil(o.Completed) {
		var ret int64
		return ret
	}
	return *o.Completed
}

// GetCompletedOk returns a tuple with the Completed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRun) GetCompletedOk() (*int64, bool) {
	if o == nil || IsNil(o.Completed) {
		return nil, false
	}
	return o.Completed, true
}

// HasCompleted returns a boolean if a field has been set.
func (o *JobRun) HasCompleted() bool {
	if o != nil && !IsNil(o.Completed) {
		return true
	}

	return false
}

// SetCompleted gets a reference to the given int64 and assigns it to the Completed field.
func (o *JobRun) SetCompleted(v int64) {
	o.Completed = &v
}

// GetDryRun returns the DryRun field value
func (o *JobRun) GetDryRun() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.DryRun
}

// GetDryRunOk returns a tuple with the DryRun field value
// and a boolean to check if the value has been set.
func (o *JobRun) GetDryRunOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DryRun, true
}

// SetDryRun sets field value
func (o *JobRun) SetDryRun(v bool) {
	o.DryRun = v
}

// GetJobName returns the JobName field value
func (o *JobRun) GetJobName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobName
}

// GetJobNameOk returns a tuple with the JobName field value
// and a boolean to check if the value has been set.
func (o *JobRun) GetJobNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobName, true
}

// SetJobName sets field value
func (o *JobRun) SetJobName(v string) {
	o.JobName = v
}

// GetJobUid returns the JobUid field value
func (o *JobRun) GetJobUid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobUid
}

// GetJobUidOk returns a tuple with the JobUid field value
// and a boolean to check if the value has been set.
func (o *JobRun) GetJobUidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobUid, true
}

// SetJobUid sets field value
func (o *JobRun) SetJobUid(v string) {
	o.JobUid = v
}

// GetReportUid returns the ReportUid field value
func (o *JobRun) GetReportUid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReportUid
}

// GetReportUidOk returns a tuple with the ReportUid field value
// and a boolean to check if the value has been set.
func (o *JobRun) GetReportUidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReportUid, true
}

// SetReportUid sets field value
func (o *JobRun) SetReportUid(v string) {
	o.ReportUid = v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *JobRun) GetResults() map[string]interface{} {
	if o == nil || IsNil(o.Results) {
		var ret map[string]interface{}
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRun) GetResultsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Results) {
		return map[string]interface{}{}, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *JobRun) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given map[string]interface{} and assigns it to the Results field.
func (o *JobRun) SetResults(v map[string]interface{}) {
	o.Results = v
}

// GetStarted returns the Started field value if set, zero value otherwise.
func (o *JobRun) GetStarted() int64 {
	if o == nil || IsNil(o.Started) {
		var ret int64
		return ret
	}
	return *o.Started
}

// GetStartedOk returns a tuple with the Started field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobRun) GetStartedOk() (*int64, bool) {
	if o == nil || IsNil(o.Started) {
		return nil, false
	}
	return o.Started, true
}

// HasStarted returns a boolean if a field has been set.
func (o *JobRun) HasStarted() bool {
	if o != nil && !IsNil(o.Started) {
		return true
	}

	return false
}

// SetStarted gets a reference to the given int64 and assigns it to the Started field.
func (o *JobRun) SetStarted(v int64) {
	o.Started = &v
}

// GetStatus returns the Status field value
func (o *JobRun) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *JobRun) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *JobRun) SetStatus(v string) {
	o.Status = v
}

// GetSubmitted returns the Submitted field value
func (o *JobRun) GetSubmitted() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Submitted
}

// GetSubmittedOk returns a tuple with the Submitted field value
// and a boolean to check if the value has been set.
func (o *JobRun) GetSubmittedOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Submitted, true
}

// SetSubmitted sets field value
func (o *JobRun) SetSubmitted(v int64) {
	o.Submitted = v
}

// GetSubmittedBy returns the SubmittedBy field value
func (o *JobRun) GetSubmittedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubmittedBy
}

// GetSubmittedByOk returns a tuple with the SubmittedBy field value
// and a boolean to check if the value has been set.
func (o *JobRun) GetSubmittedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubmittedBy, true
}

// SetSubmittedBy sets field value
func (o *JobRun) SetSubmittedBy(v string) {
	o.SubmittedBy = v
}

// GetUpdated returns the Updated field value
func (o *JobRun) GetUpdated() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value
// and a boolean to check if the value has been set.
func (o *JobRun) GetUpdatedOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Updated, true
}

// SetUpdated sets field value
func (o *JobRun) SetUpdated(v int64) {
	o.Updated = v
}

func (o JobRun) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobRun) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cancel) {
		toSerialize["cancel"] = o.Cancel
	}
	if !IsNil(o.Completed) {
		toSerialize["completed"] = o.Completed
	}
	toSerialize["dry_run"] = o.DryRun
	toSerialize["job_name"] = o.JobName
	toSerialize["job_uid"] = o.JobUid
	toSerialize["report_uid"] = o.ReportUid
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	if !IsNil(o.Started) {
		toSerialize["started"] = o.Started
	}
	toSerialize["status"] = o.Status
	toSerialize["submitted"] = o.Submitted
	toSerialize["submitted_by"] = o.SubmittedBy
	toSerialize["updated"] = o.Updated

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *JobRun) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"dry_run",
		"job_name",
		"job_uid",
		"report_uid",
		"status",
		"submitted",
		"submitted_by",
		"updated",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJobRun := _JobRun{}

	err = json.Unmarshal(data, &varJobRun)

	if err != nil {
		return err
	}

	*o = JobRun(varJobRun)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "cancel")
		delete(additionalProperties, "completed")
		delete(additionalProperties, "dry_run")
		delete(additionalProperties, "job_name")
		delete(additionalProperties, "job_uid")
		delete(additionalProperties, "report_uid")
		delete(additionalProperties, "results")
		delete(additionalProperties, "started")
		delete(additionalProperties, "status")
		delete(additionalProperties, "submitted")
		delete(additionalProperties, "submitted_by")
		delete(additionalProperties, "updated")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableJobRun struct {
	value *JobRun
	isSet bool
}

func (v NullableJobRun) Get() *JobRun {
	return v.value
}

func (v *NullableJobRun) Set(val *JobRun) {
	v.value = val
	v.isSet = true
}

func (v NullableJobRun) IsSet() bool {
	return v.isSet
}

func (v *NullableJobRun) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobRun(val *JobRun) *NullableJobRun {
	return &NullableJobRun{value: val, isSet: true}
}

func (v NullableJobRun) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobRun) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
