/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"encoding/json"
)

// checks if the UserFirmwareInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserFirmwareInfo{}

// UserFirmwareInfo struct for UserFirmwareInfo
type UserFirmwareInfo struct {
	CurrentFirmware *CurrentFirmware     `json:"current_firmware,omitempty"`
	FirmwareUpdate  *UserDfuStateMachine `json:"firmware_update,omitempty"`
}

// NewUserFirmwareInfo instantiates a new UserFirmwareInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserFirmwareInfo() *UserFirmwareInfo {
	this := UserFirmwareInfo{}
	return &this
}

// NewUserFirmwareInfoWithDefaults instantiates a new UserFirmwareInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserFirmwareInfoWithDefaults() *UserFirmwareInfo {
	this := UserFirmwareInfo{}
	return &this
}

// GetCurrentFirmware returns the CurrentFirmware field value if set, zero value otherwise.
func (o *UserFirmwareInfo) GetCurrentFirmware() CurrentFirmware {
	if o == nil || IsNil(o.CurrentFirmware) {
		var ret CurrentFirmware
		return ret
	}
	return *o.CurrentFirmware
}

// GetCurrentFirmwareOk returns a tuple with the CurrentFirmware field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserFirmwareInfo) GetCurrentFirmwareOk() (*CurrentFirmware, bool) {
	if o == nil || IsNil(o.CurrentFirmware) {
		return nil, false
	}
	return o.CurrentFirmware, true
}

// HasCurrentFirmware returns a boolean if a field has been set.
func (o *UserFirmwareInfo) HasCurrentFirmware() bool {
	if o != nil && !IsNil(o.CurrentFirmware) {
		return true
	}

	return false
}

// SetCurrentFirmware gets a reference to the given CurrentFirmware and assigns it to the CurrentFirmware field.
func (o *UserFirmwareInfo) SetCurrentFirmware(v CurrentFirmware) {
	o.CurrentFirmware = &v
}

// GetFirmwareUpdate returns the FirmwareUpdate field value if set, zero value otherwise.
func (o *UserFirmwareInfo) GetFirmwareUpdate() UserDfuStateMachine {
	if o == nil || IsNil(o.FirmwareUpdate) {
		var ret UserDfuStateMachine
		return ret
	}
	return *o.FirmwareUpdate
}

// GetFirmwareUpdateOk returns a tuple with the FirmwareUpdate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserFirmwareInfo) GetFirmwareUpdateOk() (*UserDfuStateMachine, bool) {
	if o == nil || IsNil(o.FirmwareUpdate) {
		return nil, false
	}
	return o.FirmwareUpdate, true
}

// HasFirmwareUpdate returns a boolean if a field has been set.
func (o *UserFirmwareInfo) HasFirmwareUpdate() bool {
	if o != nil && !IsNil(o.FirmwareUpdate) {
		return true
	}

	return false
}

// SetFirmwareUpdate gets a reference to the given UserDfuStateMachine and assigns it to the FirmwareUpdate field.
func (o *UserFirmwareInfo) SetFirmwareUpdate(v UserDfuStateMachine) {
	o.FirmwareUpdate = &v
}

func (o UserFirmwareInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserFirmwareInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CurrentFirmware) {
		toSerialize["current_firmware"] = o.CurrentFirmware
	}
	if !IsNil(o.FirmwareUpdate) {
		toSerialize["firmware_update"] = o.FirmwareUpdate
	}
	return toSerialize, nil
}

type NullableUserFirmwareInfo struct {
	value *UserFirmwareInfo
	isSet bool
}

func (v NullableUserFirmwareInfo) Get() *UserFirmwareInfo {
	return v.value
}

func (v *NullableUserFirmwareInfo) Set(val *UserFirmwareInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableUserFirmwareInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableUserFirmwareInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserFirmwareInfo(val *UserFirmwareInfo) *NullableUserFirmwareInfo {
	return &NullableUserFirmwareInfo{value: val, isSet: true}
}

func (v NullableUserFirmwareInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserFirmwareInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
