/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateProductRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateProductRequest{}

// CreateProductRequest struct for CreateProductRequest
type CreateProductRequest struct {
	AutoProvisionFleets []string `json:"auto_provision_fleets,omitempty"`
	// If `true`, devices provisioned to this product will be automatically disabled by default.
	DisableDevicesByDefault *bool `json:"disable_devices_by_default,omitempty"`
	// The label for the Product.
	Label string `json:"label"`
	// The requested uid for the Product. Will be prefixed with the user's reversed email.
	ProductUid string `json:"product_uid"`
}

type _CreateProductRequest CreateProductRequest

// NewCreateProductRequest instantiates a new CreateProductRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateProductRequest(label string, productUid string) *CreateProductRequest {
	this := CreateProductRequest{}
	this.Label = label
	this.ProductUid = productUid
	return &this
}

// NewCreateProductRequestWithDefaults instantiates a new CreateProductRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateProductRequestWithDefaults() *CreateProductRequest {
	this := CreateProductRequest{}
	return &this
}

// GetAutoProvisionFleets returns the AutoProvisionFleets field value if set, zero value otherwise.
func (o *CreateProductRequest) GetAutoProvisionFleets() []string {
	if o == nil || IsNil(o.AutoProvisionFleets) {
		var ret []string
		return ret
	}
	return o.AutoProvisionFleets
}

// GetAutoProvisionFleetsOk returns a tuple with the AutoProvisionFleets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProductRequest) GetAutoProvisionFleetsOk() ([]string, bool) {
	if o == nil || IsNil(o.AutoProvisionFleets) {
		return nil, false
	}
	return o.AutoProvisionFleets, true
}

// HasAutoProvisionFleets returns a boolean if a field has been set.
func (o *CreateProductRequest) HasAutoProvisionFleets() bool {
	if o != nil && !IsNil(o.AutoProvisionFleets) {
		return true
	}

	return false
}

// SetAutoProvisionFleets gets a reference to the given []string and assigns it to the AutoProvisionFleets field.
func (o *CreateProductRequest) SetAutoProvisionFleets(v []string) {
	o.AutoProvisionFleets = v
}

// GetDisableDevicesByDefault returns the DisableDevicesByDefault field value if set, zero value otherwise.
func (o *CreateProductRequest) GetDisableDevicesByDefault() bool {
	if o == nil || IsNil(o.DisableDevicesByDefault) {
		var ret bool
		return ret
	}
	return *o.DisableDevicesByDefault
}

// GetDisableDevicesByDefaultOk returns a tuple with the DisableDevicesByDefault field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProductRequest) GetDisableDevicesByDefaultOk() (*bool, bool) {
	if o == nil || IsNil(o.DisableDevicesByDefault) {
		return nil, false
	}
	return o.DisableDevicesByDefault, true
}

// HasDisableDevicesByDefault returns a boolean if a field has been set.
func (o *CreateProductRequest) HasDisableDevicesByDefault() bool {
	if o != nil && !IsNil(o.DisableDevicesByDefault) {
		return true
	}

	return false
}

// SetDisableDevicesByDefault gets a reference to the given bool and assigns it to the DisableDevicesByDefault field.
func (o *CreateProductRequest) SetDisableDevicesByDefault(v bool) {
	o.DisableDevicesByDefault = &v
}

// GetLabel returns the Label field value
func (o *CreateProductRequest) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *CreateProductRequest) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *CreateProductRequest) SetLabel(v string) {
	o.Label = v
}

// GetProductUid returns the ProductUid field value
func (o *CreateProductRequest) GetProductUid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProductUid
}

// GetProductUidOk returns a tuple with the ProductUid field value
// and a boolean to check if the value has been set.
func (o *CreateProductRequest) GetProductUidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProductUid, true
}

// SetProductUid sets field value
func (o *CreateProductRequest) SetProductUid(v string) {
	o.ProductUid = v
}

func (o CreateProductRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateProductRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AutoProvisionFleets) {
		toSerialize["auto_provision_fleets"] = o.AutoProvisionFleets
	}
	if !IsNil(o.DisableDevicesByDefault) {
		toSerialize["disable_devices_by_default"] = o.DisableDevicesByDefault
	}
	toSerialize["label"] = o.Label
	toSerialize["product_uid"] = o.ProductUid
	return toSerialize, nil
}

func (o *CreateProductRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"label",
		"product_uid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateProductRequest := _CreateProductRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateProductRequest)

	if err != nil {
		return err
	}

	*o = CreateProductRequest(varCreateProductRequest)

	return err
}

type NullableCreateProductRequest struct {
	value *CreateProductRequest
	isSet bool
}

func (v NullableCreateProductRequest) Get() *CreateProductRequest {
	return v.value
}

func (v *NullableCreateProductRequest) Set(val *CreateProductRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateProductRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateProductRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateProductRequest(val *CreateProductRequest) *NullableCreateProductRequest {
	return &NullableCreateProductRequest{value: val, isSet: true}
}

func (v NullableCreateProductRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateProductRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
