/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DeleteDeviceFromFleetsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteDeviceFromFleetsRequest{}

// DeleteDeviceFromFleetsRequest struct for DeleteDeviceFromFleetsRequest
type DeleteDeviceFromFleetsRequest struct {
	// The fleetUIDs to remove from the device.
	FleetUids []string `json:"fleet_uids"`
}

type _DeleteDeviceFromFleetsRequest DeleteDeviceFromFleetsRequest

// NewDeleteDeviceFromFleetsRequest instantiates a new DeleteDeviceFromFleetsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteDeviceFromFleetsRequest(fleetUids []string) *DeleteDeviceFromFleetsRequest {
	this := DeleteDeviceFromFleetsRequest{}
	this.FleetUids = fleetUids
	return &this
}

// NewDeleteDeviceFromFleetsRequestWithDefaults instantiates a new DeleteDeviceFromFleetsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteDeviceFromFleetsRequestWithDefaults() *DeleteDeviceFromFleetsRequest {
	this := DeleteDeviceFromFleetsRequest{}
	return &this
}

// GetFleetUids returns the FleetUids field value
func (o *DeleteDeviceFromFleetsRequest) GetFleetUids() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.FleetUids
}

// GetFleetUidsOk returns a tuple with the FleetUids field value
// and a boolean to check if the value has been set.
func (o *DeleteDeviceFromFleetsRequest) GetFleetUidsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FleetUids, true
}

// SetFleetUids sets field value
func (o *DeleteDeviceFromFleetsRequest) SetFleetUids(v []string) {
	o.FleetUids = v
}

func (o DeleteDeviceFromFleetsRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteDeviceFromFleetsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["fleet_uids"] = o.FleetUids
	return toSerialize, nil
}

func (o *DeleteDeviceFromFleetsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fleet_uids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteDeviceFromFleetsRequest := _DeleteDeviceFromFleetsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteDeviceFromFleetsRequest)

	if err != nil {
		return err
	}

	*o = DeleteDeviceFromFleetsRequest(varDeleteDeviceFromFleetsRequest)

	return err
}

type NullableDeleteDeviceFromFleetsRequest struct {
	value *DeleteDeviceFromFleetsRequest
	isSet bool
}

func (v NullableDeleteDeviceFromFleetsRequest) Get() *DeleteDeviceFromFleetsRequest {
	return v.value
}

func (v *NullableDeleteDeviceFromFleetsRequest) Set(val *DeleteDeviceFromFleetsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteDeviceFromFleetsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteDeviceFromFleetsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteDeviceFromFleetsRequest(val *DeleteDeviceFromFleetsRequest) *NullableDeleteDeviceFromFleetsRequest {
	return &NullableDeleteDeviceFromFleetsRequest{value: val, isSet: true}
}

func (v NullableDeleteDeviceFromFleetsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteDeviceFromFleetsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
