/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetDeviceSessions200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetDeviceSessions200Response{}

// GetDeviceSessions200Response struct for GetDeviceSessions200Response
type GetDeviceSessions200Response struct {
	HasMore  bool            `json:"has_more"`
	Sessions []DeviceSession `json:"sessions"`
}

type _GetDeviceSessions200Response GetDeviceSessions200Response

// NewGetDeviceSessions200Response instantiates a new GetDeviceSessions200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetDeviceSessions200Response(hasMore bool, sessions []DeviceSession) *GetDeviceSessions200Response {
	this := GetDeviceSessions200Response{}
	this.HasMore = hasMore
	this.Sessions = sessions
	return &this
}

// NewGetDeviceSessions200ResponseWithDefaults instantiates a new GetDeviceSessions200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetDeviceSessions200ResponseWithDefaults() *GetDeviceSessions200Response {
	this := GetDeviceSessions200Response{}
	return &this
}

// GetHasMore returns the HasMore field value
func (o *GetDeviceSessions200Response) GetHasMore() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value
// and a boolean to check if the value has been set.
func (o *GetDeviceSessions200Response) GetHasMoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasMore, true
}

// SetHasMore sets field value
func (o *GetDeviceSessions200Response) SetHasMore(v bool) {
	o.HasMore = v
}

// GetSessions returns the Sessions field value
func (o *GetDeviceSessions200Response) GetSessions() []DeviceSession {
	if o == nil {
		var ret []DeviceSession
		return ret
	}

	return o.Sessions
}

// GetSessionsOk returns a tuple with the Sessions field value
// and a boolean to check if the value has been set.
func (o *GetDeviceSessions200Response) GetSessionsOk() ([]DeviceSession, bool) {
	if o == nil {
		return nil, false
	}
	return o.Sessions, true
}

// SetSessions sets field value
func (o *GetDeviceSessions200Response) SetSessions(v []DeviceSession) {
	o.Sessions = v
}

func (o GetDeviceSessions200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetDeviceSessions200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["has_more"] = o.HasMore
	toSerialize["sessions"] = o.Sessions
	return toSerialize, nil
}

func (o *GetDeviceSessions200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"has_more",
		"sessions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetDeviceSessions200Response := _GetDeviceSessions200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetDeviceSessions200Response)

	if err != nil {
		return err
	}

	*o = GetDeviceSessions200Response(varGetDeviceSessions200Response)

	return err
}

type NullableGetDeviceSessions200Response struct {
	value *GetDeviceSessions200Response
	isSet bool
}

func (v NullableGetDeviceSessions200Response) Get() *GetDeviceSessions200Response {
	return v.value
}

func (v *NullableGetDeviceSessions200Response) Set(val *GetDeviceSessions200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDeviceSessions200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDeviceSessions200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDeviceSessions200Response(val *GetDeviceSessions200Response) *NullableGetDeviceSessions200Response {
	return &NullableGetDeviceSessions200Response{value: val, isSet: true}
}

func (v NullableGetDeviceSessions200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetDeviceSessions200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
