/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the DeviceSensor type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceSensor{}

// DeviceSensor A sensor attached to a device
type DeviceSensor struct {
	// UTC midnight of the most recent day on which this sensor was active
	LastActivityDate *time.Time `json:"last_activity_date,omitempty"`
	// Unique identifier of the sensor
	SensorUid            string `json:"sensor_uid"`
	AdditionalProperties map[string]interface{}
}

type _DeviceSensor DeviceSensor

// NewDeviceSensor instantiates a new DeviceSensor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceSensor(sensorUid string) *DeviceSensor {
	this := DeviceSensor{}
	this.SensorUid = sensorUid
	return &this
}

// NewDeviceSensorWithDefaults instantiates a new DeviceSensor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceSensorWithDefaults() *DeviceSensor {
	this := DeviceSensor{}
	return &this
}

// GetLastActivityDate returns the LastActivityDate field value if set, zero value otherwise.
func (o *DeviceSensor) GetLastActivityDate() time.Time {
	if o == nil || IsNil(o.LastActivityDate) {
		var ret time.Time
		return ret
	}
	return *o.LastActivityDate
}

// GetLastActivityDateOk returns a tuple with the LastActivityDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceSensor) GetLastActivityDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastActivityDate) {
		return nil, false
	}
	return o.LastActivityDate, true
}

// HasLastActivityDate returns a boolean if a field has been set.
func (o *DeviceSensor) HasLastActivityDate() bool {
	if o != nil && !IsNil(o.LastActivityDate) {
		return true
	}

	return false
}

// SetLastActivityDate gets a reference to the given time.Time and assigns it to the LastActivityDate field.
func (o *DeviceSensor) SetLastActivityDate(v time.Time) {
	o.LastActivityDate = &v
}

// GetSensorUid returns the SensorUid field value
func (o *DeviceSensor) GetSensorUid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SensorUid
}

// GetSensorUidOk returns a tuple with the SensorUid field value
// and a boolean to check if the value has been set.
func (o *DeviceSensor) GetSensorUidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SensorUid, true
}

// SetSensorUid sets field value
func (o *DeviceSensor) SetSensorUid(v string) {
	o.SensorUid = v
}

func (o DeviceSensor) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceSensor) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LastActivityDate) {
		toSerialize["last_activity_date"] = o.LastActivityDate
	}
	toSerialize["sensor_uid"] = o.SensorUid

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DeviceSensor) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sensor_uid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeviceSensor := _DeviceSensor{}

	err = json.Unmarshal(data, &varDeviceSensor)

	if err != nil {
		return err
	}

	*o = DeviceSensor(varDeviceSensor)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "last_activity_date")
		delete(additionalProperties, "sensor_uid")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDeviceSensor struct {
	value *DeviceSensor
	isSet bool
}

func (v NullableDeviceSensor) Get() *DeviceSensor {
	return v.value
}

func (v *NullableDeviceSensor) Set(val *DeviceSensor) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceSensor) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceSensor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceSensor(val *DeviceSensor) *NullableDeviceSensor {
	return &NullableDeviceSensor{value: val, isSet: true}
}

func (v NullableDeviceSensor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceSensor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
