/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ProvisionDeviceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProvisionDeviceRequest{}

// ProvisionDeviceRequest struct for ProvisionDeviceRequest
type ProvisionDeviceRequest struct {
	// The serial number to assign to the device.
	DeviceSn *string `json:"device_sn,omitempty"`
	// The fleetUIDs to provision the device to.
	FleetUids []string `json:"fleet_uids,omitempty"`
	// The ProductUID that the device should use.
	ProductUid string `json:"product_uid"`
}

type _ProvisionDeviceRequest ProvisionDeviceRequest

// NewProvisionDeviceRequest instantiates a new ProvisionDeviceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProvisionDeviceRequest(productUid string) *ProvisionDeviceRequest {
	this := ProvisionDeviceRequest{}
	this.ProductUid = productUid
	return &this
}

// NewProvisionDeviceRequestWithDefaults instantiates a new ProvisionDeviceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProvisionDeviceRequestWithDefaults() *ProvisionDeviceRequest {
	this := ProvisionDeviceRequest{}
	return &this
}

// GetDeviceSn returns the DeviceSn field value if set, zero value otherwise.
func (o *ProvisionDeviceRequest) GetDeviceSn() string {
	if o == nil || IsNil(o.DeviceSn) {
		var ret string
		return ret
	}
	return *o.DeviceSn
}

// GetDeviceSnOk returns a tuple with the DeviceSn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvisionDeviceRequest) GetDeviceSnOk() (*string, bool) {
	if o == nil || IsNil(o.DeviceSn) {
		return nil, false
	}
	return o.DeviceSn, true
}

// HasDeviceSn returns a boolean if a field has been set.
func (o *ProvisionDeviceRequest) HasDeviceSn() bool {
	if o != nil && !IsNil(o.DeviceSn) {
		return true
	}

	return false
}

// SetDeviceSn gets a reference to the given string and assigns it to the DeviceSn field.
func (o *ProvisionDeviceRequest) SetDeviceSn(v string) {
	o.DeviceSn = &v
}

// GetFleetUids returns the FleetUids field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProvisionDeviceRequest) GetFleetUids() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.FleetUids
}

// GetFleetUidsOk returns a tuple with the FleetUids field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProvisionDeviceRequest) GetFleetUidsOk() ([]string, bool) {
	if o == nil || IsNil(o.FleetUids) {
		return nil, false
	}
	return o.FleetUids, true
}

// HasFleetUids returns a boolean if a field has been set.
func (o *ProvisionDeviceRequest) HasFleetUids() bool {
	if o != nil && !IsNil(o.FleetUids) {
		return true
	}

	return false
}

// SetFleetUids gets a reference to the given []string and assigns it to the FleetUids field.
func (o *ProvisionDeviceRequest) SetFleetUids(v []string) {
	o.FleetUids = v
}

// GetProductUid returns the ProductUid field value
func (o *ProvisionDeviceRequest) GetProductUid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProductUid
}

// GetProductUidOk returns a tuple with the ProductUid field value
// and a boolean to check if the value has been set.
func (o *ProvisionDeviceRequest) GetProductUidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProductUid, true
}

// SetProductUid sets field value
func (o *ProvisionDeviceRequest) SetProductUid(v string) {
	o.ProductUid = v
}

func (o ProvisionDeviceRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProvisionDeviceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DeviceSn) {
		toSerialize["device_sn"] = o.DeviceSn
	}
	if o.FleetUids != nil {
		toSerialize["fleet_uids"] = o.FleetUids
	}
	toSerialize["product_uid"] = o.ProductUid
	return toSerialize, nil
}

func (o *ProvisionDeviceRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"product_uid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProvisionDeviceRequest := _ProvisionDeviceRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProvisionDeviceRequest)

	if err != nil {
		return err
	}

	*o = ProvisionDeviceRequest(varProvisionDeviceRequest)

	return err
}

type NullableProvisionDeviceRequest struct {
	value *ProvisionDeviceRequest
	isSet bool
}

func (v NullableProvisionDeviceRequest) Get() *ProvisionDeviceRequest {
	return v.value
}

func (v *NullableProvisionDeviceRequest) Set(val *ProvisionDeviceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProvisionDeviceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProvisionDeviceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProvisionDeviceRequest(val *ProvisionDeviceRequest) *NullableProvisionDeviceRequest {
	return &NullableProvisionDeviceRequest{value: val, isSet: true}
}

func (v NullableProvisionDeviceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProvisionDeviceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
