/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"encoding/json"
)

// checks if the UpdateFleetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateFleetRequest{}

// UpdateFleetRequest struct for UpdateFleetRequest
type UpdateFleetRequest struct {
	// List of DeviceUIDs to add to fleet
	AddDevices            []string                           `json:"addDevices,omitempty"`
	ConnectivityAssurance NullableFleetConnectivityAssurance `json:"connectivity_assurance,omitempty"`
	// The label for the Fleet.
	Label *string `json:"label,omitempty"`
	// List of DeviceUIDs to remove from fleet
	RemoveDevices []string `json:"removeDevices,omitempty"`
	// JSONata expression that will be evaluated to determine device membership into this fleet, if the expression evaluates to a 1, the device will be included, if it evaluates to -1 it will be removed, and if it evaluates to 0 or errors it will be left unchanged.
	SmartRule        *string `json:"smart_rule,omitempty"`
	SmartRuleEnabled *bool   `json:"smart_rule_enabled,omitempty"`
	// A watchdog timer is used to generate an event every N minutes of inactivity. 0 means no watchdog
	WatchdogMins *int64 `json:"watchdog_mins,omitempty"`
}

// NewUpdateFleetRequest instantiates a new UpdateFleetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateFleetRequest() *UpdateFleetRequest {
	this := UpdateFleetRequest{}
	return &this
}

// NewUpdateFleetRequestWithDefaults instantiates a new UpdateFleetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateFleetRequestWithDefaults() *UpdateFleetRequest {
	this := UpdateFleetRequest{}
	return &this
}

// GetAddDevices returns the AddDevices field value if set, zero value otherwise.
func (o *UpdateFleetRequest) GetAddDevices() []string {
	if o == nil || IsNil(o.AddDevices) {
		var ret []string
		return ret
	}
	return o.AddDevices
}

// GetAddDevicesOk returns a tuple with the AddDevices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateFleetRequest) GetAddDevicesOk() ([]string, bool) {
	if o == nil || IsNil(o.AddDevices) {
		return nil, false
	}
	return o.AddDevices, true
}

// HasAddDevices returns a boolean if a field has been set.
func (o *UpdateFleetRequest) HasAddDevices() bool {
	if o != nil && !IsNil(o.AddDevices) {
		return true
	}

	return false
}

// SetAddDevices gets a reference to the given []string and assigns it to the AddDevices field.
func (o *UpdateFleetRequest) SetAddDevices(v []string) {
	o.AddDevices = v
}

// GetConnectivityAssurance returns the ConnectivityAssurance field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateFleetRequest) GetConnectivityAssurance() FleetConnectivityAssurance {
	if o == nil || IsNil(o.ConnectivityAssurance.Get()) {
		var ret FleetConnectivityAssurance
		return ret
	}
	return *o.ConnectivityAssurance.Get()
}

// GetConnectivityAssuranceOk returns a tuple with the ConnectivityAssurance field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateFleetRequest) GetConnectivityAssuranceOk() (*FleetConnectivityAssurance, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConnectivityAssurance.Get(), o.ConnectivityAssurance.IsSet()
}

// HasConnectivityAssurance returns a boolean if a field has been set.
func (o *UpdateFleetRequest) HasConnectivityAssurance() bool {
	if o != nil && o.ConnectivityAssurance.IsSet() {
		return true
	}

	return false
}

// SetConnectivityAssurance gets a reference to the given NullableFleetConnectivityAssurance and assigns it to the ConnectivityAssurance field.
func (o *UpdateFleetRequest) SetConnectivityAssurance(v FleetConnectivityAssurance) {
	o.ConnectivityAssurance.Set(&v)
}

// SetConnectivityAssuranceNil sets the value for ConnectivityAssurance to be an explicit nil
func (o *UpdateFleetRequest) SetConnectivityAssuranceNil() {
	o.ConnectivityAssurance.Set(nil)
}

// UnsetConnectivityAssurance ensures that no value is present for ConnectivityAssurance, not even an explicit nil
func (o *UpdateFleetRequest) UnsetConnectivityAssurance() {
	o.ConnectivityAssurance.Unset()
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *UpdateFleetRequest) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateFleetRequest) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *UpdateFleetRequest) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *UpdateFleetRequest) SetLabel(v string) {
	o.Label = &v
}

// GetRemoveDevices returns the RemoveDevices field value if set, zero value otherwise.
func (o *UpdateFleetRequest) GetRemoveDevices() []string {
	if o == nil || IsNil(o.RemoveDevices) {
		var ret []string
		return ret
	}
	return o.RemoveDevices
}

// GetRemoveDevicesOk returns a tuple with the RemoveDevices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateFleetRequest) GetRemoveDevicesOk() ([]string, bool) {
	if o == nil || IsNil(o.RemoveDevices) {
		return nil, false
	}
	return o.RemoveDevices, true
}

// HasRemoveDevices returns a boolean if a field has been set.
func (o *UpdateFleetRequest) HasRemoveDevices() bool {
	if o != nil && !IsNil(o.RemoveDevices) {
		return true
	}

	return false
}

// SetRemoveDevices gets a reference to the given []string and assigns it to the RemoveDevices field.
func (o *UpdateFleetRequest) SetRemoveDevices(v []string) {
	o.RemoveDevices = v
}

// GetSmartRule returns the SmartRule field value if set, zero value otherwise.
func (o *UpdateFleetRequest) GetSmartRule() string {
	if o == nil || IsNil(o.SmartRule) {
		var ret string
		return ret
	}
	return *o.SmartRule
}

// GetSmartRuleOk returns a tuple with the SmartRule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateFleetRequest) GetSmartRuleOk() (*string, bool) {
	if o == nil || IsNil(o.SmartRule) {
		return nil, false
	}
	return o.SmartRule, true
}

// HasSmartRule returns a boolean if a field has been set.
func (o *UpdateFleetRequest) HasSmartRule() bool {
	if o != nil && !IsNil(o.SmartRule) {
		return true
	}

	return false
}

// SetSmartRule gets a reference to the given string and assigns it to the SmartRule field.
func (o *UpdateFleetRequest) SetSmartRule(v string) {
	o.SmartRule = &v
}

// GetSmartRuleEnabled returns the SmartRuleEnabled field value if set, zero value otherwise.
func (o *UpdateFleetRequest) GetSmartRuleEnabled() bool {
	if o == nil || IsNil(o.SmartRuleEnabled) {
		var ret bool
		return ret
	}
	return *o.SmartRuleEnabled
}

// GetSmartRuleEnabledOk returns a tuple with the SmartRuleEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateFleetRequest) GetSmartRuleEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.SmartRuleEnabled) {
		return nil, false
	}
	return o.SmartRuleEnabled, true
}

// HasSmartRuleEnabled returns a boolean if a field has been set.
func (o *UpdateFleetRequest) HasSmartRuleEnabled() bool {
	if o != nil && !IsNil(o.SmartRuleEnabled) {
		return true
	}

	return false
}

// SetSmartRuleEnabled gets a reference to the given bool and assigns it to the SmartRuleEnabled field.
func (o *UpdateFleetRequest) SetSmartRuleEnabled(v bool) {
	o.SmartRuleEnabled = &v
}

// GetWatchdogMins returns the WatchdogMins field value if set, zero value otherwise.
func (o *UpdateFleetRequest) GetWatchdogMins() int64 {
	if o == nil || IsNil(o.WatchdogMins) {
		var ret int64
		return ret
	}
	return *o.WatchdogMins
}

// GetWatchdogMinsOk returns a tuple with the WatchdogMins field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateFleetRequest) GetWatchdogMinsOk() (*int64, bool) {
	if o == nil || IsNil(o.WatchdogMins) {
		return nil, false
	}
	return o.WatchdogMins, true
}

// HasWatchdogMins returns a boolean if a field has been set.
func (o *UpdateFleetRequest) HasWatchdogMins() bool {
	if o != nil && !IsNil(o.WatchdogMins) {
		return true
	}

	return false
}

// SetWatchdogMins gets a reference to the given int64 and assigns it to the WatchdogMins field.
func (o *UpdateFleetRequest) SetWatchdogMins(v int64) {
	o.WatchdogMins = &v
}

func (o UpdateFleetRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateFleetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AddDevices) {
		toSerialize["addDevices"] = o.AddDevices
	}
	if o.ConnectivityAssurance.IsSet() {
		toSerialize["connectivity_assurance"] = o.ConnectivityAssurance.Get()
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.RemoveDevices) {
		toSerialize["removeDevices"] = o.RemoveDevices
	}
	if !IsNil(o.SmartRule) {
		toSerialize["smart_rule"] = o.SmartRule
	}
	if !IsNil(o.SmartRuleEnabled) {
		toSerialize["smart_rule_enabled"] = o.SmartRuleEnabled
	}
	if !IsNil(o.WatchdogMins) {
		toSerialize["watchdog_mins"] = o.WatchdogMins
	}
	return toSerialize, nil
}

type NullableUpdateFleetRequest struct {
	value *UpdateFleetRequest
	isSet bool
}

func (v NullableUpdateFleetRequest) Get() *UpdateFleetRequest {
	return v.value
}

func (v *NullableUpdateFleetRequest) Set(val *UpdateFleetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateFleetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateFleetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateFleetRequest(val *UpdateFleetRequest) *NullableUpdateFleetRequest {
	return &NullableUpdateFleetRequest{value: val, isSet: true}
}

func (v NullableUpdateFleetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateFleetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
