/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the OAuth2Error type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OAuth2Error{}

// OAuth2Error struct for OAuth2Error
type OAuth2Error struct {
	// RFC 6749 error code.
	Error string `json:"error"`
	// Human-readable explanation of the error.
	ErrorDescription *string `json:"error_description,omitempty"`
}

type _OAuth2Error OAuth2Error

// NewOAuth2Error instantiates a new OAuth2Error object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOAuth2Error(error_ string) *OAuth2Error {
	this := OAuth2Error{}
	this.Error = error_
	return &this
}

// NewOAuth2ErrorWithDefaults instantiates a new OAuth2Error object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOAuth2ErrorWithDefaults() *OAuth2Error {
	this := OAuth2Error{}
	return &this
}

// GetError returns the Error field value
func (o *OAuth2Error) GetError() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *OAuth2Error) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *OAuth2Error) SetError(v string) {
	o.Error = v
}

// GetErrorDescription returns the ErrorDescription field value if set, zero value otherwise.
func (o *OAuth2Error) GetErrorDescription() string {
	if o == nil || IsNil(o.ErrorDescription) {
		var ret string
		return ret
	}
	return *o.ErrorDescription
}

// GetErrorDescriptionOk returns a tuple with the ErrorDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuth2Error) GetErrorDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorDescription) {
		return nil, false
	}
	return o.ErrorDescription, true
}

// HasErrorDescription returns a boolean if a field has been set.
func (o *OAuth2Error) HasErrorDescription() bool {
	if o != nil && !IsNil(o.ErrorDescription) {
		return true
	}

	return false
}

// SetErrorDescription gets a reference to the given string and assigns it to the ErrorDescription field.
func (o *OAuth2Error) SetErrorDescription(v string) {
	o.ErrorDescription = &v
}

func (o OAuth2Error) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OAuth2Error) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["error"] = o.Error
	if !IsNil(o.ErrorDescription) {
		toSerialize["error_description"] = o.ErrorDescription
	}
	return toSerialize, nil
}

func (o *OAuth2Error) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"error",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOAuth2Error := _OAuth2Error{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOAuth2Error)

	if err != nil {
		return err
	}

	*o = OAuth2Error(varOAuth2Error)

	return err
}

type NullableOAuth2Error struct {
	value *OAuth2Error
	isSet bool
}

func (v NullableOAuth2Error) Get() *OAuth2Error {
	return v.value
}

func (v *NullableOAuth2Error) Set(val *OAuth2Error) {
	v.value = val
	v.isSet = true
}

func (v NullableOAuth2Error) IsSet() bool {
	return v.isSet
}

func (v *NullableOAuth2Error) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOAuth2Error(val *OAuth2Error) *NullableOAuth2Error {
	return &NullableOAuth2Error{value: val, isSet: true}
}

func (v NullableOAuth2Error) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOAuth2Error) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
