/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"encoding/json"
)

// checks if the JobDefinitionReportOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobDefinitionReportOptions{}

// JobDefinitionReportOptions Controls what data is included in the job report
type JobDefinitionReportOptions struct {
	// Include project fleets in the report
	AppFleets *bool `json:"app_fleets,omitempty"`
	// Include project info in the report
	AppInfo *bool `json:"app_info,omitempty"`
	// Include project environment variables in the report
	AppVars *bool   `json:"app_vars,omitempty"`
	Comment *string `json:"comment,omitempty"`
	// Include device activity data in the report
	DeviceActivity *bool `json:"device_activity,omitempty"`
	// Include device health data in the report
	DeviceHealth *bool `json:"device_health,omitempty"`
	// Include device info in the report
	DeviceInfo *bool `json:"device_info,omitempty"`
	// Include device environment variables in the report
	DeviceVars           *bool `json:"device_vars,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _JobDefinitionReportOptions JobDefinitionReportOptions

// NewJobDefinitionReportOptions instantiates a new JobDefinitionReportOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobDefinitionReportOptions() *JobDefinitionReportOptions {
	this := JobDefinitionReportOptions{}
	return &this
}

// NewJobDefinitionReportOptionsWithDefaults instantiates a new JobDefinitionReportOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobDefinitionReportOptionsWithDefaults() *JobDefinitionReportOptions {
	this := JobDefinitionReportOptions{}
	return &this
}

// GetAppFleets returns the AppFleets field value if set, zero value otherwise.
func (o *JobDefinitionReportOptions) GetAppFleets() bool {
	if o == nil || IsNil(o.AppFleets) {
		var ret bool
		return ret
	}
	return *o.AppFleets
}

// GetAppFleetsOk returns a tuple with the AppFleets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobDefinitionReportOptions) GetAppFleetsOk() (*bool, bool) {
	if o == nil || IsNil(o.AppFleets) {
		return nil, false
	}
	return o.AppFleets, true
}

// HasAppFleets returns a boolean if a field has been set.
func (o *JobDefinitionReportOptions) HasAppFleets() bool {
	if o != nil && !IsNil(o.AppFleets) {
		return true
	}

	return false
}

// SetAppFleets gets a reference to the given bool and assigns it to the AppFleets field.
func (o *JobDefinitionReportOptions) SetAppFleets(v bool) {
	o.AppFleets = &v
}

// GetAppInfo returns the AppInfo field value if set, zero value otherwise.
func (o *JobDefinitionReportOptions) GetAppInfo() bool {
	if o == nil || IsNil(o.AppInfo) {
		var ret bool
		return ret
	}
	return *o.AppInfo
}

// GetAppInfoOk returns a tuple with the AppInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobDefinitionReportOptions) GetAppInfoOk() (*bool, bool) {
	if o == nil || IsNil(o.AppInfo) {
		return nil, false
	}
	return o.AppInfo, true
}

// HasAppInfo returns a boolean if a field has been set.
func (o *JobDefinitionReportOptions) HasAppInfo() bool {
	if o != nil && !IsNil(o.AppInfo) {
		return true
	}

	return false
}

// SetAppInfo gets a reference to the given bool and assigns it to the AppInfo field.
func (o *JobDefinitionReportOptions) SetAppInfo(v bool) {
	o.AppInfo = &v
}

// GetAppVars returns the AppVars field value if set, zero value otherwise.
func (o *JobDefinitionReportOptions) GetAppVars() bool {
	if o == nil || IsNil(o.AppVars) {
		var ret bool
		return ret
	}
	return *o.AppVars
}

// GetAppVarsOk returns a tuple with the AppVars field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobDefinitionReportOptions) GetAppVarsOk() (*bool, bool) {
	if o == nil || IsNil(o.AppVars) {
		return nil, false
	}
	return o.AppVars, true
}

// HasAppVars returns a boolean if a field has been set.
func (o *JobDefinitionReportOptions) HasAppVars() bool {
	if o != nil && !IsNil(o.AppVars) {
		return true
	}

	return false
}

// SetAppVars gets a reference to the given bool and assigns it to the AppVars field.
func (o *JobDefinitionReportOptions) SetAppVars(v bool) {
	o.AppVars = &v
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *JobDefinitionReportOptions) GetComment() string {
	if o == nil || IsNil(o.Comment) {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobDefinitionReportOptions) GetCommentOk() (*string, bool) {
	if o == nil || IsNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *JobDefinitionReportOptions) HasComment() bool {
	if o != nil && !IsNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *JobDefinitionReportOptions) SetComment(v string) {
	o.Comment = &v
}

// GetDeviceActivity returns the DeviceActivity field value if set, zero value otherwise.
func (o *JobDefinitionReportOptions) GetDeviceActivity() bool {
	if o == nil || IsNil(o.DeviceActivity) {
		var ret bool
		return ret
	}
	return *o.DeviceActivity
}

// GetDeviceActivityOk returns a tuple with the DeviceActivity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobDefinitionReportOptions) GetDeviceActivityOk() (*bool, bool) {
	if o == nil || IsNil(o.DeviceActivity) {
		return nil, false
	}
	return o.DeviceActivity, true
}

// HasDeviceActivity returns a boolean if a field has been set.
func (o *JobDefinitionReportOptions) HasDeviceActivity() bool {
	if o != nil && !IsNil(o.DeviceActivity) {
		return true
	}

	return false
}

// SetDeviceActivity gets a reference to the given bool and assigns it to the DeviceActivity field.
func (o *JobDefinitionReportOptions) SetDeviceActivity(v bool) {
	o.DeviceActivity = &v
}

// GetDeviceHealth returns the DeviceHealth field value if set, zero value otherwise.
func (o *JobDefinitionReportOptions) GetDeviceHealth() bool {
	if o == nil || IsNil(o.DeviceHealth) {
		var ret bool
		return ret
	}
	return *o.DeviceHealth
}

// GetDeviceHealthOk returns a tuple with the DeviceHealth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobDefinitionReportOptions) GetDeviceHealthOk() (*bool, bool) {
	if o == nil || IsNil(o.DeviceHealth) {
		return nil, false
	}
	return o.DeviceHealth, true
}

// HasDeviceHealth returns a boolean if a field has been set.
func (o *JobDefinitionReportOptions) HasDeviceHealth() bool {
	if o != nil && !IsNil(o.DeviceHealth) {
		return true
	}

	return false
}

// SetDeviceHealth gets a reference to the given bool and assigns it to the DeviceHealth field.
func (o *JobDefinitionReportOptions) SetDeviceHealth(v bool) {
	o.DeviceHealth = &v
}

// GetDeviceInfo returns the DeviceInfo field value if set, zero value otherwise.
func (o *JobDefinitionReportOptions) GetDeviceInfo() bool {
	if o == nil || IsNil(o.DeviceInfo) {
		var ret bool
		return ret
	}
	return *o.DeviceInfo
}

// GetDeviceInfoOk returns a tuple with the DeviceInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobDefinitionReportOptions) GetDeviceInfoOk() (*bool, bool) {
	if o == nil || IsNil(o.DeviceInfo) {
		return nil, false
	}
	return o.DeviceInfo, true
}

// HasDeviceInfo returns a boolean if a field has been set.
func (o *JobDefinitionReportOptions) HasDeviceInfo() bool {
	if o != nil && !IsNil(o.DeviceInfo) {
		return true
	}

	return false
}

// SetDeviceInfo gets a reference to the given bool and assigns it to the DeviceInfo field.
func (o *JobDefinitionReportOptions) SetDeviceInfo(v bool) {
	o.DeviceInfo = &v
}

// GetDeviceVars returns the DeviceVars field value if set, zero value otherwise.
func (o *JobDefinitionReportOptions) GetDeviceVars() bool {
	if o == nil || IsNil(o.DeviceVars) {
		var ret bool
		return ret
	}
	return *o.DeviceVars
}

// GetDeviceVarsOk returns a tuple with the DeviceVars field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobDefinitionReportOptions) GetDeviceVarsOk() (*bool, bool) {
	if o == nil || IsNil(o.DeviceVars) {
		return nil, false
	}
	return o.DeviceVars, true
}

// HasDeviceVars returns a boolean if a field has been set.
func (o *JobDefinitionReportOptions) HasDeviceVars() bool {
	if o != nil && !IsNil(o.DeviceVars) {
		return true
	}

	return false
}

// SetDeviceVars gets a reference to the given bool and assigns it to the DeviceVars field.
func (o *JobDefinitionReportOptions) SetDeviceVars(v bool) {
	o.DeviceVars = &v
}

func (o JobDefinitionReportOptions) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobDefinitionReportOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AppFleets) {
		toSerialize["app_fleets"] = o.AppFleets
	}
	if !IsNil(o.AppInfo) {
		toSerialize["app_info"] = o.AppInfo
	}
	if !IsNil(o.AppVars) {
		toSerialize["app_vars"] = o.AppVars
	}
	if !IsNil(o.Comment) {
		toSerialize["comment"] = o.Comment
	}
	if !IsNil(o.DeviceActivity) {
		toSerialize["device_activity"] = o.DeviceActivity
	}
	if !IsNil(o.DeviceHealth) {
		toSerialize["device_health"] = o.DeviceHealth
	}
	if !IsNil(o.DeviceInfo) {
		toSerialize["device_info"] = o.DeviceInfo
	}
	if !IsNil(o.DeviceVars) {
		toSerialize["device_vars"] = o.DeviceVars
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *JobDefinitionReportOptions) UnmarshalJSON(data []byte) (err error) {
	varJobDefinitionReportOptions := _JobDefinitionReportOptions{}

	err = json.Unmarshal(data, &varJobDefinitionReportOptions)

	if err != nil {
		return err
	}

	*o = JobDefinitionReportOptions(varJobDefinitionReportOptions)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "app_fleets")
		delete(additionalProperties, "app_info")
		delete(additionalProperties, "app_vars")
		delete(additionalProperties, "comment")
		delete(additionalProperties, "device_activity")
		delete(additionalProperties, "device_health")
		delete(additionalProperties, "device_info")
		delete(additionalProperties, "device_vars")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableJobDefinitionReportOptions struct {
	value *JobDefinitionReportOptions
	isSet bool
}

func (v NullableJobDefinitionReportOptions) Get() *JobDefinitionReportOptions {
	return v.value
}

func (v *NullableJobDefinitionReportOptions) Set(val *JobDefinitionReportOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableJobDefinitionReportOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableJobDefinitionReportOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobDefinitionReportOptions(val *JobDefinitionReportOptions) *NullableJobDefinitionReportOptions {
	return &NullableJobDefinitionReportOptions{value: val, isSet: true}
}

func (v NullableJobDefinitionReportOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobDefinitionReportOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
