/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the GetDeviceHealthLog200ResponseHealthLogInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetDeviceHealthLog200ResponseHealthLogInner{}

// GetDeviceHealthLog200ResponseHealthLogInner struct for GetDeviceHealthLog200ResponseHealthLogInner
type GetDeviceHealthLog200ResponseHealthLogInner struct {
	Alert bool      `json:"alert"`
	Text  string    `json:"text"`
	When  time.Time `json:"when"`
}

type _GetDeviceHealthLog200ResponseHealthLogInner GetDeviceHealthLog200ResponseHealthLogInner

// NewGetDeviceHealthLog200ResponseHealthLogInner instantiates a new GetDeviceHealthLog200ResponseHealthLogInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetDeviceHealthLog200ResponseHealthLogInner(alert bool, text string, when time.Time) *GetDeviceHealthLog200ResponseHealthLogInner {
	this := GetDeviceHealthLog200ResponseHealthLogInner{}
	this.Alert = alert
	this.Text = text
	this.When = when
	return &this
}

// NewGetDeviceHealthLog200ResponseHealthLogInnerWithDefaults instantiates a new GetDeviceHealthLog200ResponseHealthLogInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetDeviceHealthLog200ResponseHealthLogInnerWithDefaults() *GetDeviceHealthLog200ResponseHealthLogInner {
	this := GetDeviceHealthLog200ResponseHealthLogInner{}
	return &this
}

// GetAlert returns the Alert field value
func (o *GetDeviceHealthLog200ResponseHealthLogInner) GetAlert() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Alert
}

// GetAlertOk returns a tuple with the Alert field value
// and a boolean to check if the value has been set.
func (o *GetDeviceHealthLog200ResponseHealthLogInner) GetAlertOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Alert, true
}

// SetAlert sets field value
func (o *GetDeviceHealthLog200ResponseHealthLogInner) SetAlert(v bool) {
	o.Alert = v
}

// GetText returns the Text field value
func (o *GetDeviceHealthLog200ResponseHealthLogInner) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *GetDeviceHealthLog200ResponseHealthLogInner) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *GetDeviceHealthLog200ResponseHealthLogInner) SetText(v string) {
	o.Text = v
}

// GetWhen returns the When field value
func (o *GetDeviceHealthLog200ResponseHealthLogInner) GetWhen() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.When
}

// GetWhenOk returns a tuple with the When field value
// and a boolean to check if the value has been set.
func (o *GetDeviceHealthLog200ResponseHealthLogInner) GetWhenOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.When, true
}

// SetWhen sets field value
func (o *GetDeviceHealthLog200ResponseHealthLogInner) SetWhen(v time.Time) {
	o.When = v
}

func (o GetDeviceHealthLog200ResponseHealthLogInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetDeviceHealthLog200ResponseHealthLogInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["alert"] = o.Alert
	toSerialize["text"] = o.Text
	toSerialize["when"] = o.When
	return toSerialize, nil
}

func (o *GetDeviceHealthLog200ResponseHealthLogInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"alert",
		"text",
		"when",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetDeviceHealthLog200ResponseHealthLogInner := _GetDeviceHealthLog200ResponseHealthLogInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetDeviceHealthLog200ResponseHealthLogInner)

	if err != nil {
		return err
	}

	*o = GetDeviceHealthLog200ResponseHealthLogInner(varGetDeviceHealthLog200ResponseHealthLogInner)

	return err
}

type NullableGetDeviceHealthLog200ResponseHealthLogInner struct {
	value *GetDeviceHealthLog200ResponseHealthLogInner
	isSet bool
}

func (v NullableGetDeviceHealthLog200ResponseHealthLogInner) Get() *GetDeviceHealthLog200ResponseHealthLogInner {
	return v.value
}

func (v *NullableGetDeviceHealthLog200ResponseHealthLogInner) Set(val *GetDeviceHealthLog200ResponseHealthLogInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDeviceHealthLog200ResponseHealthLogInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDeviceHealthLog200ResponseHealthLogInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDeviceHealthLog200ResponseHealthLogInner(val *GetDeviceHealthLog200ResponseHealthLogInner) *NullableGetDeviceHealthLog200ResponseHealthLogInner {
	return &NullableGetDeviceHealthLog200ResponseHealthLogInner{value: val, isSet: true}
}

func (v NullableGetDeviceHealthLog200ResponseHealthLogInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetDeviceHealthLog200ResponseHealthLogInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
