/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"encoding/json"
	"fmt"
)

// checks if the GetSessionsUsage200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSessionsUsage200Response{}

// GetSessionsUsage200Response struct for GetSessionsUsage200Response
type GetSessionsUsage200Response struct {
	Sessions []UsageSessionsData `json:"sessions"`
	// If the data is truncated that means that the parameters selected resulted in a response of over | the requested limit of data points, in order to ensure
	Truncated            bool `json:"truncated"`
	AdditionalProperties map[string]interface{}
}

type _GetSessionsUsage200Response GetSessionsUsage200Response

// NewGetSessionsUsage200Response instantiates a new GetSessionsUsage200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSessionsUsage200Response(sessions []UsageSessionsData, truncated bool) *GetSessionsUsage200Response {
	this := GetSessionsUsage200Response{}
	this.Sessions = sessions
	this.Truncated = truncated
	return &this
}

// NewGetSessionsUsage200ResponseWithDefaults instantiates a new GetSessionsUsage200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSessionsUsage200ResponseWithDefaults() *GetSessionsUsage200Response {
	this := GetSessionsUsage200Response{}
	return &this
}

// GetSessions returns the Sessions field value
func (o *GetSessionsUsage200Response) GetSessions() []UsageSessionsData {
	if o == nil {
		var ret []UsageSessionsData
		return ret
	}

	return o.Sessions
}

// GetSessionsOk returns a tuple with the Sessions field value
// and a boolean to check if the value has been set.
func (o *GetSessionsUsage200Response) GetSessionsOk() ([]UsageSessionsData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Sessions, true
}

// SetSessions sets field value
func (o *GetSessionsUsage200Response) SetSessions(v []UsageSessionsData) {
	o.Sessions = v
}

// GetTruncated returns the Truncated field value
func (o *GetSessionsUsage200Response) GetTruncated() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Truncated
}

// GetTruncatedOk returns a tuple with the Truncated field value
// and a boolean to check if the value has been set.
func (o *GetSessionsUsage200Response) GetTruncatedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Truncated, true
}

// SetTruncated sets field value
func (o *GetSessionsUsage200Response) SetTruncated(v bool) {
	o.Truncated = v
}

func (o GetSessionsUsage200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSessionsUsage200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sessions"] = o.Sessions
	toSerialize["truncated"] = o.Truncated

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetSessionsUsage200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sessions",
		"truncated",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetSessionsUsage200Response := _GetSessionsUsage200Response{}

	err = json.Unmarshal(data, &varGetSessionsUsage200Response)

	if err != nil {
		return err
	}

	*o = GetSessionsUsage200Response(varGetSessionsUsage200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "sessions")
		delete(additionalProperties, "truncated")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetSessionsUsage200Response struct {
	value *GetSessionsUsage200Response
	isSet bool
}

func (v NullableGetSessionsUsage200Response) Get() *GetSessionsUsage200Response {
	return v.value
}

func (v *NullableGetSessionsUsage200Response) Set(val *GetSessionsUsage200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSessionsUsage200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSessionsUsage200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSessionsUsage200Response(val *GetSessionsUsage200Response) *NullableGetSessionsUsage200Response {
	return &NullableGetSessionsUsage200Response{value: val, isSet: true}
}

func (v NullableGetSessionsUsage200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSessionsUsage200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
