/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"encoding/json"
)

// checks if the GetOrganizations200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetOrganizations200Response{}

// GetOrganizations200Response struct for GetOrganizations200Response
type GetOrganizations200Response struct {
	Organizations        []Organization `json:"organizations,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetOrganizations200Response GetOrganizations200Response

// NewGetOrganizations200Response instantiates a new GetOrganizations200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOrganizations200Response() *GetOrganizations200Response {
	this := GetOrganizations200Response{}
	return &this
}

// NewGetOrganizations200ResponseWithDefaults instantiates a new GetOrganizations200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOrganizations200ResponseWithDefaults() *GetOrganizations200Response {
	this := GetOrganizations200Response{}
	return &this
}

// GetOrganizations returns the Organizations field value if set, zero value otherwise.
func (o *GetOrganizations200Response) GetOrganizations() []Organization {
	if o == nil || IsNil(o.Organizations) {
		var ret []Organization
		return ret
	}
	return o.Organizations
}

// GetOrganizationsOk returns a tuple with the Organizations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizations200Response) GetOrganizationsOk() ([]Organization, bool) {
	if o == nil || IsNil(o.Organizations) {
		return nil, false
	}
	return o.Organizations, true
}

// HasOrganizations returns a boolean if a field has been set.
func (o *GetOrganizations200Response) HasOrganizations() bool {
	if o != nil && !IsNil(o.Organizations) {
		return true
	}

	return false
}

// SetOrganizations gets a reference to the given []Organization and assigns it to the Organizations field.
func (o *GetOrganizations200Response) SetOrganizations(v []Organization) {
	o.Organizations = v
}

func (o GetOrganizations200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetOrganizations200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Organizations) {
		toSerialize["organizations"] = o.Organizations
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetOrganizations200Response) UnmarshalJSON(data []byte) (err error) {
	varGetOrganizations200Response := _GetOrganizations200Response{}

	err = json.Unmarshal(data, &varGetOrganizations200Response)

	if err != nil {
		return err
	}

	*o = GetOrganizations200Response(varGetOrganizations200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "organizations")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetOrganizations200Response struct {
	value *GetOrganizations200Response
	isSet bool
}

func (v NullableGetOrganizations200Response) Get() *GetOrganizations200Response {
	return v.value
}

func (v *NullableGetOrganizations200Response) Set(val *GetOrganizations200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOrganizations200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOrganizations200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOrganizations200Response(val *GetOrganizations200Response) *NullableGetOrganizations200Response {
	return &NullableGetOrganizations200Response{value: val, isSet: true}
}

func (v NullableGetOrganizations200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOrganizations200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
