/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetDeviceEnvironmentVariablesByPin200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetDeviceEnvironmentVariablesByPin200Response{}

// GetDeviceEnvironmentVariablesByPin200Response struct for GetDeviceEnvironmentVariablesByPin200Response
type GetDeviceEnvironmentVariablesByPin200Response struct {
	// The environment variables for this device that have been set using host firmware or the Notehub API or UI.
	EnvironmentVariables map[string]string `json:"environment_variables"`
	// The environment variables as they will be seen by the device, fully resolved with project/fleet/device prioritization rules.
	EnvironmentVariablesEffective *map[string]string `json:"environment_variables_effective,omitempty"`
	// The environment variables that have been set using the env.default request through the Notecard API.
	EnvironmentVariablesEnvDefault map[string]string `json:"environment_variables_env_default"`
}

type _GetDeviceEnvironmentVariablesByPin200Response GetDeviceEnvironmentVariablesByPin200Response

// NewGetDeviceEnvironmentVariablesByPin200Response instantiates a new GetDeviceEnvironmentVariablesByPin200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetDeviceEnvironmentVariablesByPin200Response(environmentVariables map[string]string, environmentVariablesEnvDefault map[string]string) *GetDeviceEnvironmentVariablesByPin200Response {
	this := GetDeviceEnvironmentVariablesByPin200Response{}
	this.EnvironmentVariables = environmentVariables
	this.EnvironmentVariablesEnvDefault = environmentVariablesEnvDefault
	return &this
}

// NewGetDeviceEnvironmentVariablesByPin200ResponseWithDefaults instantiates a new GetDeviceEnvironmentVariablesByPin200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetDeviceEnvironmentVariablesByPin200ResponseWithDefaults() *GetDeviceEnvironmentVariablesByPin200Response {
	this := GetDeviceEnvironmentVariablesByPin200Response{}
	return &this
}

// GetEnvironmentVariables returns the EnvironmentVariables field value
func (o *GetDeviceEnvironmentVariablesByPin200Response) GetEnvironmentVariables() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.EnvironmentVariables
}

// GetEnvironmentVariablesOk returns a tuple with the EnvironmentVariables field value
// and a boolean to check if the value has been set.
func (o *GetDeviceEnvironmentVariablesByPin200Response) GetEnvironmentVariablesOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnvironmentVariables, true
}

// SetEnvironmentVariables sets field value
func (o *GetDeviceEnvironmentVariablesByPin200Response) SetEnvironmentVariables(v map[string]string) {
	o.EnvironmentVariables = v
}

// GetEnvironmentVariablesEffective returns the EnvironmentVariablesEffective field value if set, zero value otherwise.
func (o *GetDeviceEnvironmentVariablesByPin200Response) GetEnvironmentVariablesEffective() map[string]string {
	if o == nil || IsNil(o.EnvironmentVariablesEffective) {
		var ret map[string]string
		return ret
	}
	return *o.EnvironmentVariablesEffective
}

// GetEnvironmentVariablesEffectiveOk returns a tuple with the EnvironmentVariablesEffective field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDeviceEnvironmentVariablesByPin200Response) GetEnvironmentVariablesEffectiveOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.EnvironmentVariablesEffective) {
		return nil, false
	}
	return o.EnvironmentVariablesEffective, true
}

// HasEnvironmentVariablesEffective returns a boolean if a field has been set.
func (o *GetDeviceEnvironmentVariablesByPin200Response) HasEnvironmentVariablesEffective() bool {
	if o != nil && !IsNil(o.EnvironmentVariablesEffective) {
		return true
	}

	return false
}

// SetEnvironmentVariablesEffective gets a reference to the given map[string]string and assigns it to the EnvironmentVariablesEffective field.
func (o *GetDeviceEnvironmentVariablesByPin200Response) SetEnvironmentVariablesEffective(v map[string]string) {
	o.EnvironmentVariablesEffective = &v
}

// GetEnvironmentVariablesEnvDefault returns the EnvironmentVariablesEnvDefault field value
func (o *GetDeviceEnvironmentVariablesByPin200Response) GetEnvironmentVariablesEnvDefault() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.EnvironmentVariablesEnvDefault
}

// GetEnvironmentVariablesEnvDefaultOk returns a tuple with the EnvironmentVariablesEnvDefault field value
// and a boolean to check if the value has been set.
func (o *GetDeviceEnvironmentVariablesByPin200Response) GetEnvironmentVariablesEnvDefaultOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnvironmentVariablesEnvDefault, true
}

// SetEnvironmentVariablesEnvDefault sets field value
func (o *GetDeviceEnvironmentVariablesByPin200Response) SetEnvironmentVariablesEnvDefault(v map[string]string) {
	o.EnvironmentVariablesEnvDefault = v
}

func (o GetDeviceEnvironmentVariablesByPin200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetDeviceEnvironmentVariablesByPin200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["environment_variables"] = o.EnvironmentVariables
	if !IsNil(o.EnvironmentVariablesEffective) {
		toSerialize["environment_variables_effective"] = o.EnvironmentVariablesEffective
	}
	toSerialize["environment_variables_env_default"] = o.EnvironmentVariablesEnvDefault
	return toSerialize, nil
}

func (o *GetDeviceEnvironmentVariablesByPin200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"environment_variables",
		"environment_variables_env_default",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetDeviceEnvironmentVariablesByPin200Response := _GetDeviceEnvironmentVariablesByPin200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetDeviceEnvironmentVariablesByPin200Response)

	if err != nil {
		return err
	}

	*o = GetDeviceEnvironmentVariablesByPin200Response(varGetDeviceEnvironmentVariablesByPin200Response)

	return err
}

type NullableGetDeviceEnvironmentVariablesByPin200Response struct {
	value *GetDeviceEnvironmentVariablesByPin200Response
	isSet bool
}

func (v NullableGetDeviceEnvironmentVariablesByPin200Response) Get() *GetDeviceEnvironmentVariablesByPin200Response {
	return v.value
}

func (v *NullableGetDeviceEnvironmentVariablesByPin200Response) Set(val *GetDeviceEnvironmentVariablesByPin200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDeviceEnvironmentVariablesByPin200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDeviceEnvironmentVariablesByPin200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDeviceEnvironmentVariablesByPin200Response(val *GetDeviceEnvironmentVariablesByPin200Response) *NullableGetDeviceEnvironmentVariablesByPin200Response {
	return &NullableGetDeviceEnvironmentVariablesByPin200Response{value: val, isSet: true}
}

func (v NullableGetDeviceEnvironmentVariablesByPin200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetDeviceEnvironmentVariablesByPin200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
