/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"encoding/json"
)

// checks if the GetDbNote200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetDbNote200Response{}

// GetDbNote200Response struct for GetDbNote200Response
type GetDbNote200Response struct {
	// The note body
	Body map[string]interface{} `json:"body,omitempty"`
	// The note payload
	Payload *string `json:"payload,omitempty"`
	// The time the Note was added to the Notecard or Notehub
	Time *int32 `json:"time,omitempty"`
}

// NewGetDbNote200Response instantiates a new GetDbNote200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetDbNote200Response() *GetDbNote200Response {
	this := GetDbNote200Response{}
	return &this
}

// NewGetDbNote200ResponseWithDefaults instantiates a new GetDbNote200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetDbNote200ResponseWithDefaults() *GetDbNote200Response {
	this := GetDbNote200Response{}
	return &this
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *GetDbNote200Response) GetBody() map[string]interface{} {
	if o == nil || IsNil(o.Body) {
		var ret map[string]interface{}
		return ret
	}
	return o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDbNote200Response) GetBodyOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Body) {
		return map[string]interface{}{}, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *GetDbNote200Response) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given map[string]interface{} and assigns it to the Body field.
func (o *GetDbNote200Response) SetBody(v map[string]interface{}) {
	o.Body = v
}

// GetPayload returns the Payload field value if set, zero value otherwise.
func (o *GetDbNote200Response) GetPayload() string {
	if o == nil || IsNil(o.Payload) {
		var ret string
		return ret
	}
	return *o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDbNote200Response) GetPayloadOk() (*string, bool) {
	if o == nil || IsNil(o.Payload) {
		return nil, false
	}
	return o.Payload, true
}

// HasPayload returns a boolean if a field has been set.
func (o *GetDbNote200Response) HasPayload() bool {
	if o != nil && !IsNil(o.Payload) {
		return true
	}

	return false
}

// SetPayload gets a reference to the given string and assigns it to the Payload field.
func (o *GetDbNote200Response) SetPayload(v string) {
	o.Payload = &v
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *GetDbNote200Response) GetTime() int32 {
	if o == nil || IsNil(o.Time) {
		var ret int32
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDbNote200Response) GetTimeOk() (*int32, bool) {
	if o == nil || IsNil(o.Time) {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *GetDbNote200Response) HasTime() bool {
	if o != nil && !IsNil(o.Time) {
		return true
	}

	return false
}

// SetTime gets a reference to the given int32 and assigns it to the Time field.
func (o *GetDbNote200Response) SetTime(v int32) {
	o.Time = &v
}

func (o GetDbNote200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetDbNote200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	if !IsNil(o.Payload) {
		toSerialize["payload"] = o.Payload
	}
	if !IsNil(o.Time) {
		toSerialize["time"] = o.Time
	}
	return toSerialize, nil
}

type NullableGetDbNote200Response struct {
	value *GetDbNote200Response
	isSet bool
}

func (v NullableGetDbNote200Response) Get() *GetDbNote200Response {
	return v.value
}

func (v *NullableGetDbNote200Response) Set(val *GetDbNote200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDbNote200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDbNote200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDbNote200Response(val *GetDbNote200Response) *NullableGetDbNote200Response {
	return &NullableGetDbNote200Response{value: val, isSet: true}
}

func (v NullableGetDbNote200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetDbNote200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
