/*
Notehub API

The OpenAPI definition for the Notehub.io API.

API version: 1.2.0
Contact: engineering@blues.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notehub

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the ProjectSecret type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectSecret{}

// ProjectSecret Metadata for a project secret. The value is never returned.
type ProjectSecret struct {
	// When the secret was first created.
	Created time.Time `json:"created"`
	// The actor who created the secret.
	CreatedBy string `json:"created_by"`
	// When the secret was last updated.
	Modified *time.Time `json:"modified,omitempty"`
	// The actor who last updated the secret.
	ModifiedBy *string `json:"modified_by,omitempty"`
	// The secret name (alphanumeric and underscores only).
	Name                 string `json:"name"`
	AdditionalProperties map[string]interface{}
}

type _ProjectSecret ProjectSecret

// NewProjectSecret instantiates a new ProjectSecret object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectSecret(created time.Time, createdBy string, name string) *ProjectSecret {
	this := ProjectSecret{}
	this.Created = created
	this.CreatedBy = createdBy
	this.Name = name
	return &this
}

// NewProjectSecretWithDefaults instantiates a new ProjectSecret object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectSecretWithDefaults() *ProjectSecret {
	this := ProjectSecret{}
	return &this
}

// GetCreated returns the Created field value
func (o *ProjectSecret) GetCreated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *ProjectSecret) GetCreatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *ProjectSecret) SetCreated(v time.Time) {
	o.Created = v
}

// GetCreatedBy returns the CreatedBy field value
func (o *ProjectSecret) GetCreatedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value
// and a boolean to check if the value has been set.
func (o *ProjectSecret) GetCreatedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedBy, true
}

// SetCreatedBy sets field value
func (o *ProjectSecret) SetCreatedBy(v string) {
	o.CreatedBy = v
}

// GetModified returns the Modified field value if set, zero value otherwise.
func (o *ProjectSecret) GetModified() time.Time {
	if o == nil || IsNil(o.Modified) {
		var ret time.Time
		return ret
	}
	return *o.Modified
}

// GetModifiedOk returns a tuple with the Modified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectSecret) GetModifiedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Modified) {
		return nil, false
	}
	return o.Modified, true
}

// HasModified returns a boolean if a field has been set.
func (o *ProjectSecret) HasModified() bool {
	if o != nil && !IsNil(o.Modified) {
		return true
	}

	return false
}

// SetModified gets a reference to the given time.Time and assigns it to the Modified field.
func (o *ProjectSecret) SetModified(v time.Time) {
	o.Modified = &v
}

// GetModifiedBy returns the ModifiedBy field value if set, zero value otherwise.
func (o *ProjectSecret) GetModifiedBy() string {
	if o == nil || IsNil(o.ModifiedBy) {
		var ret string
		return ret
	}
	return *o.ModifiedBy
}

// GetModifiedByOk returns a tuple with the ModifiedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectSecret) GetModifiedByOk() (*string, bool) {
	if o == nil || IsNil(o.ModifiedBy) {
		return nil, false
	}
	return o.ModifiedBy, true
}

// HasModifiedBy returns a boolean if a field has been set.
func (o *ProjectSecret) HasModifiedBy() bool {
	if o != nil && !IsNil(o.ModifiedBy) {
		return true
	}

	return false
}

// SetModifiedBy gets a reference to the given string and assigns it to the ModifiedBy field.
func (o *ProjectSecret) SetModifiedBy(v string) {
	o.ModifiedBy = &v
}

// GetName returns the Name field value
func (o *ProjectSecret) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ProjectSecret) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ProjectSecret) SetName(v string) {
	o.Name = v
}

func (o ProjectSecret) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectSecret) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["created"] = o.Created
	toSerialize["created_by"] = o.CreatedBy
	if !IsNil(o.Modified) {
		toSerialize["modified"] = o.Modified
	}
	if !IsNil(o.ModifiedBy) {
		toSerialize["modified_by"] = o.ModifiedBy
	}
	toSerialize["name"] = o.Name

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProjectSecret) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"created",
		"created_by",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProjectSecret := _ProjectSecret{}

	err = json.Unmarshal(data, &varProjectSecret)

	if err != nil {
		return err
	}

	*o = ProjectSecret(varProjectSecret)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "created")
		delete(additionalProperties, "created_by")
		delete(additionalProperties, "modified")
		delete(additionalProperties, "modified_by")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableProjectSecret struct {
	value *ProjectSecret
	isSet bool
}

func (v NullableProjectSecret) Get() *ProjectSecret {
	return v.value
}

func (v *NullableProjectSecret) Set(val *ProjectSecret) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectSecret) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectSecret) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectSecret(val *ProjectSecret) *NullableProjectSecret {
	return &NullableProjectSecret{value: val, isSet: true}
}

func (v NullableProjectSecret) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectSecret) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
